// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package chains

import (
	"context"
	mock "github.com/stretchr/testify/mock"
)

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// TxPacketEvents provides a mock function for the type MockClient
func (_mock *MockClient) TxPacketEvents(ctx context.Context, txHashes [][]byte) ([]PacketEvent, error) {
	ret := _mock.Called(ctx, txHashes)

	if len(ret) == 0 {
		panic("no return value specified for TxPacketEvents")
	}

	var r0 []PacketEvent
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, [][]byte) ([]PacketEvent, error)); ok {
		return returnFunc(ctx, txHashes)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, [][]byte) []PacketEvent); ok {
		r0 = returnFunc(ctx, txHashes)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]PacketEvent)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, [][]byte) error); ok {
		r1 = returnFunc(ctx, txHashes)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_TxPacketEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TxPacketEvents'
type MockClient_TxPacketEvents_Call struct {
	*mock.Call
}

// TxPacketEvents is a helper method to define mock.On call
//   - ctx context.Context
//   - txHashes [][]byte
func (_e *MockClient_Expecter) TxPacketEvents(ctx any, txHashes any) *MockClient_TxPacketEvents_Call {
	return &MockClient_TxPacketEvents_Call{Call: _e.mock.On("TxPacketEvents", ctx, txHashes)}
}

func (_c *MockClient_TxPacketEvents_Call) Run(run func(ctx context.Context, txHashes [][]byte)) *MockClient_TxPacketEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 [][]byte
		if args[1] != nil {
			arg1 = args[1].([][]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_TxPacketEvents_Call) Return(packetEvents []PacketEvent, err error) *MockClient_TxPacketEvents_Call {
	_c.Call.Return(packetEvents, err)
	return _c
}

func (_c *MockClient_TxPacketEvents_Call) RunAndReturn(run func(ctx context.Context, txHashes [][]byte) ([]PacketEvent, error)) *MockClient_TxPacketEvents_Call {
	_c.Call.Return(run)
	return _c
}
