// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package chains

import (
	"context"
	"github.com/cosmos/ibc/link/internal/types/v2"
	mock "github.com/stretchr/testify/mock"
)

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// ChainID provides a mock function for the type MockClient
func (_mock *MockClient) ChainID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ChainID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockClient_ChainID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChainID'
type MockClient_ChainID_Call struct {
	*mock.Call
}

// ChainID is a helper method to define mock.On call
func (_e *MockClient_Expecter) ChainID() *MockClient_ChainID_Call {
	return &MockClient_ChainID_Call{Call: _e.mock.On("ChainID")}
}

func (_c *MockClient_ChainID_Call) Run(run func()) *MockClient_ChainID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_ChainID_Call) Return(s string) *MockClient_ChainID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockClient_ChainID_Call) RunAndReturn(run func() string) *MockClient_ChainID_Call {
	_c.Call.Return(run)
	return _c
}

// TxPacketEvents provides a mock function for the type MockClient
func (_mock *MockClient) TxPacketEvents(ctx context.Context, txHash []byte) ([]v2.PacketEvent, error) {
	ret := _mock.Called(ctx, txHash)

	if len(ret) == 0 {
		panic("no return value specified for TxPacketEvents")
	}

	var r0 []v2.PacketEvent
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte) ([]v2.PacketEvent, error)); ok {
		return returnFunc(ctx, txHash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte) []v2.PacketEvent); ok {
		r0 = returnFunc(ctx, txHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]v2.PacketEvent)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []byte) error); ok {
		r1 = returnFunc(ctx, txHash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_TxPacketEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TxPacketEvents'
type MockClient_TxPacketEvents_Call struct {
	*mock.Call
}

// TxPacketEvents is a helper method to define mock.On call
//   - ctx context.Context
//   - txHash []byte
func (_e *MockClient_Expecter) TxPacketEvents(ctx any, txHash any) *MockClient_TxPacketEvents_Call {
	return &MockClient_TxPacketEvents_Call{Call: _e.mock.On("TxPacketEvents", ctx, txHash)}
}

func (_c *MockClient_TxPacketEvents_Call) Run(run func(ctx context.Context, txHash []byte)) *MockClient_TxPacketEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_TxPacketEvents_Call) Return(packetEvents []v2.PacketEvent, err error) *MockClient_TxPacketEvents_Call {
	_c.Call.Return(packetEvents, err)
	return _c
}

func (_c *MockClient_TxPacketEvents_Call) RunAndReturn(run func(ctx context.Context, txHash []byte) ([]v2.PacketEvent, error)) *MockClient_TxPacketEvents_Call {
	_c.Call.Return(run)
	return _c
}
