#!/bin/sh

# SPDX-License-Identifier: Apache-2.0

set -eu

git rev-parse -q --verify MERGE_HEAD >/dev/null 2>&1 && exit 0

author=$(git var GIT_AUTHOR_IDENT)
author=${author% *}
author=${author% *}

committer=$(git var GIT_COMMITTER_IDENT)
committer=${committer% *}
committer=${committer% *}

git -c trailer.separators=: interpret-trailers --parse --no-divider "$1" |
	grep -iFqx -e "Signed-off-by: $author" -e "Signed-off-by: $committer" && exit 0

printf >&2 'Missing DCO sign-off. Re-run your commit command with --signoff.\n'
exit 1
