// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: prover.proto

package prover

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ProverServiceName is the fully-qualified name of the ProverService service.
	ProverServiceName = "ibc.v2.prover.ProverService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ProverServiceLatestProvableHeightProcedure is the fully-qualified name of the ProverService's
	// LatestProvableHeight RPC.
	ProverServiceLatestProvableHeightProcedure = "/ibc.v2.prover.ProverService/LatestProvableHeight"
	// ProverServicePrepareProcedure is the fully-qualified name of the ProverService's Prepare RPC.
	ProverServicePrepareProcedure = "/ibc.v2.prover.ProverService/Prepare"
)

// ProverServiceClient is a client for the ibc.v2.prover.ProverService service.
type ProverServiceClient interface {
	// LatestProvableHeight selects the target height and counterparty timestamp.
	LatestProvableHeight(context.Context, *connect.Request[LatestProvableHeightRequest]) (*connect.Response[LatestProvableHeightResponse], error)
	// Prepare returns one client-only checkpoint or proofs for the entire batch.
	Prepare(context.Context, *connect.Request[PrepareRequest]) (*connect.Response[PrepareResponse], error)
}

// NewProverServiceClient constructs a client for the ibc.v2.prover.ProverService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewProverServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ProverServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	proverServiceMethods := File_prover_proto.Services().ByName("ProverService").Methods()
	return &proverServiceClient{
		latestProvableHeight: connect.NewClient[LatestProvableHeightRequest, LatestProvableHeightResponse](
			httpClient,
			baseURL+ProverServiceLatestProvableHeightProcedure,
			connect.WithSchema(proverServiceMethods.ByName("LatestProvableHeight")),
			connect.WithClientOptions(opts...),
		),
		prepare: connect.NewClient[PrepareRequest, PrepareResponse](
			httpClient,
			baseURL+ProverServicePrepareProcedure,
			connect.WithSchema(proverServiceMethods.ByName("Prepare")),
			connect.WithClientOptions(opts...),
		),
	}
}

// proverServiceClient implements ProverServiceClient.
type proverServiceClient struct {
	latestProvableHeight *connect.Client[LatestProvableHeightRequest, LatestProvableHeightResponse]
	prepare              *connect.Client[PrepareRequest, PrepareResponse]
}

// LatestProvableHeight calls ibc.v2.prover.ProverService.LatestProvableHeight.
func (c *proverServiceClient) LatestProvableHeight(ctx context.Context, req *connect.Request[LatestProvableHeightRequest]) (*connect.Response[LatestProvableHeightResponse], error) {
	return c.latestProvableHeight.CallUnary(ctx, req)
}

// Prepare calls ibc.v2.prover.ProverService.Prepare.
func (c *proverServiceClient) Prepare(ctx context.Context, req *connect.Request[PrepareRequest]) (*connect.Response[PrepareResponse], error) {
	return c.prepare.CallUnary(ctx, req)
}

// ProverServiceHandler is an implementation of the ibc.v2.prover.ProverService service.
type ProverServiceHandler interface {
	// LatestProvableHeight selects the target height and counterparty timestamp.
	LatestProvableHeight(context.Context, *connect.Request[LatestProvableHeightRequest]) (*connect.Response[LatestProvableHeightResponse], error)
	// Prepare returns one client-only checkpoint or proofs for the entire batch.
	Prepare(context.Context, *connect.Request[PrepareRequest]) (*connect.Response[PrepareResponse], error)
}

// NewProverServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewProverServiceHandler(svc ProverServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	proverServiceMethods := File_prover_proto.Services().ByName("ProverService").Methods()
	proverServiceLatestProvableHeightHandler := connect.NewUnaryHandler(
		ProverServiceLatestProvableHeightProcedure,
		svc.LatestProvableHeight,
		connect.WithSchema(proverServiceMethods.ByName("LatestProvableHeight")),
		connect.WithHandlerOptions(opts...),
	)
	proverServicePrepareHandler := connect.NewUnaryHandler(
		ProverServicePrepareProcedure,
		svc.Prepare,
		connect.WithSchema(proverServiceMethods.ByName("Prepare")),
		connect.WithHandlerOptions(opts...),
	)
	return "/ibc.v2.prover.ProverService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ProverServiceLatestProvableHeightProcedure:
			proverServiceLatestProvableHeightHandler.ServeHTTP(w, r)
		case ProverServicePrepareProcedure:
			proverServicePrepareHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedProverServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedProverServiceHandler struct{}

func (UnimplementedProverServiceHandler) LatestProvableHeight(context.Context, *connect.Request[LatestProvableHeightRequest]) (*connect.Response[LatestProvableHeightResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ibc.v2.prover.ProverService.LatestProvableHeight is not implemented"))
}

func (UnimplementedProverServiceHandler) Prepare(context.Context, *connect.Request[PrepareRequest]) (*connect.Response[PrepareResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ibc.v2.prover.ProverService.Prepare is not implemented"))
}
