# SPDX-License-Identifier: Apache-2.0

version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    target-branch: development
    schedule:
      interval: weekly

  - package-ecosystem: gomod
    directories:
      - "/link"
      - "/e2e"
    target-branch: development
    schedule:
      interval: weekly
