# SPDX-License-Identifier: Apache-2.0

grpc:
  listen: 0.0.0.0:9090

  keys:
    - id: attestor-41001
      backend: file
      algorithm: secp256k1eth
      key_file: keys/attestor-41001.hex

    - id: attestor-41002
      backend: file
      algorithm: secp256k1eth
      key_file: keys/attestor-41002.hex
