// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package attestor

import (
	"context"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAttestor creates a new instance of MockAttestor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAttestor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAttestor {
	mock := &MockAttestor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAttestor is an autogenerated mock type for the Attestor type
type MockAttestor struct {
	mock.Mock
}

type MockAttestor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAttestor) EXPECT() *MockAttestor_Expecter {
	return &MockAttestor_Expecter{mock: &_m.Mock}
}

// Address provides a mock function for the type MockAttestor
func (_mock *MockAttestor) Address() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Address")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockAttestor_Address_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Address'
type MockAttestor_Address_Call struct {
	*mock.Call
}

// Address is a helper method to define mock.On call
func (_e *MockAttestor_Expecter) Address() *MockAttestor_Address_Call {
	return &MockAttestor_Address_Call{Call: _e.mock.On("Address")}
}

func (_c *MockAttestor_Address_Call) Run(run func()) *MockAttestor_Address_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAttestor_Address_Call) Return(s string) *MockAttestor_Address_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockAttestor_Address_Call) RunAndReturn(run func() string) *MockAttestor_Address_Call {
	_c.Call.Return(run)
	return _c
}

// Alias provides a mock function for the type MockAttestor
func (_mock *MockAttestor) Alias() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Alias")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockAttestor_Alias_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Alias'
type MockAttestor_Alias_Call struct {
	*mock.Call
}

// Alias is a helper method to define mock.On call
func (_e *MockAttestor_Expecter) Alias() *MockAttestor_Alias_Call {
	return &MockAttestor_Alias_Call{Call: _e.mock.On("Alias")}
}

func (_c *MockAttestor_Alias_Call) Run(run func()) *MockAttestor_Alias_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAttestor_Alias_Call) Return(s string) *MockAttestor_Alias_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockAttestor_Alias_Call) RunAndReturn(run func() string) *MockAttestor_Alias_Call {
	_c.Call.Return(run)
	return _c
}

// ChainID provides a mock function for the type MockAttestor
func (_mock *MockAttestor) ChainID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ChainID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockAttestor_ChainID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChainID'
type MockAttestor_ChainID_Call struct {
	*mock.Call
}

// ChainID is a helper method to define mock.On call
func (_e *MockAttestor_Expecter) ChainID() *MockAttestor_ChainID_Call {
	return &MockAttestor_ChainID_Call{Call: _e.mock.On("ChainID")}
}

func (_c *MockAttestor_ChainID_Call) Run(run func()) *MockAttestor_ChainID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAttestor_ChainID_Call) Return(s string) *MockAttestor_ChainID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockAttestor_ChainID_Call) RunAndReturn(run func() string) *MockAttestor_ChainID_Call {
	_c.Call.Return(run)
	return _c
}

// IsLocal provides a mock function for the type MockAttestor
func (_mock *MockAttestor) IsLocal() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsLocal")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockAttestor_IsLocal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsLocal'
type MockAttestor_IsLocal_Call struct {
	*mock.Call
}

// IsLocal is a helper method to define mock.On call
func (_e *MockAttestor_Expecter) IsLocal() *MockAttestor_IsLocal_Call {
	return &MockAttestor_IsLocal_Call{Call: _e.mock.On("IsLocal")}
}

func (_c *MockAttestor_IsLocal_Call) Run(run func()) *MockAttestor_IsLocal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAttestor_IsLocal_Call) Return(b bool) *MockAttestor_IsLocal_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockAttestor_IsLocal_Call) RunAndReturn(run func() bool) *MockAttestor_IsLocal_Call {
	_c.Call.Return(run)
	return _c
}

// LatestHeight provides a mock function for the type MockAttestor
func (_mock *MockAttestor) LatestHeight(ctx context.Context) (uint64, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for LatestHeight")
	}

	var r0 uint64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (uint64, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) uint64); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(uint64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAttestor_LatestHeight_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LatestHeight'
type MockAttestor_LatestHeight_Call struct {
	*mock.Call
}

// LatestHeight is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAttestor_Expecter) LatestHeight(ctx any) *MockAttestor_LatestHeight_Call {
	return &MockAttestor_LatestHeight_Call{Call: _e.mock.On("LatestHeight", ctx)}
}

func (_c *MockAttestor_LatestHeight_Call) Run(run func(ctx context.Context)) *MockAttestor_LatestHeight_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAttestor_LatestHeight_Call) Return(v uint64, err error) *MockAttestor_LatestHeight_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockAttestor_LatestHeight_Call) RunAndReturn(run func(ctx context.Context) (uint64, error)) *MockAttestor_LatestHeight_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function for the type MockAttestor
func (_mock *MockAttestor) Name() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockAttestor_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockAttestor_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockAttestor_Expecter) Name() *MockAttestor_Name_Call {
	return &MockAttestor_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockAttestor_Name_Call) Run(run func()) *MockAttestor_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAttestor_Name_Call) Return(s string) *MockAttestor_Name_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockAttestor_Name_Call) RunAndReturn(run func() string) *MockAttestor_Name_Call {
	_c.Call.Return(run)
	return _c
}

// PacketAttestation provides a mock function for the type MockAttestor
func (_mock *MockAttestor) PacketAttestation(ctx context.Context, req PacketAttestationRequest) (Attestation, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for PacketAttestation")
	}

	var r0 Attestation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, PacketAttestationRequest) (Attestation, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, PacketAttestationRequest) Attestation); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Get(0).(Attestation)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, PacketAttestationRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAttestor_PacketAttestation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PacketAttestation'
type MockAttestor_PacketAttestation_Call struct {
	*mock.Call
}

// PacketAttestation is a helper method to define mock.On call
//   - ctx context.Context
//   - req PacketAttestationRequest
func (_e *MockAttestor_Expecter) PacketAttestation(ctx any, req any) *MockAttestor_PacketAttestation_Call {
	return &MockAttestor_PacketAttestation_Call{Call: _e.mock.On("PacketAttestation", ctx, req)}
}

func (_c *MockAttestor_PacketAttestation_Call) Run(run func(ctx context.Context, req PacketAttestationRequest)) *MockAttestor_PacketAttestation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 PacketAttestationRequest
		if args[1] != nil {
			arg1 = args[1].(PacketAttestationRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAttestor_PacketAttestation_Call) Return(attestation Attestation, err error) *MockAttestor_PacketAttestation_Call {
	_c.Call.Return(attestation, err)
	return _c
}

func (_c *MockAttestor_PacketAttestation_Call) RunAndReturn(run func(ctx context.Context, req PacketAttestationRequest) (Attestation, error)) *MockAttestor_PacketAttestation_Call {
	_c.Call.Return(run)
	return _c
}

// StateAttestation provides a mock function for the type MockAttestor
func (_mock *MockAttestor) StateAttestation(ctx context.Context, height uint64) (Attestation, error) {
	ret := _mock.Called(ctx, height)

	if len(ret) == 0 {
		panic("no return value specified for StateAttestation")
	}

	var r0 Attestation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) (Attestation, error)); ok {
		return returnFunc(ctx, height)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) Attestation); ok {
		r0 = returnFunc(ctx, height)
	} else {
		r0 = ret.Get(0).(Attestation)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = returnFunc(ctx, height)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAttestor_StateAttestation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StateAttestation'
type MockAttestor_StateAttestation_Call struct {
	*mock.Call
}

// StateAttestation is a helper method to define mock.On call
//   - ctx context.Context
//   - height uint64
func (_e *MockAttestor_Expecter) StateAttestation(ctx any, height any) *MockAttestor_StateAttestation_Call {
	return &MockAttestor_StateAttestation_Call{Call: _e.mock.On("StateAttestation", ctx, height)}
}

func (_c *MockAttestor_StateAttestation_Call) Run(run func(ctx context.Context, height uint64)) *MockAttestor_StateAttestation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAttestor_StateAttestation_Call) Return(attestation Attestation, err error) *MockAttestor_StateAttestation_Call {
	_c.Call.Return(attestation, err)
	return _c
}

func (_c *MockAttestor_StateAttestation_Call) RunAndReturn(run func(ctx context.Context, height uint64) (Attestation, error)) *MockAttestor_StateAttestation_Call {
	_c.Call.Return(run)
	return _c
}
