// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"github.com/cosmos/ibc-go/v11/modules/core/04-channel/v2/types"
	"github.com/cosmos/ibc/cli/internal/types/v2"
	mock "github.com/stretchr/testify/mock"
	"time"
)

// NewMockProver creates a new instance of MockProver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProver {
	mock := &MockProver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProver is an autogenerated mock type for the Prover type
type MockProver struct {
	mock.Mock
}

type MockProver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProver) EXPECT() *MockProver_Expecter {
	return &MockProver_Expecter{mock: &_m.Mock}
}

// LatestProvableHeight provides a mock function for the type MockProver
func (_mock *MockProver) LatestProvableHeight(ctx context.Context) (uint64, time.Time, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for LatestProvableHeight")
	}

	var r0 uint64
	var r1 time.Time
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (uint64, time.Time, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) uint64); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(uint64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) time.Time); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Get(1).(time.Time)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context) error); ok {
		r2 = returnFunc(ctx)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockProver_LatestProvableHeight_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LatestProvableHeight'
type MockProver_LatestProvableHeight_Call struct {
	*mock.Call
}

// LatestProvableHeight is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockProver_Expecter) LatestProvableHeight(ctx any) *MockProver_LatestProvableHeight_Call {
	return &MockProver_LatestProvableHeight_Call{Call: _e.mock.On("LatestProvableHeight", ctx)}
}

func (_c *MockProver_LatestProvableHeight_Call) Run(run func(ctx context.Context)) *MockProver_LatestProvableHeight_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockProver_LatestProvableHeight_Call) Return(v uint64, time1 time.Time, err error) *MockProver_LatestProvableHeight_Call {
	_c.Call.Return(v, time1, err)
	return _c
}

func (_c *MockProver_LatestProvableHeight_Call) RunAndReturn(run func(ctx context.Context) (uint64, time.Time, error)) *MockProver_LatestProvableHeight_Call {
	_c.Call.Return(run)
	return _c
}

// Prepare provides a mock function for the type MockProver
func (_mock *MockProver) Prepare(ctx context.Context, height uint64, kind v2.ProofKind, packets []types.Packet) (*v2.Preparation, error) {
	ret := _mock.Called(ctx, height, kind, packets)

	if len(ret) == 0 {
		panic("no return value specified for Prepare")
	}

	var r0 *v2.Preparation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, v2.ProofKind, []types.Packet) (*v2.Preparation, error)); ok {
		return returnFunc(ctx, height, kind, packets)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, v2.ProofKind, []types.Packet) *v2.Preparation); ok {
		r0 = returnFunc(ctx, height, kind, packets)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v2.Preparation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64, v2.ProofKind, []types.Packet) error); ok {
		r1 = returnFunc(ctx, height, kind, packets)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProver_Prepare_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Prepare'
type MockProver_Prepare_Call struct {
	*mock.Call
}

// Prepare is a helper method to define mock.On call
//   - ctx context.Context
//   - height uint64
//   - kind v2.ProofKind
//   - packets []types.Packet
func (_e *MockProver_Expecter) Prepare(ctx any, height any, kind any, packets any) *MockProver_Prepare_Call {
	return &MockProver_Prepare_Call{Call: _e.mock.On("Prepare", ctx, height, kind, packets)}
}

func (_c *MockProver_Prepare_Call) Run(run func(ctx context.Context, height uint64, kind v2.ProofKind, packets []types.Packet)) *MockProver_Prepare_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 v2.ProofKind
		if args[2] != nil {
			arg2 = args[2].(v2.ProofKind)
		}
		var arg3 []types.Packet
		if args[3] != nil {
			arg3 = args[3].([]types.Packet)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockProver_Prepare_Call) Return(preparation *v2.Preparation, err error) *MockProver_Prepare_Call {
	_c.Call.Return(preparation, err)
	return _c
}

func (_c *MockProver_Prepare_Call) RunAndReturn(run func(ctx context.Context, height uint64, kind v2.ProofKind, packets []types.Packet) (*v2.Preparation, error)) *MockProver_Prepare_Call {
	_c.Call.Return(run)
	return _c
}
