// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package txmgr

import (
	"context"
	mock "github.com/stretchr/testify/mock"
	"time"
)

// NewMockSubmitter creates a new instance of MockSubmitter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSubmitter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSubmitter {
	mock := &MockSubmitter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSubmitter is an autogenerated mock type for the Submitter type
type MockSubmitter struct {
	mock.Mock
}

type MockSubmitter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSubmitter) EXPECT() *MockSubmitter_Expecter {
	return &MockSubmitter_Expecter{mock: &_m.Mock}
}

// ShouldRetry provides a mock function for the type MockSubmitter
func (_mock *MockSubmitter) ShouldRetry(ctx context.Context, txHash string, expiry time.Duration, sentAt time.Time) (bool, error) {
	ret := _mock.Called(ctx, txHash, expiry, sentAt)

	if len(ret) == 0 {
		panic("no return value specified for ShouldRetry")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Duration, time.Time) (bool, error)); ok {
		return returnFunc(ctx, txHash, expiry, sentAt)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Duration, time.Time) bool); ok {
		r0 = returnFunc(ctx, txHash, expiry, sentAt)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, time.Duration, time.Time) error); ok {
		r1 = returnFunc(ctx, txHash, expiry, sentAt)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSubmitter_ShouldRetry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShouldRetry'
type MockSubmitter_ShouldRetry_Call struct {
	*mock.Call
}

// ShouldRetry is a helper method to define mock.On call
//   - ctx context.Context
//   - txHash string
//   - expiry time.Duration
//   - sentAt time.Time
func (_e *MockSubmitter_Expecter) ShouldRetry(ctx any, txHash any, expiry any, sentAt any) *MockSubmitter_ShouldRetry_Call {
	return &MockSubmitter_ShouldRetry_Call{Call: _e.mock.On("ShouldRetry", ctx, txHash, expiry, sentAt)}
}

func (_c *MockSubmitter_ShouldRetry_Call) Run(run func(ctx context.Context, txHash string, expiry time.Duration, sentAt time.Time)) *MockSubmitter_ShouldRetry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockSubmitter_ShouldRetry_Call) Return(b bool, err error) *MockSubmitter_ShouldRetry_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockSubmitter_ShouldRetry_Call) RunAndReturn(run func(ctx context.Context, txHash string, expiry time.Duration, sentAt time.Time) (bool, error)) *MockSubmitter_ShouldRetry_Call {
	_c.Call.Return(run)
	return _c
}

// Submit provides a mock function for the type MockSubmitter
func (_mock *MockSubmitter) Submit(ctx context.Context, intent TxIntent) (*Submission, error) {
	ret := _mock.Called(ctx, intent)

	if len(ret) == 0 {
		panic("no return value specified for Submit")
	}

	var r0 *Submission
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, TxIntent) (*Submission, error)); ok {
		return returnFunc(ctx, intent)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, TxIntent) *Submission); ok {
		r0 = returnFunc(ctx, intent)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Submission)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, TxIntent) error); ok {
		r1 = returnFunc(ctx, intent)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSubmitter_Submit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Submit'
type MockSubmitter_Submit_Call struct {
	*mock.Call
}

// Submit is a helper method to define mock.On call
//   - ctx context.Context
//   - intent TxIntent
func (_e *MockSubmitter_Expecter) Submit(ctx any, intent any) *MockSubmitter_Submit_Call {
	return &MockSubmitter_Submit_Call{Call: _e.mock.On("Submit", ctx, intent)}
}

func (_c *MockSubmitter_Submit_Call) Run(run func(ctx context.Context, intent TxIntent)) *MockSubmitter_Submit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 TxIntent
		if args[1] != nil {
			arg1 = args[1].(TxIntent)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSubmitter_Submit_Call) Return(submission *Submission, err error) *MockSubmitter_Submit_Call {
	_c.Call.Return(submission, err)
	return _c
}

func (_c *MockSubmitter_Submit_Call) RunAndReturn(run func(ctx context.Context, intent TxIntent) (*Submission, error)) *MockSubmitter_Submit_Call {
	_c.Call.Return(run)
	return _c
}
