// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: prover.proto

package prover

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProofKind int32

const (
	ProofKind_PROOF_KIND_UNSPECIFIED       ProofKind = 0
	ProofKind_PROOF_KIND_PACKET_COMMITMENT ProofKind = 1
	ProofKind_PROOF_KIND_ACKNOWLEDGEMENT   ProofKind = 2
	ProofKind_PROOF_KIND_RECEIPT_ABSENCE   ProofKind = 3
)

// Enum value maps for ProofKind.
var (
	ProofKind_name = map[int32]string{
		0: "PROOF_KIND_UNSPECIFIED",
		1: "PROOF_KIND_PACKET_COMMITMENT",
		2: "PROOF_KIND_ACKNOWLEDGEMENT",
		3: "PROOF_KIND_RECEIPT_ABSENCE",
	}
	ProofKind_value = map[string]int32{
		"PROOF_KIND_UNSPECIFIED":       0,
		"PROOF_KIND_PACKET_COMMITMENT": 1,
		"PROOF_KIND_ACKNOWLEDGEMENT":   2,
		"PROOF_KIND_RECEIPT_ABSENCE":   3,
	}
)

func (x ProofKind) Enum() *ProofKind {
	p := new(ProofKind)
	*p = x
	return p
}

func (x ProofKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProofKind) Descriptor() protoreflect.EnumDescriptor {
	return file_prover_proto_enumTypes[0].Descriptor()
}

func (ProofKind) Type() protoreflect.EnumType {
	return &file_prover_proto_enumTypes[0]
}

func (x ProofKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProofKind.Descriptor instead.
func (ProofKind) EnumDescriptor() ([]byte, []int) {
	return file_prover_proto_rawDescGZIP(), []int{0}
}

// Client identifies one configured light client: the chain it lives on and its
// client id.
type Client struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChainId       string                 `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	ClientId      string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Client) Reset() {
	*x = Client{}
	mi := &file_prover_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Client) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Client) ProtoMessage() {}

func (x *Client) ProtoReflect() protoreflect.Message {
	mi := &file_prover_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Client.ProtoReflect.Descriptor instead.
func (*Client) Descriptor() ([]byte, []int) {
	return file_prover_proto_rawDescGZIP(), []int{0}
}

func (x *Client) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

func (x *Client) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type LatestProvableHeightRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Client        *Client                `protobuf:"bytes,1,opt,name=client,proto3" json:"client,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LatestProvableHeightRequest) Reset() {
	*x = LatestProvableHeightRequest{}
	mi := &file_prover_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LatestProvableHeightRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LatestProvableHeightRequest) ProtoMessage() {}

func (x *LatestProvableHeightRequest) ProtoReflect() protoreflect.Message {
	mi := &file_prover_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LatestProvableHeightRequest.ProtoReflect.Descriptor instead.
func (*LatestProvableHeightRequest) Descriptor() ([]byte, []int) {
	return file_prover_proto_rawDescGZIP(), []int{1}
}

func (x *LatestProvableHeightRequest) GetClient() *Client {
	if x != nil {
		return x.Client
	}
	return nil
}

type LatestProvableHeightResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Height uint64                 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	// counterparty-chain timestamp of height, in seconds.
	Timestamp     uint64 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LatestProvableHeightResponse) Reset() {
	*x = LatestProvableHeightResponse{}
	mi := &file_prover_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LatestProvableHeightResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LatestProvableHeightResponse) ProtoMessage() {}

func (x *LatestProvableHeightResponse) ProtoReflect() protoreflect.Message {
	mi := &file_prover_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LatestProvableHeightResponse.ProtoReflect.Descriptor instead.
func (*LatestProvableHeightResponse) Descriptor() ([]byte, []int) {
	return file_prover_proto_rawDescGZIP(), []int{2}
}

func (x *LatestProvableHeightResponse) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *LatestProvableHeightResponse) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type StateProofRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Client        *Client                `protobuf:"bytes,1,opt,name=client,proto3" json:"client,omitempty"`
	Height        uint64                 `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateProofRequest) Reset() {
	*x = StateProofRequest{}
	mi := &file_prover_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateProofRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateProofRequest) ProtoMessage() {}

func (x *StateProofRequest) ProtoReflect() protoreflect.Message {
	mi := &file_prover_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateProofRequest.ProtoReflect.Descriptor instead.
func (*StateProofRequest) Descriptor() ([]byte, []int) {
	return file_prover_proto_rawDescGZIP(), []int{3}
}

func (x *StateProofRequest) GetClient() *Client {
	if x != nil {
		return x.Client
	}
	return nil
}

func (x *StateProofRequest) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

type StateProofResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Proof         []byte                 `protobuf:"bytes,1,opt,name=proof,proto3" json:"proof,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateProofResponse) Reset() {
	*x = StateProofResponse{}
	mi := &file_prover_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateProofResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateProofResponse) ProtoMessage() {}

func (x *StateProofResponse) ProtoReflect() protoreflect.Message {
	mi := &file_prover_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateProofResponse.ProtoReflect.Descriptor instead.
func (*StateProofResponse) Descriptor() ([]byte, []int) {
	return file_prover_proto_rawDescGZIP(), []int{4}
}

func (x *StateProofResponse) GetProof() []byte {
	if x != nil {
		return x.Proof
	}
	return nil
}

type PacketProofsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Client        *Client                `protobuf:"bytes,1,opt,name=client,proto3" json:"client,omitempty"`
	Height        uint64                 `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	Kind          ProofKind              `protobuf:"varint,3,opt,name=kind,proto3,enum=ibc.v2.prover.ProofKind" json:"kind,omitempty"`
	Packets       []*Packet              `protobuf:"bytes,4,rep,name=packets,proto3" json:"packets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PacketProofsRequest) Reset() {
	*x = PacketProofsRequest{}
	mi := &file_prover_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PacketProofsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PacketProofsRequest) ProtoMessage() {}

func (x *PacketProofsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_prover_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PacketProofsRequest.ProtoReflect.Descriptor instead.
func (*PacketProofsRequest) Descriptor() ([]byte, []int) {
	return file_prover_proto_rawDescGZIP(), []int{5}
}

func (x *PacketProofsRequest) GetClient() *Client {
	if x != nil {
		return x.Client
	}
	return nil
}

func (x *PacketProofsRequest) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *PacketProofsRequest) GetKind() ProofKind {
	if x != nil {
		return x.Kind
	}
	return ProofKind_PROOF_KIND_UNSPECIFIED
}

func (x *PacketProofsRequest) GetPackets() []*Packet {
	if x != nil {
		return x.Packets
	}
	return nil
}

type PacketProofsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// One proof per requested packet, in request order.
	Proofs        [][]byte `protobuf:"bytes,1,rep,name=proofs,proto3" json:"proofs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PacketProofsResponse) Reset() {
	*x = PacketProofsResponse{}
	mi := &file_prover_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PacketProofsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PacketProofsResponse) ProtoMessage() {}

func (x *PacketProofsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_prover_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PacketProofsResponse.ProtoReflect.Descriptor instead.
func (*PacketProofsResponse) Descriptor() ([]byte, []int) {
	return file_prover_proto_rawDescGZIP(), []int{6}
}

func (x *PacketProofsResponse) GetProofs() [][]byte {
	if x != nil {
		return x.Proofs
	}
	return nil
}

// Packet mirrors the IBC v2 packet the proof is generated for.
type Packet struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Sequence          uint64                 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	SourceClient      string                 `protobuf:"bytes,2,opt,name=source_client,json=sourceClient,proto3" json:"source_client,omitempty"`
	DestinationClient string                 `protobuf:"bytes,3,opt,name=destination_client,json=destinationClient,proto3" json:"destination_client,omitempty"`
	TimeoutTimestamp  uint64                 `protobuf:"varint,4,opt,name=timeout_timestamp,json=timeoutTimestamp,proto3" json:"timeout_timestamp,omitempty"`
	Payloads          []*Payload             `protobuf:"bytes,5,rep,name=payloads,proto3" json:"payloads,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Packet) Reset() {
	*x = Packet{}
	mi := &file_prover_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Packet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Packet) ProtoMessage() {}

func (x *Packet) ProtoReflect() protoreflect.Message {
	mi := &file_prover_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Packet.ProtoReflect.Descriptor instead.
func (*Packet) Descriptor() ([]byte, []int) {
	return file_prover_proto_rawDescGZIP(), []int{7}
}

func (x *Packet) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *Packet) GetSourceClient() string {
	if x != nil {
		return x.SourceClient
	}
	return ""
}

func (x *Packet) GetDestinationClient() string {
	if x != nil {
		return x.DestinationClient
	}
	return ""
}

func (x *Packet) GetTimeoutTimestamp() uint64 {
	if x != nil {
		return x.TimeoutTimestamp
	}
	return 0
}

func (x *Packet) GetPayloads() []*Payload {
	if x != nil {
		return x.Payloads
	}
	return nil
}

type Payload struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SourcePort      string                 `protobuf:"bytes,1,opt,name=source_port,json=sourcePort,proto3" json:"source_port,omitempty"`
	DestinationPort string                 `protobuf:"bytes,2,opt,name=destination_port,json=destinationPort,proto3" json:"destination_port,omitempty"`
	Version         string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Encoding        string                 `protobuf:"bytes,4,opt,name=encoding,proto3" json:"encoding,omitempty"`
	Value           []byte                 `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Payload) Reset() {
	*x = Payload{}
	mi := &file_prover_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payload) ProtoMessage() {}

func (x *Payload) ProtoReflect() protoreflect.Message {
	mi := &file_prover_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payload.ProtoReflect.Descriptor instead.
func (*Payload) Descriptor() ([]byte, []int) {
	return file_prover_proto_rawDescGZIP(), []int{8}
}

func (x *Payload) GetSourcePort() string {
	if x != nil {
		return x.SourcePort
	}
	return ""
}

func (x *Payload) GetDestinationPort() string {
	if x != nil {
		return x.DestinationPort
	}
	return ""
}

func (x *Payload) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Payload) GetEncoding() string {
	if x != nil {
		return x.Encoding
	}
	return ""
}

func (x *Payload) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

var File_prover_proto protoreflect.FileDescriptor

const file_prover_proto_rawDesc = "" +
	"\n" +
	"\fprover.proto\x12\ribc.v2.prover\"@\n" +
	"\x06Client\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\tR\achainId\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\"L\n" +
	"\x1bLatestProvableHeightRequest\x12-\n" +
	"\x06client\x18\x01 \x01(\v2\x15.ibc.v2.prover.ClientR\x06client\"T\n" +
	"\x1cLatestProvableHeightResponse\x12\x16\n" +
	"\x06height\x18\x01 \x01(\x04R\x06height\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x04R\ttimestamp\"Z\n" +
	"\x11StateProofRequest\x12-\n" +
	"\x06client\x18\x01 \x01(\v2\x15.ibc.v2.prover.ClientR\x06client\x12\x16\n" +
	"\x06height\x18\x02 \x01(\x04R\x06height\"*\n" +
	"\x12StateProofResponse\x12\x14\n" +
	"\x05proof\x18\x01 \x01(\fR\x05proof\"\xbb\x01\n" +
	"\x13PacketProofsRequest\x12-\n" +
	"\x06client\x18\x01 \x01(\v2\x15.ibc.v2.prover.ClientR\x06client\x12\x16\n" +
	"\x06height\x18\x02 \x01(\x04R\x06height\x12,\n" +
	"\x04kind\x18\x03 \x01(\x0e2\x18.ibc.v2.prover.ProofKindR\x04kind\x12/\n" +
	"\apackets\x18\x04 \x03(\v2\x15.ibc.v2.prover.PacketR\apackets\".\n" +
	"\x14PacketProofsResponse\x12\x16\n" +
	"\x06proofs\x18\x01 \x03(\fR\x06proofs\"\xd9\x01\n" +
	"\x06Packet\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x04R\bsequence\x12#\n" +
	"\rsource_client\x18\x02 \x01(\tR\fsourceClient\x12-\n" +
	"\x12destination_client\x18\x03 \x01(\tR\x11destinationClient\x12+\n" +
	"\x11timeout_timestamp\x18\x04 \x01(\x04R\x10timeoutTimestamp\x122\n" +
	"\bpayloads\x18\x05 \x03(\v2\x16.ibc.v2.prover.PayloadR\bpayloads\"\xa1\x01\n" +
	"\aPayload\x12\x1f\n" +
	"\vsource_port\x18\x01 \x01(\tR\n" +
	"sourcePort\x12)\n" +
	"\x10destination_port\x18\x02 \x01(\tR\x0fdestinationPort\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x1a\n" +
	"\bencoding\x18\x04 \x01(\tR\bencoding\x12\x14\n" +
	"\x05value\x18\x05 \x01(\fR\x05value*\x89\x01\n" +
	"\tProofKind\x12\x1a\n" +
	"\x16PROOF_KIND_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cPROOF_KIND_PACKET_COMMITMENT\x10\x01\x12\x1e\n" +
	"\x1aPROOF_KIND_ACKNOWLEDGEMENT\x10\x02\x12\x1e\n" +
	"\x1aPROOF_KIND_RECEIPT_ABSENCE\x10\x032\xb2\x02\n" +
	"\rProverService\x12q\n" +
	"\x14LatestProvableHeight\x12*.ibc.v2.prover.LatestProvableHeightRequest\x1a+.ibc.v2.prover.LatestProvableHeightResponse\"\x00\x12S\n" +
	"\n" +
	"StateProof\x12 .ibc.v2.prover.StateProofRequest\x1a!.ibc.v2.prover.StateProofResponse\"\x00\x12Y\n" +
	"\fPacketProofs\x12\".ibc.v2.prover.PacketProofsRequest\x1a#.ibc.v2.prover.PacketProofsResponse\"\x00B*Z(github.com/cosmos/ibc/link/api/v2/proverb\x06proto3"

var (
	file_prover_proto_rawDescOnce sync.Once
	file_prover_proto_rawDescData []byte
)

func file_prover_proto_rawDescGZIP() []byte {
	file_prover_proto_rawDescOnce.Do(func() {
		file_prover_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_prover_proto_rawDesc), len(file_prover_proto_rawDesc)))
	})
	return file_prover_proto_rawDescData
}

var file_prover_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_prover_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_prover_proto_goTypes = []any{
	(ProofKind)(0),                       // 0: ibc.v2.prover.ProofKind
	(*Client)(nil),                       // 1: ibc.v2.prover.Client
	(*LatestProvableHeightRequest)(nil),  // 2: ibc.v2.prover.LatestProvableHeightRequest
	(*LatestProvableHeightResponse)(nil), // 3: ibc.v2.prover.LatestProvableHeightResponse
	(*StateProofRequest)(nil),            // 4: ibc.v2.prover.StateProofRequest
	(*StateProofResponse)(nil),           // 5: ibc.v2.prover.StateProofResponse
	(*PacketProofsRequest)(nil),          // 6: ibc.v2.prover.PacketProofsRequest
	(*PacketProofsResponse)(nil),         // 7: ibc.v2.prover.PacketProofsResponse
	(*Packet)(nil),                       // 8: ibc.v2.prover.Packet
	(*Payload)(nil),                      // 9: ibc.v2.prover.Payload
}
var file_prover_proto_depIdxs = []int32{
	1, // 0: ibc.v2.prover.LatestProvableHeightRequest.client:type_name -> ibc.v2.prover.Client
	1, // 1: ibc.v2.prover.StateProofRequest.client:type_name -> ibc.v2.prover.Client
	1, // 2: ibc.v2.prover.PacketProofsRequest.client:type_name -> ibc.v2.prover.Client
	0, // 3: ibc.v2.prover.PacketProofsRequest.kind:type_name -> ibc.v2.prover.ProofKind
	8, // 4: ibc.v2.prover.PacketProofsRequest.packets:type_name -> ibc.v2.prover.Packet
	9, // 5: ibc.v2.prover.Packet.payloads:type_name -> ibc.v2.prover.Payload
	2, // 6: ibc.v2.prover.ProverService.LatestProvableHeight:input_type -> ibc.v2.prover.LatestProvableHeightRequest
	4, // 7: ibc.v2.prover.ProverService.StateProof:input_type -> ibc.v2.prover.StateProofRequest
	6, // 8: ibc.v2.prover.ProverService.PacketProofs:input_type -> ibc.v2.prover.PacketProofsRequest
	3, // 9: ibc.v2.prover.ProverService.LatestProvableHeight:output_type -> ibc.v2.prover.LatestProvableHeightResponse
	5, // 10: ibc.v2.prover.ProverService.StateProof:output_type -> ibc.v2.prover.StateProofResponse
	7, // 11: ibc.v2.prover.ProverService.PacketProofs:output_type -> ibc.v2.prover.PacketProofsResponse
	9, // [9:12] is the sub-list for method output_type
	6, // [6:9] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_prover_proto_init() }
func file_prover_proto_init() {
	if File_prover_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_prover_proto_rawDesc), len(file_prover_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_prover_proto_goTypes,
		DependencyIndexes: file_prover_proto_depIdxs,
		EnumInfos:         file_prover_proto_enumTypes,
		MessageInfos:      file_prover_proto_msgTypes,
	}.Build()
	File_prover_proto = out.File
	file_prover_proto_goTypes = nil
	file_prover_proto_depIdxs = nil
}
