// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: attestor.proto

package attestor

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AttestationServiceName is the fully-qualified name of the AttestationService service.
	AttestationServiceName = "ibc.attestor.AttestationService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AttestationServiceLatestAttestableHeightProcedure is the fully-qualified name of the
	// AttestationService's LatestAttestableHeight RPC.
	AttestationServiceLatestAttestableHeightProcedure = "/ibc.attestor.AttestationService/LatestAttestableHeight"
)

// AttestationServiceClient is a client for the ibc.attestor.AttestationService service.
type AttestationServiceClient interface {
	// Returns the latest height the attestor will generate attestations for.
	LatestAttestableHeight(context.Context, *connect.Request[LatestAttestableHeightRequest]) (*connect.Response[LatestAttestableHeightResponse], error)
}

// NewAttestationServiceClient constructs a client for the ibc.attestor.AttestationService service.
// By default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped
// responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAttestationServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AttestationServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	attestationServiceMethods := File_attestor_proto.Services().ByName("AttestationService").Methods()
	return &attestationServiceClient{
		latestAttestableHeight: connect.NewClient[LatestAttestableHeightRequest, LatestAttestableHeightResponse](
			httpClient,
			baseURL+AttestationServiceLatestAttestableHeightProcedure,
			connect.WithSchema(attestationServiceMethods.ByName("LatestAttestableHeight")),
			connect.WithClientOptions(opts...),
		),
	}
}

// attestationServiceClient implements AttestationServiceClient.
type attestationServiceClient struct {
	latestAttestableHeight *connect.Client[LatestAttestableHeightRequest, LatestAttestableHeightResponse]
}

// LatestAttestableHeight calls ibc.attestor.AttestationService.LatestAttestableHeight.
func (c *attestationServiceClient) LatestAttestableHeight(ctx context.Context, req *connect.Request[LatestAttestableHeightRequest]) (*connect.Response[LatestAttestableHeightResponse], error) {
	return c.latestAttestableHeight.CallUnary(ctx, req)
}

// AttestationServiceHandler is an implementation of the ibc.attestor.AttestationService service.
type AttestationServiceHandler interface {
	// Returns the latest height the attestor will generate attestations for.
	LatestAttestableHeight(context.Context, *connect.Request[LatestAttestableHeightRequest]) (*connect.Response[LatestAttestableHeightResponse], error)
}

// NewAttestationServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAttestationServiceHandler(svc AttestationServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	attestationServiceMethods := File_attestor_proto.Services().ByName("AttestationService").Methods()
	attestationServiceLatestAttestableHeightHandler := connect.NewUnaryHandler(
		AttestationServiceLatestAttestableHeightProcedure,
		svc.LatestAttestableHeight,
		connect.WithSchema(attestationServiceMethods.ByName("LatestAttestableHeight")),
		connect.WithHandlerOptions(opts...),
	)
	return "/ibc.attestor.AttestationService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AttestationServiceLatestAttestableHeightProcedure:
			attestationServiceLatestAttestableHeightHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAttestationServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAttestationServiceHandler struct{}

func (UnimplementedAttestationServiceHandler) LatestAttestableHeight(context.Context, *connect.Request[LatestAttestableHeightRequest]) (*connect.Response[LatestAttestableHeightResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ibc.attestor.AttestationService.LatestAttestableHeight is not implemented"))
}
