// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: attestor.proto

package attestor

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LatestAttestableHeightRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attestor      string                 `protobuf:"bytes,1,opt,name=attestor,proto3" json:"attestor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LatestAttestableHeightRequest) Reset() {
	*x = LatestAttestableHeightRequest{}
	mi := &file_attestor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LatestAttestableHeightRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LatestAttestableHeightRequest) ProtoMessage() {}

func (x *LatestAttestableHeightRequest) ProtoReflect() protoreflect.Message {
	mi := &file_attestor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LatestAttestableHeightRequest.ProtoReflect.Descriptor instead.
func (*LatestAttestableHeightRequest) Descriptor() ([]byte, []int) {
	return file_attestor_proto_rawDescGZIP(), []int{0}
}

func (x *LatestAttestableHeightRequest) GetAttestor() string {
	if x != nil {
		return x.Attestor
	}
	return ""
}

type LatestAttestableHeightResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Height        uint64                 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LatestAttestableHeightResponse) Reset() {
	*x = LatestAttestableHeightResponse{}
	mi := &file_attestor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LatestAttestableHeightResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LatestAttestableHeightResponse) ProtoMessage() {}

func (x *LatestAttestableHeightResponse) ProtoReflect() protoreflect.Message {
	mi := &file_attestor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LatestAttestableHeightResponse.ProtoReflect.Descriptor instead.
func (*LatestAttestableHeightResponse) Descriptor() ([]byte, []int) {
	return file_attestor_proto_rawDescGZIP(), []int{1}
}

func (x *LatestAttestableHeightResponse) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

var File_attestor_proto protoreflect.FileDescriptor

const file_attestor_proto_rawDesc = "" +
	"\n" +
	"\x0eattestor.proto\x12\fibc.attestor\";\n" +
	"\x1dLatestAttestableHeightRequest\x12\x1a\n" +
	"\battestor\x18\x01 \x01(\tR\battestor\"8\n" +
	"\x1eLatestAttestableHeightResponse\x12\x16\n" +
	"\x06height\x18\x01 \x01(\x04R\x06height2\x89\x01\n" +
	"\x12AttestationService\x12s\n" +
	"\x16LatestAttestableHeight\x12+.ibc.attestor.LatestAttestableHeightRequest\x1a,.ibc.attestor.LatestAttestableHeightResponseB4Z2github.com/cosmos/ibc/link/internal/types/attestorb\x06proto3"

var (
	file_attestor_proto_rawDescOnce sync.Once
	file_attestor_proto_rawDescData []byte
)

func file_attestor_proto_rawDescGZIP() []byte {
	file_attestor_proto_rawDescOnce.Do(func() {
		file_attestor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_attestor_proto_rawDesc), len(file_attestor_proto_rawDesc)))
	})
	return file_attestor_proto_rawDescData
}

var file_attestor_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_attestor_proto_goTypes = []any{
	(*LatestAttestableHeightRequest)(nil),  // 0: ibc.attestor.LatestAttestableHeightRequest
	(*LatestAttestableHeightResponse)(nil), // 1: ibc.attestor.LatestAttestableHeightResponse
}
var file_attestor_proto_depIdxs = []int32{
	0, // 0: ibc.attestor.AttestationService.LatestAttestableHeight:input_type -> ibc.attestor.LatestAttestableHeightRequest
	1, // 1: ibc.attestor.AttestationService.LatestAttestableHeight:output_type -> ibc.attestor.LatestAttestableHeightResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_attestor_proto_init() }
func file_attestor_proto_init() {
	if File_attestor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_attestor_proto_rawDesc), len(file_attestor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_attestor_proto_goTypes,
		DependencyIndexes: file_attestor_proto_depIdxs,
		MessageInfos:      file_attestor_proto_msgTypes,
	}.Build()
	File_attestor_proto = out.File
	file_attestor_proto_goTypes = nil
	file_attestor_proto_depIdxs = nil
}
