// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package proofapi

import (
	"context"

	"connectrpc.com/connect"
	mock "github.com/stretchr/testify/mock"
)

// NewMockProofApiServiceClient creates a new instance of MockProofApiServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProofApiServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProofApiServiceClient {
	mock := &MockProofApiServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProofApiServiceClient is an autogenerated mock type for the ProofApiServiceClient type
type MockProofApiServiceClient struct {
	mock.Mock
}

type MockProofApiServiceClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProofApiServiceClient) EXPECT() *MockProofApiServiceClient_Expecter {
	return &MockProofApiServiceClient_Expecter{mock: &_m.Mock}
}

// CreateClient provides a mock function for the type MockProofApiServiceClient
func (_mock *MockProofApiServiceClient) CreateClient(context1 context.Context, request *connect.Request[CreateClientRequest]) (*connect.Response[CreateClientResponse], error) {
	ret := _mock.Called(context1, request)

	if len(ret) == 0 {
		panic("no return value specified for CreateClient")
	}

	var r0 *connect.Response[CreateClientResponse]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *connect.Request[CreateClientRequest]) (*connect.Response[CreateClientResponse], error)); ok {
		return returnFunc(context1, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *connect.Request[CreateClientRequest]) *connect.Response[CreateClientResponse]); ok {
		r0 = returnFunc(context1, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*connect.Response[CreateClientResponse])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *connect.Request[CreateClientRequest]) error); ok {
		r1 = returnFunc(context1, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProofApiServiceClient_CreateClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateClient'
type MockProofApiServiceClient_CreateClient_Call struct {
	*mock.Call
}

// CreateClient is a helper method to define mock.On call
//   - context1 context.Context
//   - request *connect.Request[CreateClientRequest]
func (_e *MockProofApiServiceClient_Expecter) CreateClient(context1 any, request any) *MockProofApiServiceClient_CreateClient_Call {
	return &MockProofApiServiceClient_CreateClient_Call{Call: _e.mock.On("CreateClient", context1, request)}
}

func (_c *MockProofApiServiceClient_CreateClient_Call) Run(run func(context1 context.Context, request *connect.Request[CreateClientRequest])) *MockProofApiServiceClient_CreateClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *connect.Request[CreateClientRequest]
		if args[1] != nil {
			arg1 = args[1].(*connect.Request[CreateClientRequest])
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProofApiServiceClient_CreateClient_Call) Return(response *connect.Response[CreateClientResponse], err error) *MockProofApiServiceClient_CreateClient_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockProofApiServiceClient_CreateClient_Call) RunAndReturn(run func(context1 context.Context, request *connect.Request[CreateClientRequest]) (*connect.Response[CreateClientResponse], error)) *MockProofApiServiceClient_CreateClient_Call {
	_c.Call.Return(run)
	return _c
}

// Info provides a mock function for the type MockProofApiServiceClient
func (_mock *MockProofApiServiceClient) Info(context1 context.Context, request *connect.Request[InfoRequest]) (*connect.Response[InfoResponse], error) {
	ret := _mock.Called(context1, request)

	if len(ret) == 0 {
		panic("no return value specified for Info")
	}

	var r0 *connect.Response[InfoResponse]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *connect.Request[InfoRequest]) (*connect.Response[InfoResponse], error)); ok {
		return returnFunc(context1, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *connect.Request[InfoRequest]) *connect.Response[InfoResponse]); ok {
		r0 = returnFunc(context1, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*connect.Response[InfoResponse])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *connect.Request[InfoRequest]) error); ok {
		r1 = returnFunc(context1, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProofApiServiceClient_Info_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Info'
type MockProofApiServiceClient_Info_Call struct {
	*mock.Call
}

// Info is a helper method to define mock.On call
//   - context1 context.Context
//   - request *connect.Request[InfoRequest]
func (_e *MockProofApiServiceClient_Expecter) Info(context1 any, request any) *MockProofApiServiceClient_Info_Call {
	return &MockProofApiServiceClient_Info_Call{Call: _e.mock.On("Info", context1, request)}
}

func (_c *MockProofApiServiceClient_Info_Call) Run(run func(context1 context.Context, request *connect.Request[InfoRequest])) *MockProofApiServiceClient_Info_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *connect.Request[InfoRequest]
		if args[1] != nil {
			arg1 = args[1].(*connect.Request[InfoRequest])
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProofApiServiceClient_Info_Call) Return(response *connect.Response[InfoResponse], err error) *MockProofApiServiceClient_Info_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockProofApiServiceClient_Info_Call) RunAndReturn(run func(context1 context.Context, request *connect.Request[InfoRequest]) (*connect.Response[InfoResponse], error)) *MockProofApiServiceClient_Info_Call {
	_c.Call.Return(run)
	return _c
}

// RelayByTx provides a mock function for the type MockProofApiServiceClient
func (_mock *MockProofApiServiceClient) RelayByTx(context1 context.Context, request *connect.Request[RelayByTxRequest]) (*connect.Response[RelayByTxResponse], error) {
	ret := _mock.Called(context1, request)

	if len(ret) == 0 {
		panic("no return value specified for RelayByTx")
	}

	var r0 *connect.Response[RelayByTxResponse]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *connect.Request[RelayByTxRequest]) (*connect.Response[RelayByTxResponse], error)); ok {
		return returnFunc(context1, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *connect.Request[RelayByTxRequest]) *connect.Response[RelayByTxResponse]); ok {
		r0 = returnFunc(context1, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*connect.Response[RelayByTxResponse])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *connect.Request[RelayByTxRequest]) error); ok {
		r1 = returnFunc(context1, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProofApiServiceClient_RelayByTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RelayByTx'
type MockProofApiServiceClient_RelayByTx_Call struct {
	*mock.Call
}

// RelayByTx is a helper method to define mock.On call
//   - context1 context.Context
//   - request *connect.Request[RelayByTxRequest]
func (_e *MockProofApiServiceClient_Expecter) RelayByTx(context1 any, request any) *MockProofApiServiceClient_RelayByTx_Call {
	return &MockProofApiServiceClient_RelayByTx_Call{Call: _e.mock.On("RelayByTx", context1, request)}
}

func (_c *MockProofApiServiceClient_RelayByTx_Call) Run(run func(context1 context.Context, request *connect.Request[RelayByTxRequest])) *MockProofApiServiceClient_RelayByTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *connect.Request[RelayByTxRequest]
		if args[1] != nil {
			arg1 = args[1].(*connect.Request[RelayByTxRequest])
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProofApiServiceClient_RelayByTx_Call) Return(response *connect.Response[RelayByTxResponse], err error) *MockProofApiServiceClient_RelayByTx_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockProofApiServiceClient_RelayByTx_Call) RunAndReturn(run func(context1 context.Context, request *connect.Request[RelayByTxRequest]) (*connect.Response[RelayByTxResponse], error)) *MockProofApiServiceClient_RelayByTx_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateClient provides a mock function for the type MockProofApiServiceClient
func (_mock *MockProofApiServiceClient) UpdateClient(context1 context.Context, request *connect.Request[UpdateClientRequest]) (*connect.Response[UpdateClientResponse], error) {
	ret := _mock.Called(context1, request)

	if len(ret) == 0 {
		panic("no return value specified for UpdateClient")
	}

	var r0 *connect.Response[UpdateClientResponse]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *connect.Request[UpdateClientRequest]) (*connect.Response[UpdateClientResponse], error)); ok {
		return returnFunc(context1, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *connect.Request[UpdateClientRequest]) *connect.Response[UpdateClientResponse]); ok {
		r0 = returnFunc(context1, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*connect.Response[UpdateClientResponse])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *connect.Request[UpdateClientRequest]) error); ok {
		r1 = returnFunc(context1, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProofApiServiceClient_UpdateClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateClient'
type MockProofApiServiceClient_UpdateClient_Call struct {
	*mock.Call
}

// UpdateClient is a helper method to define mock.On call
//   - context1 context.Context
//   - request *connect.Request[UpdateClientRequest]
func (_e *MockProofApiServiceClient_Expecter) UpdateClient(context1 any, request any) *MockProofApiServiceClient_UpdateClient_Call {
	return &MockProofApiServiceClient_UpdateClient_Call{Call: _e.mock.On("UpdateClient", context1, request)}
}

func (_c *MockProofApiServiceClient_UpdateClient_Call) Run(run func(context1 context.Context, request *connect.Request[UpdateClientRequest])) *MockProofApiServiceClient_UpdateClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *connect.Request[UpdateClientRequest]
		if args[1] != nil {
			arg1 = args[1].(*connect.Request[UpdateClientRequest])
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProofApiServiceClient_UpdateClient_Call) Return(response *connect.Response[UpdateClientResponse], err error) *MockProofApiServiceClient_UpdateClient_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockProofApiServiceClient_UpdateClient_Call) RunAndReturn(run func(context1 context.Context, request *connect.Request[UpdateClientRequest]) (*connect.Response[UpdateClientResponse], error)) *MockProofApiServiceClient_UpdateClient_Call {
	_c.Call.Return(run)
	return _c
}
