// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proofapi.proto

package proofapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The relay by tx request message
type RelayByTxRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The source chain identifier
	SrcChain string `protobuf:"bytes,1,opt,name=src_chain,json=srcChain,proto3" json:"src_chain,omitempty"`
	// The target chain identifier
	DstChain string `protobuf:"bytes,2,opt,name=dst_chain,json=dstChain,proto3" json:"dst_chain,omitempty"`
	// The identifiers for the IBC transactions to be relayed
	// This is usually the transaction hash
	SourceTxIds [][]byte `protobuf:"bytes,3,rep,name=source_tx_ids,json=sourceTxIds,proto3" json:"source_tx_ids,omitempty"`
	// The identifiers for the IBC transactions on the target chain to be timed out
	TimeoutTxIds [][]byte `protobuf:"bytes,4,rep,name=timeout_tx_ids,json=timeoutTxIds,proto3" json:"timeout_tx_ids,omitempty"`
	// The identifier for the source client
	// Used for event filtering
	SrcClientId string `protobuf:"bytes,5,opt,name=src_client_id,json=srcClientId,proto3" json:"src_client_id,omitempty"`
	// The identifier for the destination client
	// Used for event filtering
	DstClientId string `protobuf:"bytes,6,opt,name=dst_client_id,json=dstClientId,proto3" json:"dst_client_id,omitempty"`
	// The optional source chain send packet sequences for recv packets
	// Used for event filtering, no filtering if empty
	SrcPacketSequences []uint64 `protobuf:"varint,7,rep,packed,name=src_packet_sequences,json=srcPacketSequences,proto3" json:"src_packet_sequences,omitempty"`
	// The optional destination chain send packet sequences for acks and timeouts
	// Used for event filtering, no filtering if empty
	DstPacketSequences []uint64 `protobuf:"varint,8,rep,packed,name=dst_packet_sequences,json=dstPacketSequences,proto3" json:"dst_packet_sequences,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RelayByTxRequest) Reset() {
	*x = RelayByTxRequest{}
	mi := &file_proofapi_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayByTxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayByTxRequest) ProtoMessage() {}

func (x *RelayByTxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proofapi_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayByTxRequest.ProtoReflect.Descriptor instead.
func (*RelayByTxRequest) Descriptor() ([]byte, []int) {
	return file_proofapi_proto_rawDescGZIP(), []int{0}
}

func (x *RelayByTxRequest) GetSrcChain() string {
	if x != nil {
		return x.SrcChain
	}
	return ""
}

func (x *RelayByTxRequest) GetDstChain() string {
	if x != nil {
		return x.DstChain
	}
	return ""
}

func (x *RelayByTxRequest) GetSourceTxIds() [][]byte {
	if x != nil {
		return x.SourceTxIds
	}
	return nil
}

func (x *RelayByTxRequest) GetTimeoutTxIds() [][]byte {
	if x != nil {
		return x.TimeoutTxIds
	}
	return nil
}

func (x *RelayByTxRequest) GetSrcClientId() string {
	if x != nil {
		return x.SrcClientId
	}
	return ""
}

func (x *RelayByTxRequest) GetDstClientId() string {
	if x != nil {
		return x.DstClientId
	}
	return ""
}

func (x *RelayByTxRequest) GetSrcPacketSequences() []uint64 {
	if x != nil {
		return x.SrcPacketSequences
	}
	return nil
}

func (x *RelayByTxRequest) GetDstPacketSequences() []uint64 {
	if x != nil {
		return x.DstPacketSequences
	}
	return nil
}

// The relay by tx response message
type RelayByTxResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The multicall transaction to be submitted by caller
	Tx []byte `protobuf:"bytes,1,opt,name=tx,proto3" json:"tx,omitempty"`
	// The contract address to submit the transaction, if applicable
	Address       string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayByTxResponse) Reset() {
	*x = RelayByTxResponse{}
	mi := &file_proofapi_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayByTxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayByTxResponse) ProtoMessage() {}

func (x *RelayByTxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proofapi_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayByTxResponse.ProtoReflect.Descriptor instead.
func (*RelayByTxResponse) Descriptor() ([]byte, []int) {
	return file_proofapi_proto_rawDescGZIP(), []int{1}
}

func (x *RelayByTxResponse) GetTx() []byte {
	if x != nil {
		return x.Tx
	}
	return nil
}

func (x *RelayByTxResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

// The create client request message
type CreateClientRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The source chain identifier
	SrcChain string `protobuf:"bytes,1,opt,name=src_chain,json=srcChain,proto3" json:"src_chain,omitempty"`
	// The target chain identifier
	DstChain string `protobuf:"bytes,2,opt,name=dst_chain,json=dstChain,proto3" json:"dst_chain,omitempty"`
	// Optional genesis parameters
	Parameters    map[string]string `protobuf:"bytes,3,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateClientRequest) Reset() {
	*x = CreateClientRequest{}
	mi := &file_proofapi_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateClientRequest) ProtoMessage() {}

func (x *CreateClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proofapi_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateClientRequest.ProtoReflect.Descriptor instead.
func (*CreateClientRequest) Descriptor() ([]byte, []int) {
	return file_proofapi_proto_rawDescGZIP(), []int{2}
}

func (x *CreateClientRequest) GetSrcChain() string {
	if x != nil {
		return x.SrcChain
	}
	return ""
}

func (x *CreateClientRequest) GetDstChain() string {
	if x != nil {
		return x.DstChain
	}
	return ""
}

func (x *CreateClientRequest) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

// The create client response message
type CreateClientResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The transaction to be submitted by caller
	Tx []byte `protobuf:"bytes,1,opt,name=tx,proto3" json:"tx,omitempty"`
	// The contract address to submit the transaction, if applicable
	Address       string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateClientResponse) Reset() {
	*x = CreateClientResponse{}
	mi := &file_proofapi_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateClientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateClientResponse) ProtoMessage() {}

func (x *CreateClientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proofapi_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateClientResponse.ProtoReflect.Descriptor instead.
func (*CreateClientResponse) Descriptor() ([]byte, []int) {
	return file_proofapi_proto_rawDescGZIP(), []int{3}
}

func (x *CreateClientResponse) GetTx() []byte {
	if x != nil {
		return x.Tx
	}
	return nil
}

func (x *CreateClientResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

// The update client request message
type UpdateClientRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The source chain identifier
	SrcChain string `protobuf:"bytes,1,opt,name=src_chain,json=srcChain,proto3" json:"src_chain,omitempty"`
	// The target chain identifier
	DstChain string `protobuf:"bytes,2,opt,name=dst_chain,json=dstChain,proto3" json:"dst_chain,omitempty"`
	// The identifier for the client on the destination chain
	DstClientId   string `protobuf:"bytes,3,opt,name=dst_client_id,json=dstClientId,proto3" json:"dst_client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateClientRequest) Reset() {
	*x = UpdateClientRequest{}
	mi := &file_proofapi_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateClientRequest) ProtoMessage() {}

func (x *UpdateClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proofapi_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateClientRequest.ProtoReflect.Descriptor instead.
func (*UpdateClientRequest) Descriptor() ([]byte, []int) {
	return file_proofapi_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateClientRequest) GetSrcChain() string {
	if x != nil {
		return x.SrcChain
	}
	return ""
}

func (x *UpdateClientRequest) GetDstChain() string {
	if x != nil {
		return x.DstChain
	}
	return ""
}

func (x *UpdateClientRequest) GetDstClientId() string {
	if x != nil {
		return x.DstClientId
	}
	return ""
}

// The update client response message
type UpdateClientResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The transaction to be submitted by caller
	Tx []byte `protobuf:"bytes,1,opt,name=tx,proto3" json:"tx,omitempty"`
	// The contract address to submit the transaction, if applicable
	Address       string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateClientResponse) Reset() {
	*x = UpdateClientResponse{}
	mi := &file_proofapi_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateClientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateClientResponse) ProtoMessage() {}

func (x *UpdateClientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proofapi_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateClientResponse.ProtoReflect.Descriptor instead.
func (*UpdateClientResponse) Descriptor() ([]byte, []int) {
	return file_proofapi_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateClientResponse) GetTx() []byte {
	if x != nil {
		return x.Tx
	}
	return nil
}

func (x *UpdateClientResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

// Information request message
type InfoRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The source chain identifier
	SrcChain string `protobuf:"bytes,1,opt,name=src_chain,json=srcChain,proto3" json:"src_chain,omitempty"`
	// The target chain identifier
	DstChain      string `protobuf:"bytes,2,opt,name=dst_chain,json=dstChain,proto3" json:"dst_chain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoRequest) Reset() {
	*x = InfoRequest{}
	mi := &file_proofapi_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoRequest) ProtoMessage() {}

func (x *InfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proofapi_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoRequest.ProtoReflect.Descriptor instead.
func (*InfoRequest) Descriptor() ([]byte, []int) {
	return file_proofapi_proto_rawDescGZIP(), []int{6}
}

func (x *InfoRequest) GetSrcChain() string {
	if x != nil {
		return x.SrcChain
	}
	return ""
}

func (x *InfoRequest) GetDstChain() string {
	if x != nil {
		return x.DstChain
	}
	return ""
}

// Information response message
type InfoResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The target chain information
	TargetChain *Chain `protobuf:"bytes,1,opt,name=target_chain,json=targetChain,proto3" json:"target_chain,omitempty"`
	// The source chain information
	SourceChain *Chain `protobuf:"bytes,2,opt,name=source_chain,json=sourceChain,proto3" json:"source_chain,omitempty"`
	// Metadata for the module
	Metadata      map[string]string `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoResponse) Reset() {
	*x = InfoResponse{}
	mi := &file_proofapi_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoResponse) ProtoMessage() {}

func (x *InfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proofapi_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoResponse.ProtoReflect.Descriptor instead.
func (*InfoResponse) Descriptor() ([]byte, []int) {
	return file_proofapi_proto_rawDescGZIP(), []int{7}
}

func (x *InfoResponse) GetTargetChain() *Chain {
	if x != nil {
		return x.TargetChain
	}
	return nil
}

func (x *InfoResponse) GetSourceChain() *Chain {
	if x != nil {
		return x.SourceChain
	}
	return nil
}

func (x *InfoResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// The chain definition
type Chain struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The chain id
	ChainId string `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	// The ibc version
	IbcVersion string `protobuf:"bytes,2,opt,name=ibc_version,json=ibcVersion,proto3" json:"ibc_version,omitempty"`
	// The ibc contract address
	IbcContract   string `protobuf:"bytes,3,opt,name=ibc_contract,json=ibcContract,proto3" json:"ibc_contract,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chain) Reset() {
	*x = Chain{}
	mi := &file_proofapi_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chain) ProtoMessage() {}

func (x *Chain) ProtoReflect() protoreflect.Message {
	mi := &file_proofapi_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chain.ProtoReflect.Descriptor instead.
func (*Chain) Descriptor() ([]byte, []int) {
	return file_proofapi_proto_rawDescGZIP(), []int{8}
}

func (x *Chain) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

func (x *Chain) GetIbcVersion() string {
	if x != nil {
		return x.IbcVersion
	}
	return ""
}

func (x *Chain) GetIbcContract() string {
	if x != nil {
		return x.IbcContract
	}
	return ""
}

var File_proofapi_proto protoreflect.FileDescriptor

const file_proofapi_proto_rawDesc = "" +
	"\n" +
	"\x0eproofapi.proto\x12\bproofapi\"\xc2\x02\n" +
	"\x10RelayByTxRequest\x12\x1b\n" +
	"\tsrc_chain\x18\x01 \x01(\tR\bsrcChain\x12\x1b\n" +
	"\tdst_chain\x18\x02 \x01(\tR\bdstChain\x12\"\n" +
	"\rsource_tx_ids\x18\x03 \x03(\fR\vsourceTxIds\x12$\n" +
	"\x0etimeout_tx_ids\x18\x04 \x03(\fR\ftimeoutTxIds\x12\"\n" +
	"\rsrc_client_id\x18\x05 \x01(\tR\vsrcClientId\x12\"\n" +
	"\rdst_client_id\x18\x06 \x01(\tR\vdstClientId\x120\n" +
	"\x14src_packet_sequences\x18\a \x03(\x04R\x12srcPacketSequences\x120\n" +
	"\x14dst_packet_sequences\x18\b \x03(\x04R\x12dstPacketSequences\"=\n" +
	"\x11RelayByTxResponse\x12\x0e\n" +
	"\x02tx\x18\x01 \x01(\fR\x02tx\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"\xdd\x01\n" +
	"\x13CreateClientRequest\x12\x1b\n" +
	"\tsrc_chain\x18\x01 \x01(\tR\bsrcChain\x12\x1b\n" +
	"\tdst_chain\x18\x02 \x01(\tR\bdstChain\x12M\n" +
	"\n" +
	"parameters\x18\x03 \x03(\v2-.proofapi.CreateClientRequest.ParametersEntryR\n" +
	"parameters\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"@\n" +
	"\x14CreateClientResponse\x12\x0e\n" +
	"\x02tx\x18\x01 \x01(\fR\x02tx\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"s\n" +
	"\x13UpdateClientRequest\x12\x1b\n" +
	"\tsrc_chain\x18\x01 \x01(\tR\bsrcChain\x12\x1b\n" +
	"\tdst_chain\x18\x02 \x01(\tR\bdstChain\x12\"\n" +
	"\rdst_client_id\x18\x03 \x01(\tR\vdstClientId\"@\n" +
	"\x14UpdateClientResponse\x12\x0e\n" +
	"\x02tx\x18\x01 \x01(\fR\x02tx\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"G\n" +
	"\vInfoRequest\x12\x1b\n" +
	"\tsrc_chain\x18\x01 \x01(\tR\bsrcChain\x12\x1b\n" +
	"\tdst_chain\x18\x02 \x01(\tR\bdstChain\"\xf5\x01\n" +
	"\fInfoResponse\x122\n" +
	"\ftarget_chain\x18\x01 \x01(\v2\x0f.proofapi.ChainR\vtargetChain\x122\n" +
	"\fsource_chain\x18\x02 \x01(\v2\x0f.proofapi.ChainR\vsourceChain\x12@\n" +
	"\bmetadata\x18\x03 \x03(\v2$.proofapi.InfoResponse.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"f\n" +
	"\x05Chain\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\tR\achainId\x12\x1f\n" +
	"\vibc_version\x18\x02 \x01(\tR\n" +
	"ibcVersion\x12!\n" +
	"\fibc_contract\x18\x03 \x01(\tR\vibcContract2\xac\x02\n" +
	"\x0fProofApiService\x12D\n" +
	"\tRelayByTx\x12\x1a.proofapi.RelayByTxRequest\x1a\x1b.proofapi.RelayByTxResponse\x12M\n" +
	"\fCreateClient\x12\x1d.proofapi.CreateClientRequest\x1a\x1e.proofapi.CreateClientResponse\x12M\n" +
	"\fUpdateClient\x12\x1d.proofapi.UpdateClientRequest\x1a\x1e.proofapi.UpdateClientResponse\x125\n" +
	"\x04Info\x12\x15.proofapi.InfoRequest\x1a\x16.proofapi.InfoResponseB4Z2github.com/cosmos/ibc/link/internal/types/proofapib\x06proto3"

var (
	file_proofapi_proto_rawDescOnce sync.Once
	file_proofapi_proto_rawDescData []byte
)

func file_proofapi_proto_rawDescGZIP() []byte {
	file_proofapi_proto_rawDescOnce.Do(func() {
		file_proofapi_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proofapi_proto_rawDesc), len(file_proofapi_proto_rawDesc)))
	})
	return file_proofapi_proto_rawDescData
}

var file_proofapi_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proofapi_proto_goTypes = []any{
	(*RelayByTxRequest)(nil),     // 0: proofapi.RelayByTxRequest
	(*RelayByTxResponse)(nil),    // 1: proofapi.RelayByTxResponse
	(*CreateClientRequest)(nil),  // 2: proofapi.CreateClientRequest
	(*CreateClientResponse)(nil), // 3: proofapi.CreateClientResponse
	(*UpdateClientRequest)(nil),  // 4: proofapi.UpdateClientRequest
	(*UpdateClientResponse)(nil), // 5: proofapi.UpdateClientResponse
	(*InfoRequest)(nil),          // 6: proofapi.InfoRequest
	(*InfoResponse)(nil),         // 7: proofapi.InfoResponse
	(*Chain)(nil),                // 8: proofapi.Chain
	nil,                          // 9: proofapi.CreateClientRequest.ParametersEntry
	nil,                          // 10: proofapi.InfoResponse.MetadataEntry
}
var file_proofapi_proto_depIdxs = []int32{
	9,  // 0: proofapi.CreateClientRequest.parameters:type_name -> proofapi.CreateClientRequest.ParametersEntry
	8,  // 1: proofapi.InfoResponse.target_chain:type_name -> proofapi.Chain
	8,  // 2: proofapi.InfoResponse.source_chain:type_name -> proofapi.Chain
	10, // 3: proofapi.InfoResponse.metadata:type_name -> proofapi.InfoResponse.MetadataEntry
	0,  // 4: proofapi.ProofApiService.RelayByTx:input_type -> proofapi.RelayByTxRequest
	2,  // 5: proofapi.ProofApiService.CreateClient:input_type -> proofapi.CreateClientRequest
	4,  // 6: proofapi.ProofApiService.UpdateClient:input_type -> proofapi.UpdateClientRequest
	6,  // 7: proofapi.ProofApiService.Info:input_type -> proofapi.InfoRequest
	1,  // 8: proofapi.ProofApiService.RelayByTx:output_type -> proofapi.RelayByTxResponse
	3,  // 9: proofapi.ProofApiService.CreateClient:output_type -> proofapi.CreateClientResponse
	5,  // 10: proofapi.ProofApiService.UpdateClient:output_type -> proofapi.UpdateClientResponse
	7,  // 11: proofapi.ProofApiService.Info:output_type -> proofapi.InfoResponse
	8,  // [8:12] is the sub-list for method output_type
	4,  // [4:8] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proofapi_proto_init() }
func file_proofapi_proto_init() {
	if File_proofapi_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proofapi_proto_rawDesc), len(file_proofapi_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proofapi_proto_goTypes,
		DependencyIndexes: file_proofapi_proto_depIdxs,
		MessageInfos:      file_proofapi_proto_msgTypes,
	}.Build()
	File_proofapi_proto = out.File
	file_proofapi_proto_goTypes = nil
	file_proofapi_proto_depIdxs = nil
}
