// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: proofapi.proto

package proofapi

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ProofApiServiceName is the fully-qualified name of the ProofApiService service.
	ProofApiServiceName = "proofapi.ProofApiService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ProofApiServiceRelayByTxProcedure is the fully-qualified name of the ProofApiService's RelayByTx
	// RPC.
	ProofApiServiceRelayByTxProcedure = "/proofapi.ProofApiService/RelayByTx"
	// ProofApiServiceCreateClientProcedure is the fully-qualified name of the ProofApiService's
	// CreateClient RPC.
	ProofApiServiceCreateClientProcedure = "/proofapi.ProofApiService/CreateClient"
	// ProofApiServiceUpdateClientProcedure is the fully-qualified name of the ProofApiService's
	// UpdateClient RPC.
	ProofApiServiceUpdateClientProcedure = "/proofapi.ProofApiService/UpdateClient"
	// ProofApiServiceInfoProcedure is the fully-qualified name of the ProofApiService's Info RPC.
	ProofApiServiceInfoProcedure = "/proofapi.ProofApiService/Info"
)

// ProofApiServiceClient is a client for the proofapi.ProofApiService service.
type ProofApiServiceClient interface {
	// Relay the ibc packets produced by the results of transactions
	RelayByTx(context.Context, *connect.Request[RelayByTxRequest]) (*connect.Response[RelayByTxResponse], error)
	// Create a new ibc client on the target (destination) chain
	CreateClient(context.Context, *connect.Request[CreateClientRequest]) (*connect.Response[CreateClientResponse], error)
	// Update the ibc client on the target (destination) chain
	UpdateClient(context.Context, *connect.Request[UpdateClientRequest]) (*connect.Response[UpdateClientResponse], error)
	// Request proof API information
	Info(context.Context, *connect.Request[InfoRequest]) (*connect.Response[InfoResponse], error)
}

// NewProofApiServiceClient constructs a client for the proofapi.ProofApiService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewProofApiServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ProofApiServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	proofApiServiceMethods := File_proofapi_proto.Services().ByName("ProofApiService").Methods()
	return &proofApiServiceClient{
		relayByTx: connect.NewClient[RelayByTxRequest, RelayByTxResponse](
			httpClient,
			baseURL+ProofApiServiceRelayByTxProcedure,
			connect.WithSchema(proofApiServiceMethods.ByName("RelayByTx")),
			connect.WithClientOptions(opts...),
		),
		createClient: connect.NewClient[CreateClientRequest, CreateClientResponse](
			httpClient,
			baseURL+ProofApiServiceCreateClientProcedure,
			connect.WithSchema(proofApiServiceMethods.ByName("CreateClient")),
			connect.WithClientOptions(opts...),
		),
		updateClient: connect.NewClient[UpdateClientRequest, UpdateClientResponse](
			httpClient,
			baseURL+ProofApiServiceUpdateClientProcedure,
			connect.WithSchema(proofApiServiceMethods.ByName("UpdateClient")),
			connect.WithClientOptions(opts...),
		),
		info: connect.NewClient[InfoRequest, InfoResponse](
			httpClient,
			baseURL+ProofApiServiceInfoProcedure,
			connect.WithSchema(proofApiServiceMethods.ByName("Info")),
			connect.WithClientOptions(opts...),
		),
	}
}

// proofApiServiceClient implements ProofApiServiceClient.
type proofApiServiceClient struct {
	relayByTx    *connect.Client[RelayByTxRequest, RelayByTxResponse]
	createClient *connect.Client[CreateClientRequest, CreateClientResponse]
	updateClient *connect.Client[UpdateClientRequest, UpdateClientResponse]
	info         *connect.Client[InfoRequest, InfoResponse]
}

// RelayByTx calls proofapi.ProofApiService.RelayByTx.
func (c *proofApiServiceClient) RelayByTx(ctx context.Context, req *connect.Request[RelayByTxRequest]) (*connect.Response[RelayByTxResponse], error) {
	return c.relayByTx.CallUnary(ctx, req)
}

// CreateClient calls proofapi.ProofApiService.CreateClient.
func (c *proofApiServiceClient) CreateClient(ctx context.Context, req *connect.Request[CreateClientRequest]) (*connect.Response[CreateClientResponse], error) {
	return c.createClient.CallUnary(ctx, req)
}

// UpdateClient calls proofapi.ProofApiService.UpdateClient.
func (c *proofApiServiceClient) UpdateClient(ctx context.Context, req *connect.Request[UpdateClientRequest]) (*connect.Response[UpdateClientResponse], error) {
	return c.updateClient.CallUnary(ctx, req)
}

// Info calls proofapi.ProofApiService.Info.
func (c *proofApiServiceClient) Info(ctx context.Context, req *connect.Request[InfoRequest]) (*connect.Response[InfoResponse], error) {
	return c.info.CallUnary(ctx, req)
}

// ProofApiServiceHandler is an implementation of the proofapi.ProofApiService service.
type ProofApiServiceHandler interface {
	// Relay the ibc packets produced by the results of transactions
	RelayByTx(context.Context, *connect.Request[RelayByTxRequest]) (*connect.Response[RelayByTxResponse], error)
	// Create a new ibc client on the target (destination) chain
	CreateClient(context.Context, *connect.Request[CreateClientRequest]) (*connect.Response[CreateClientResponse], error)
	// Update the ibc client on the target (destination) chain
	UpdateClient(context.Context, *connect.Request[UpdateClientRequest]) (*connect.Response[UpdateClientResponse], error)
	// Request proof API information
	Info(context.Context, *connect.Request[InfoRequest]) (*connect.Response[InfoResponse], error)
}

// NewProofApiServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewProofApiServiceHandler(svc ProofApiServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	proofApiServiceMethods := File_proofapi_proto.Services().ByName("ProofApiService").Methods()
	proofApiServiceRelayByTxHandler := connect.NewUnaryHandler(
		ProofApiServiceRelayByTxProcedure,
		svc.RelayByTx,
		connect.WithSchema(proofApiServiceMethods.ByName("RelayByTx")),
		connect.WithHandlerOptions(opts...),
	)
	proofApiServiceCreateClientHandler := connect.NewUnaryHandler(
		ProofApiServiceCreateClientProcedure,
		svc.CreateClient,
		connect.WithSchema(proofApiServiceMethods.ByName("CreateClient")),
		connect.WithHandlerOptions(opts...),
	)
	proofApiServiceUpdateClientHandler := connect.NewUnaryHandler(
		ProofApiServiceUpdateClientProcedure,
		svc.UpdateClient,
		connect.WithSchema(proofApiServiceMethods.ByName("UpdateClient")),
		connect.WithHandlerOptions(opts...),
	)
	proofApiServiceInfoHandler := connect.NewUnaryHandler(
		ProofApiServiceInfoProcedure,
		svc.Info,
		connect.WithSchema(proofApiServiceMethods.ByName("Info")),
		connect.WithHandlerOptions(opts...),
	)
	return "/proofapi.ProofApiService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ProofApiServiceRelayByTxProcedure:
			proofApiServiceRelayByTxHandler.ServeHTTP(w, r)
		case ProofApiServiceCreateClientProcedure:
			proofApiServiceCreateClientHandler.ServeHTTP(w, r)
		case ProofApiServiceUpdateClientProcedure:
			proofApiServiceUpdateClientHandler.ServeHTTP(w, r)
		case ProofApiServiceInfoProcedure:
			proofApiServiceInfoHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedProofApiServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedProofApiServiceHandler struct{}

func (UnimplementedProofApiServiceHandler) RelayByTx(context.Context, *connect.Request[RelayByTxRequest]) (*connect.Response[RelayByTxResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("proofapi.ProofApiService.RelayByTx is not implemented"))
}

func (UnimplementedProofApiServiceHandler) CreateClient(context.Context, *connect.Request[CreateClientRequest]) (*connect.Response[CreateClientResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("proofapi.ProofApiService.CreateClient is not implemented"))
}

func (UnimplementedProofApiServiceHandler) UpdateClient(context.Context, *connect.Request[UpdateClientRequest]) (*connect.Response[UpdateClientResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("proofapi.ProofApiService.UpdateClient is not implemented"))
}

func (UnimplementedProofApiServiceHandler) Info(context.Context, *connect.Request[InfoRequest]) (*connect.Response[InfoResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("proofapi.ProofApiService.Info is not implemented"))
}
