// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"connectrpc.com/connect"
	"context"
	"github.com/cosmos/ibc/link/internal/types/v2/attestor"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAttestationServiceClient creates a new instance of MockAttestationServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAttestationServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAttestationServiceClient {
	mock := &MockAttestationServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAttestationServiceClient is an autogenerated mock type for the AttestationServiceClient type
type MockAttestationServiceClient struct {
	mock.Mock
}

type MockAttestationServiceClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAttestationServiceClient) EXPECT() *MockAttestationServiceClient_Expecter {
	return &MockAttestationServiceClient_Expecter{mock: &_m.Mock}
}

// LatestHeight provides a mock function for the type MockAttestationServiceClient
func (_mock *MockAttestationServiceClient) LatestHeight(context1 context.Context, request *connect.Request[attestor.LatestHeightRequest]) (*connect.Response[attestor.LatestHeightResponse], error) {
	ret := _mock.Called(context1, request)

	if len(ret) == 0 {
		panic("no return value specified for LatestHeight")
	}

	var r0 *connect.Response[attestor.LatestHeightResponse]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *connect.Request[attestor.LatestHeightRequest]) (*connect.Response[attestor.LatestHeightResponse], error)); ok {
		return returnFunc(context1, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *connect.Request[attestor.LatestHeightRequest]) *connect.Response[attestor.LatestHeightResponse]); ok {
		r0 = returnFunc(context1, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*connect.Response[attestor.LatestHeightResponse])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *connect.Request[attestor.LatestHeightRequest]) error); ok {
		r1 = returnFunc(context1, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAttestationServiceClient_LatestHeight_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LatestHeight'
type MockAttestationServiceClient_LatestHeight_Call struct {
	*mock.Call
}

// LatestHeight is a helper method to define mock.On call
//   - context1 context.Context
//   - request *connect.Request[attestor.LatestHeightRequest]
func (_e *MockAttestationServiceClient_Expecter) LatestHeight(context1 any, request any) *MockAttestationServiceClient_LatestHeight_Call {
	return &MockAttestationServiceClient_LatestHeight_Call{Call: _e.mock.On("LatestHeight", context1, request)}
}

func (_c *MockAttestationServiceClient_LatestHeight_Call) Run(run func(context1 context.Context, request *connect.Request[attestor.LatestHeightRequest])) *MockAttestationServiceClient_LatestHeight_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *connect.Request[attestor.LatestHeightRequest]
		if args[1] != nil {
			arg1 = args[1].(*connect.Request[attestor.LatestHeightRequest])
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAttestationServiceClient_LatestHeight_Call) Return(response *connect.Response[attestor.LatestHeightResponse], err error) *MockAttestationServiceClient_LatestHeight_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockAttestationServiceClient_LatestHeight_Call) RunAndReturn(run func(context1 context.Context, request *connect.Request[attestor.LatestHeightRequest]) (*connect.Response[attestor.LatestHeightResponse], error)) *MockAttestationServiceClient_LatestHeight_Call {
	_c.Call.Return(run)
	return _c
}

// PacketAttestation provides a mock function for the type MockAttestationServiceClient
func (_mock *MockAttestationServiceClient) PacketAttestation(context1 context.Context, request *connect.Request[attestor.PacketAttestationRequest]) (*connect.Response[attestor.PacketAttestationResponse], error) {
	ret := _mock.Called(context1, request)

	if len(ret) == 0 {
		panic("no return value specified for PacketAttestation")
	}

	var r0 *connect.Response[attestor.PacketAttestationResponse]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *connect.Request[attestor.PacketAttestationRequest]) (*connect.Response[attestor.PacketAttestationResponse], error)); ok {
		return returnFunc(context1, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *connect.Request[attestor.PacketAttestationRequest]) *connect.Response[attestor.PacketAttestationResponse]); ok {
		r0 = returnFunc(context1, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*connect.Response[attestor.PacketAttestationResponse])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *connect.Request[attestor.PacketAttestationRequest]) error); ok {
		r1 = returnFunc(context1, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAttestationServiceClient_PacketAttestation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PacketAttestation'
type MockAttestationServiceClient_PacketAttestation_Call struct {
	*mock.Call
}

// PacketAttestation is a helper method to define mock.On call
//   - context1 context.Context
//   - request *connect.Request[attestor.PacketAttestationRequest]
func (_e *MockAttestationServiceClient_Expecter) PacketAttestation(context1 any, request any) *MockAttestationServiceClient_PacketAttestation_Call {
	return &MockAttestationServiceClient_PacketAttestation_Call{Call: _e.mock.On("PacketAttestation", context1, request)}
}

func (_c *MockAttestationServiceClient_PacketAttestation_Call) Run(run func(context1 context.Context, request *connect.Request[attestor.PacketAttestationRequest])) *MockAttestationServiceClient_PacketAttestation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *connect.Request[attestor.PacketAttestationRequest]
		if args[1] != nil {
			arg1 = args[1].(*connect.Request[attestor.PacketAttestationRequest])
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAttestationServiceClient_PacketAttestation_Call) Return(response *connect.Response[attestor.PacketAttestationResponse], err error) *MockAttestationServiceClient_PacketAttestation_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockAttestationServiceClient_PacketAttestation_Call) RunAndReturn(run func(context1 context.Context, request *connect.Request[attestor.PacketAttestationRequest]) (*connect.Response[attestor.PacketAttestationResponse], error)) *MockAttestationServiceClient_PacketAttestation_Call {
	_c.Call.Return(run)
	return _c
}

// StateAttestation provides a mock function for the type MockAttestationServiceClient
func (_mock *MockAttestationServiceClient) StateAttestation(context1 context.Context, request *connect.Request[attestor.StateAttestationRequest]) (*connect.Response[attestor.StateAttestationResponse], error) {
	ret := _mock.Called(context1, request)

	if len(ret) == 0 {
		panic("no return value specified for StateAttestation")
	}

	var r0 *connect.Response[attestor.StateAttestationResponse]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *connect.Request[attestor.StateAttestationRequest]) (*connect.Response[attestor.StateAttestationResponse], error)); ok {
		return returnFunc(context1, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *connect.Request[attestor.StateAttestationRequest]) *connect.Response[attestor.StateAttestationResponse]); ok {
		r0 = returnFunc(context1, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*connect.Response[attestor.StateAttestationResponse])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *connect.Request[attestor.StateAttestationRequest]) error); ok {
		r1 = returnFunc(context1, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAttestationServiceClient_StateAttestation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StateAttestation'
type MockAttestationServiceClient_StateAttestation_Call struct {
	*mock.Call
}

// StateAttestation is a helper method to define mock.On call
//   - context1 context.Context
//   - request *connect.Request[attestor.StateAttestationRequest]
func (_e *MockAttestationServiceClient_Expecter) StateAttestation(context1 any, request any) *MockAttestationServiceClient_StateAttestation_Call {
	return &MockAttestationServiceClient_StateAttestation_Call{Call: _e.mock.On("StateAttestation", context1, request)}
}

func (_c *MockAttestationServiceClient_StateAttestation_Call) Run(run func(context1 context.Context, request *connect.Request[attestor.StateAttestationRequest])) *MockAttestationServiceClient_StateAttestation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *connect.Request[attestor.StateAttestationRequest]
		if args[1] != nil {
			arg1 = args[1].(*connect.Request[attestor.StateAttestationRequest])
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAttestationServiceClient_StateAttestation_Call) Return(response *connect.Response[attestor.StateAttestationResponse], err error) *MockAttestationServiceClient_StateAttestation_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockAttestationServiceClient_StateAttestation_Call) RunAndReturn(run func(context1 context.Context, request *connect.Request[attestor.StateAttestationRequest]) (*connect.Response[attestor.StateAttestationResponse], error)) *MockAttestationServiceClient_StateAttestation_Call {
	_c.Call.Return(run)
	return _c
}
