// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"github.com/cosmos/ibc-go/v11/modules/core/04-channel/v2/types"
	"github.com/cosmos/ibc/link/lightclient"
	mock "github.com/stretchr/testify/mock"
	"time"
)

// NewMockProofGenerator creates a new instance of MockProofGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProofGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProofGenerator {
	mock := &MockProofGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProofGenerator is an autogenerated mock type for the ProofGenerator type
type MockProofGenerator struct {
	mock.Mock
}

type MockProofGenerator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProofGenerator) EXPECT() *MockProofGenerator_Expecter {
	return &MockProofGenerator_Expecter{mock: &_m.Mock}
}

// LatestProvableHeight provides a mock function for the type MockProofGenerator
func (_mock *MockProofGenerator) LatestProvableHeight(ctx context.Context) (uint64, time.Time, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for LatestProvableHeight")
	}

	var r0 uint64
	var r1 time.Time
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (uint64, time.Time, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) uint64); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(uint64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) time.Time); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Get(1).(time.Time)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context) error); ok {
		r2 = returnFunc(ctx)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockProofGenerator_LatestProvableHeight_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LatestProvableHeight'
type MockProofGenerator_LatestProvableHeight_Call struct {
	*mock.Call
}

// LatestProvableHeight is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockProofGenerator_Expecter) LatestProvableHeight(ctx any) *MockProofGenerator_LatestProvableHeight_Call {
	return &MockProofGenerator_LatestProvableHeight_Call{Call: _e.mock.On("LatestProvableHeight", ctx)}
}

func (_c *MockProofGenerator_LatestProvableHeight_Call) Run(run func(ctx context.Context)) *MockProofGenerator_LatestProvableHeight_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockProofGenerator_LatestProvableHeight_Call) Return(v uint64, time1 time.Time, err error) *MockProofGenerator_LatestProvableHeight_Call {
	_c.Call.Return(v, time1, err)
	return _c
}

func (_c *MockProofGenerator_LatestProvableHeight_Call) RunAndReturn(run func(ctx context.Context) (uint64, time.Time, error)) *MockProofGenerator_LatestProvableHeight_Call {
	_c.Call.Return(run)
	return _c
}

// PacketProofs provides a mock function for the type MockProofGenerator
func (_mock *MockProofGenerator) PacketProofs(ctx context.Context, height uint64, kind lightclient.ProofKind, packets []types.Packet) ([][]byte, error) {
	ret := _mock.Called(ctx, height, kind, packets)

	if len(ret) == 0 {
		panic("no return value specified for PacketProofs")
	}

	var r0 [][]byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, lightclient.ProofKind, []types.Packet) ([][]byte, error)); ok {
		return returnFunc(ctx, height, kind, packets)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, lightclient.ProofKind, []types.Packet) [][]byte); ok {
		r0 = returnFunc(ctx, height, kind, packets)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([][]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64, lightclient.ProofKind, []types.Packet) error); ok {
		r1 = returnFunc(ctx, height, kind, packets)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProofGenerator_PacketProofs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PacketProofs'
type MockProofGenerator_PacketProofs_Call struct {
	*mock.Call
}

// PacketProofs is a helper method to define mock.On call
//   - ctx context.Context
//   - height uint64
//   - kind lightclient.ProofKind
//   - packets []types.Packet
func (_e *MockProofGenerator_Expecter) PacketProofs(ctx any, height any, kind any, packets any) *MockProofGenerator_PacketProofs_Call {
	return &MockProofGenerator_PacketProofs_Call{Call: _e.mock.On("PacketProofs", ctx, height, kind, packets)}
}

func (_c *MockProofGenerator_PacketProofs_Call) Run(run func(ctx context.Context, height uint64, kind lightclient.ProofKind, packets []types.Packet)) *MockProofGenerator_PacketProofs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 lightclient.ProofKind
		if args[2] != nil {
			arg2 = args[2].(lightclient.ProofKind)
		}
		var arg3 []types.Packet
		if args[3] != nil {
			arg3 = args[3].([]types.Packet)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockProofGenerator_PacketProofs_Call) Return(bytess [][]byte, err error) *MockProofGenerator_PacketProofs_Call {
	_c.Call.Return(bytess, err)
	return _c
}

func (_c *MockProofGenerator_PacketProofs_Call) RunAndReturn(run func(ctx context.Context, height uint64, kind lightclient.ProofKind, packets []types.Packet) ([][]byte, error)) *MockProofGenerator_PacketProofs_Call {
	_c.Call.Return(run)
	return _c
}

// StateProof provides a mock function for the type MockProofGenerator
func (_mock *MockProofGenerator) StateProof(ctx context.Context, height uint64) ([]byte, error) {
	ret := _mock.Called(ctx, height)

	if len(ret) == 0 {
		panic("no return value specified for StateProof")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) ([]byte, error)); ok {
		return returnFunc(ctx, height)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) []byte); ok {
		r0 = returnFunc(ctx, height)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = returnFunc(ctx, height)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProofGenerator_StateProof_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StateProof'
type MockProofGenerator_StateProof_Call struct {
	*mock.Call
}

// StateProof is a helper method to define mock.On call
//   - ctx context.Context
//   - height uint64
func (_e *MockProofGenerator_Expecter) StateProof(ctx any, height any) *MockProofGenerator_StateProof_Call {
	return &MockProofGenerator_StateProof_Call{Call: _e.mock.On("StateProof", ctx, height)}
}

func (_c *MockProofGenerator_StateProof_Call) Run(run func(ctx context.Context, height uint64)) *MockProofGenerator_StateProof_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProofGenerator_StateProof_Call) Return(bytes []byte, err error) *MockProofGenerator_StateProof_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockProofGenerator_StateProof_Call) RunAndReturn(run func(ctx context.Context, height uint64) ([]byte, error)) *MockProofGenerator_StateProof_Call {
	_c.Call.Return(run)
	return _c
}
