// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"github.com/ethereum/go-ethereum"
	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/core/types"
	mock "github.com/stretchr/testify/mock"
	"math/big"
)

// NewMockTxSubmitterETHClient creates a new instance of MockTxSubmitterETHClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTxSubmitterETHClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTxSubmitterETHClient {
	mock := &MockTxSubmitterETHClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTxSubmitterETHClient is an autogenerated mock type for the ETHClient type
type MockTxSubmitterETHClient struct {
	mock.Mock
}

type MockTxSubmitterETHClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTxSubmitterETHClient) EXPECT() *MockTxSubmitterETHClient_Expecter {
	return &MockTxSubmitterETHClient_Expecter{mock: &_m.Mock}
}

// EstimateGas provides a mock function for the type MockTxSubmitterETHClient
func (_mock *MockTxSubmitterETHClient) EstimateGas(ctx context.Context, call ethereum.CallMsg) (uint64, error) {
	ret := _mock.Called(ctx, call)

	if len(ret) == 0 {
		panic("no return value specified for EstimateGas")
	}

	var r0 uint64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ethereum.CallMsg) (uint64, error)); ok {
		return returnFunc(ctx, call)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ethereum.CallMsg) uint64); ok {
		r0 = returnFunc(ctx, call)
	} else {
		r0 = ret.Get(0).(uint64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ethereum.CallMsg) error); ok {
		r1 = returnFunc(ctx, call)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTxSubmitterETHClient_EstimateGas_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EstimateGas'
type MockTxSubmitterETHClient_EstimateGas_Call struct {
	*mock.Call
}

// EstimateGas is a helper method to define mock.On call
//   - ctx context.Context
//   - call ethereum.CallMsg
func (_e *MockTxSubmitterETHClient_Expecter) EstimateGas(ctx any, call any) *MockTxSubmitterETHClient_EstimateGas_Call {
	return &MockTxSubmitterETHClient_EstimateGas_Call{Call: _e.mock.On("EstimateGas", ctx, call)}
}

func (_c *MockTxSubmitterETHClient_EstimateGas_Call) Run(run func(ctx context.Context, call ethereum.CallMsg)) *MockTxSubmitterETHClient_EstimateGas_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ethereum.CallMsg
		if args[1] != nil {
			arg1 = args[1].(ethereum.CallMsg)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTxSubmitterETHClient_EstimateGas_Call) Return(v uint64, err error) *MockTxSubmitterETHClient_EstimateGas_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockTxSubmitterETHClient_EstimateGas_Call) RunAndReturn(run func(ctx context.Context, call ethereum.CallMsg) (uint64, error)) *MockTxSubmitterETHClient_EstimateGas_Call {
	_c.Call.Return(run)
	return _c
}

// HeaderByNumber provides a mock function for the type MockTxSubmitterETHClient
func (_mock *MockTxSubmitterETHClient) HeaderByNumber(ctx context.Context, number *big.Int) (*types.Header, error) {
	ret := _mock.Called(ctx, number)

	if len(ret) == 0 {
		panic("no return value specified for HeaderByNumber")
	}

	var r0 *types.Header
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *big.Int) (*types.Header, error)); ok {
		return returnFunc(ctx, number)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *big.Int) *types.Header); ok {
		r0 = returnFunc(ctx, number)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Header)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *big.Int) error); ok {
		r1 = returnFunc(ctx, number)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTxSubmitterETHClient_HeaderByNumber_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HeaderByNumber'
type MockTxSubmitterETHClient_HeaderByNumber_Call struct {
	*mock.Call
}

// HeaderByNumber is a helper method to define mock.On call
//   - ctx context.Context
//   - number *big.Int
func (_e *MockTxSubmitterETHClient_Expecter) HeaderByNumber(ctx any, number any) *MockTxSubmitterETHClient_HeaderByNumber_Call {
	return &MockTxSubmitterETHClient_HeaderByNumber_Call{Call: _e.mock.On("HeaderByNumber", ctx, number)}
}

func (_c *MockTxSubmitterETHClient_HeaderByNumber_Call) Run(run func(ctx context.Context, number *big.Int)) *MockTxSubmitterETHClient_HeaderByNumber_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *big.Int
		if args[1] != nil {
			arg1 = args[1].(*big.Int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTxSubmitterETHClient_HeaderByNumber_Call) Return(header *types.Header, err error) *MockTxSubmitterETHClient_HeaderByNumber_Call {
	_c.Call.Return(header, err)
	return _c
}

func (_c *MockTxSubmitterETHClient_HeaderByNumber_Call) RunAndReturn(run func(ctx context.Context, number *big.Int) (*types.Header, error)) *MockTxSubmitterETHClient_HeaderByNumber_Call {
	_c.Call.Return(run)
	return _c
}

// PendingCodeAt provides a mock function for the type MockTxSubmitterETHClient
func (_mock *MockTxSubmitterETHClient) PendingCodeAt(ctx context.Context, account common.Address) ([]byte, error) {
	ret := _mock.Called(ctx, account)

	if len(ret) == 0 {
		panic("no return value specified for PendingCodeAt")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, common.Address) ([]byte, error)); ok {
		return returnFunc(ctx, account)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, common.Address) []byte); ok {
		r0 = returnFunc(ctx, account)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, common.Address) error); ok {
		r1 = returnFunc(ctx, account)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTxSubmitterETHClient_PendingCodeAt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PendingCodeAt'
type MockTxSubmitterETHClient_PendingCodeAt_Call struct {
	*mock.Call
}

// PendingCodeAt is a helper method to define mock.On call
//   - ctx context.Context
//   - account common.Address
func (_e *MockTxSubmitterETHClient_Expecter) PendingCodeAt(ctx any, account any) *MockTxSubmitterETHClient_PendingCodeAt_Call {
	return &MockTxSubmitterETHClient_PendingCodeAt_Call{Call: _e.mock.On("PendingCodeAt", ctx, account)}
}

func (_c *MockTxSubmitterETHClient_PendingCodeAt_Call) Run(run func(ctx context.Context, account common.Address)) *MockTxSubmitterETHClient_PendingCodeAt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 common.Address
		if args[1] != nil {
			arg1 = args[1].(common.Address)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTxSubmitterETHClient_PendingCodeAt_Call) Return(bytes []byte, err error) *MockTxSubmitterETHClient_PendingCodeAt_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockTxSubmitterETHClient_PendingCodeAt_Call) RunAndReturn(run func(ctx context.Context, account common.Address) ([]byte, error)) *MockTxSubmitterETHClient_PendingCodeAt_Call {
	_c.Call.Return(run)
	return _c
}

// PendingNonceAt provides a mock function for the type MockTxSubmitterETHClient
func (_mock *MockTxSubmitterETHClient) PendingNonceAt(ctx context.Context, account common.Address) (uint64, error) {
	ret := _mock.Called(ctx, account)

	if len(ret) == 0 {
		panic("no return value specified for PendingNonceAt")
	}

	var r0 uint64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, common.Address) (uint64, error)); ok {
		return returnFunc(ctx, account)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, common.Address) uint64); ok {
		r0 = returnFunc(ctx, account)
	} else {
		r0 = ret.Get(0).(uint64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, common.Address) error); ok {
		r1 = returnFunc(ctx, account)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTxSubmitterETHClient_PendingNonceAt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PendingNonceAt'
type MockTxSubmitterETHClient_PendingNonceAt_Call struct {
	*mock.Call
}

// PendingNonceAt is a helper method to define mock.On call
//   - ctx context.Context
//   - account common.Address
func (_e *MockTxSubmitterETHClient_Expecter) PendingNonceAt(ctx any, account any) *MockTxSubmitterETHClient_PendingNonceAt_Call {
	return &MockTxSubmitterETHClient_PendingNonceAt_Call{Call: _e.mock.On("PendingNonceAt", ctx, account)}
}

func (_c *MockTxSubmitterETHClient_PendingNonceAt_Call) Run(run func(ctx context.Context, account common.Address)) *MockTxSubmitterETHClient_PendingNonceAt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 common.Address
		if args[1] != nil {
			arg1 = args[1].(common.Address)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTxSubmitterETHClient_PendingNonceAt_Call) Return(v uint64, err error) *MockTxSubmitterETHClient_PendingNonceAt_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockTxSubmitterETHClient_PendingNonceAt_Call) RunAndReturn(run func(ctx context.Context, account common.Address) (uint64, error)) *MockTxSubmitterETHClient_PendingNonceAt_Call {
	_c.Call.Return(run)
	return _c
}

// SendTransaction provides a mock function for the type MockTxSubmitterETHClient
func (_mock *MockTxSubmitterETHClient) SendTransaction(ctx context.Context, tx *types.Transaction) error {
	ret := _mock.Called(ctx, tx)

	if len(ret) == 0 {
		panic("no return value specified for SendTransaction")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types.Transaction) error); ok {
		r0 = returnFunc(ctx, tx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTxSubmitterETHClient_SendTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendTransaction'
type MockTxSubmitterETHClient_SendTransaction_Call struct {
	*mock.Call
}

// SendTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *types.Transaction
func (_e *MockTxSubmitterETHClient_Expecter) SendTransaction(ctx any, tx any) *MockTxSubmitterETHClient_SendTransaction_Call {
	return &MockTxSubmitterETHClient_SendTransaction_Call{Call: _e.mock.On("SendTransaction", ctx, tx)}
}

func (_c *MockTxSubmitterETHClient_SendTransaction_Call) Run(run func(ctx context.Context, tx *types.Transaction)) *MockTxSubmitterETHClient_SendTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *types.Transaction
		if args[1] != nil {
			arg1 = args[1].(*types.Transaction)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTxSubmitterETHClient_SendTransaction_Call) Return(err error) *MockTxSubmitterETHClient_SendTransaction_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTxSubmitterETHClient_SendTransaction_Call) RunAndReturn(run func(ctx context.Context, tx *types.Transaction) error) *MockTxSubmitterETHClient_SendTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// SuggestGasTipCap provides a mock function for the type MockTxSubmitterETHClient
func (_mock *MockTxSubmitterETHClient) SuggestGasTipCap(ctx context.Context) (*big.Int, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for SuggestGasTipCap")
	}

	var r0 *big.Int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*big.Int, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *big.Int); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*big.Int)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTxSubmitterETHClient_SuggestGasTipCap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SuggestGasTipCap'
type MockTxSubmitterETHClient_SuggestGasTipCap_Call struct {
	*mock.Call
}

// SuggestGasTipCap is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTxSubmitterETHClient_Expecter) SuggestGasTipCap(ctx any) *MockTxSubmitterETHClient_SuggestGasTipCap_Call {
	return &MockTxSubmitterETHClient_SuggestGasTipCap_Call{Call: _e.mock.On("SuggestGasTipCap", ctx)}
}

func (_c *MockTxSubmitterETHClient_SuggestGasTipCap_Call) Run(run func(ctx context.Context)) *MockTxSubmitterETHClient_SuggestGasTipCap_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTxSubmitterETHClient_SuggestGasTipCap_Call) Return(intParam *big.Int, err error) *MockTxSubmitterETHClient_SuggestGasTipCap_Call {
	_c.Call.Return(intParam, err)
	return _c
}

func (_c *MockTxSubmitterETHClient_SuggestGasTipCap_Call) RunAndReturn(run func(ctx context.Context) (*big.Int, error)) *MockTxSubmitterETHClient_SuggestGasTipCap_Call {
	_c.Call.Return(run)
	return _c
}

// TransactionReceipt provides a mock function for the type MockTxSubmitterETHClient
func (_mock *MockTxSubmitterETHClient) TransactionReceipt(ctx context.Context, txHash common.Hash) (*types.Receipt, error) {
	ret := _mock.Called(ctx, txHash)

	if len(ret) == 0 {
		panic("no return value specified for TransactionReceipt")
	}

	var r0 *types.Receipt
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, common.Hash) (*types.Receipt, error)); ok {
		return returnFunc(ctx, txHash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, common.Hash) *types.Receipt); ok {
		r0 = returnFunc(ctx, txHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Receipt)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, common.Hash) error); ok {
		r1 = returnFunc(ctx, txHash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTxSubmitterETHClient_TransactionReceipt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TransactionReceipt'
type MockTxSubmitterETHClient_TransactionReceipt_Call struct {
	*mock.Call
}

// TransactionReceipt is a helper method to define mock.On call
//   - ctx context.Context
//   - txHash common.Hash
func (_e *MockTxSubmitterETHClient_Expecter) TransactionReceipt(ctx any, txHash any) *MockTxSubmitterETHClient_TransactionReceipt_Call {
	return &MockTxSubmitterETHClient_TransactionReceipt_Call{Call: _e.mock.On("TransactionReceipt", ctx, txHash)}
}

func (_c *MockTxSubmitterETHClient_TransactionReceipt_Call) Run(run func(ctx context.Context, txHash common.Hash)) *MockTxSubmitterETHClient_TransactionReceipt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 common.Hash
		if args[1] != nil {
			arg1 = args[1].(common.Hash)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTxSubmitterETHClient_TransactionReceipt_Call) Return(receipt *types.Receipt, err error) *MockTxSubmitterETHClient_TransactionReceipt_Call {
	_c.Call.Return(receipt, err)
	return _c
}

func (_c *MockTxSubmitterETHClient_TransactionReceipt_Call) RunAndReturn(run func(ctx context.Context, txHash common.Hash) (*types.Receipt, error)) *MockTxSubmitterETHClient_TransactionReceipt_Call {
	_c.Call.Return(run)
	return _c
}
