// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"github.com/cosmos/ibc/link/internal/store"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPacketStore creates a new instance of MockPacketStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPacketStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPacketStore {
	mock := &MockPacketStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPacketStore is an autogenerated mock type for the PacketStore type
type MockPacketStore struct {
	mock.Mock
}

type MockPacketStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPacketStore) EXPECT() *MockPacketStore_Expecter {
	return &MockPacketStore_Expecter{mock: &_m.Mock}
}

// UpsertPacket provides a mock function for the type MockPacketStore
func (_mock *MockPacketStore) UpsertPacket(ctx context.Context, input store.UpsertPacket) error {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for UpsertPacket")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, store.UpsertPacket) error); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPacketStore_UpsertPacket_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertPacket'
type MockPacketStore_UpsertPacket_Call struct {
	*mock.Call
}

// UpsertPacket is a helper method to define mock.On call
//   - ctx context.Context
//   - input store.UpsertPacket
func (_e *MockPacketStore_Expecter) UpsertPacket(ctx any, input any) *MockPacketStore_UpsertPacket_Call {
	return &MockPacketStore_UpsertPacket_Call{Call: _e.mock.On("UpsertPacket", ctx, input)}
}

func (_c *MockPacketStore_UpsertPacket_Call) Run(run func(ctx context.Context, input store.UpsertPacket)) *MockPacketStore_UpsertPacket_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 store.UpsertPacket
		if args[1] != nil {
			arg1 = args[1].(store.UpsertPacket)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPacketStore_UpsertPacket_Call) Return(err error) *MockPacketStore_UpsertPacket_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPacketStore_UpsertPacket_Call) RunAndReturn(run func(ctx context.Context, input store.UpsertPacket) error) *MockPacketStore_UpsertPacket_Call {
	_c.Call.Return(run)
	return _c
}
