// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package relayer

import (
	"context"
	"github.com/cosmos/ibc/link/internal/chains"
	"github.com/cosmos/ibc/link/internal/store"
	mock "github.com/stretchr/testify/mock"
)

// NewMockChainClientManager creates a new instance of MockChainClientManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChainClientManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChainClientManager {
	mock := &MockChainClientManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockChainClientManager is an autogenerated mock type for the ChainClientManager type
type MockChainClientManager struct {
	mock.Mock
}

type MockChainClientManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChainClientManager) EXPECT() *MockChainClientManager_Expecter {
	return &MockChainClientManager_Expecter{mock: &_m.Mock}
}

// GetClient provides a mock function for the type MockChainClientManager
func (_mock *MockChainClientManager) GetClient(ctx context.Context, chainID string) (chains.Client, error) {
	ret := _mock.Called(ctx, chainID)

	if len(ret) == 0 {
		panic("no return value specified for GetClient")
	}

	var r0 chains.Client
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (chains.Client, error)); ok {
		return returnFunc(ctx, chainID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) chains.Client); ok {
		r0 = returnFunc(ctx, chainID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(chains.Client)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, chainID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChainClientManager_GetClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetClient'
type MockChainClientManager_GetClient_Call struct {
	*mock.Call
}

// GetClient is a helper method to define mock.On call
//   - ctx context.Context
//   - chainID string
func (_e *MockChainClientManager_Expecter) GetClient(ctx any, chainID any) *MockChainClientManager_GetClient_Call {
	return &MockChainClientManager_GetClient_Call{Call: _e.mock.On("GetClient", ctx, chainID)}
}

func (_c *MockChainClientManager_GetClient_Call) Run(run func(ctx context.Context, chainID string)) *MockChainClientManager_GetClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockChainClientManager_GetClient_Call) Return(client chains.Client, err error) *MockChainClientManager_GetClient_Call {
	_c.Call.Return(client, err)
	return _c
}

func (_c *MockChainClientManager_GetClient_Call) RunAndReturn(run func(ctx context.Context, chainID string) (chains.Client, error)) *MockChainClientManager_GetClient_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStore creates a new instance of MockStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStore {
	mock := &MockStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStore is an autogenerated mock type for the Store type
type MockStore struct {
	mock.Mock
}

type MockStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStore) EXPECT() *MockStore_Expecter {
	return &MockStore_Expecter{mock: &_m.Mock}
}

// ExecTx provides a mock function for the type MockStore
func (_mock *MockStore) ExecTx(ctx context.Context, fn func(store.Repository) error) error {
	ret := _mock.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for ExecTx")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, func(store.Repository) error) error); ok {
		r0 = returnFunc(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStore_ExecTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecTx'
type MockStore_ExecTx_Call struct {
	*mock.Call
}

// ExecTx is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(store.Repository) error
func (_e *MockStore_Expecter) ExecTx(ctx any, fn any) *MockStore_ExecTx_Call {
	return &MockStore_ExecTx_Call{Call: _e.mock.On("ExecTx", ctx, fn)}
}

func (_c *MockStore_ExecTx_Call) Run(run func(ctx context.Context, fn func(store.Repository) error)) *MockStore_ExecTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 func(store.Repository) error
		if args[1] != nil {
			arg1 = args[1].(func(store.Repository) error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_ExecTx_Call) Return(err error) *MockStore_ExecTx_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStore_ExecTx_Call) RunAndReturn(run func(ctx context.Context, fn func(store.Repository) error) error) *MockStore_ExecTx_Call {
	_c.Call.Return(run)
	return _c
}

// GetRelayRequest provides a mock function for the type MockStore
func (_mock *MockStore) GetRelayRequest(ctx context.Context, chainID string, txHash string) (*store.RelayRequest, error) {
	ret := _mock.Called(ctx, chainID, txHash)

	if len(ret) == 0 {
		panic("no return value specified for GetRelayRequest")
	}

	var r0 *store.RelayRequest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*store.RelayRequest, error)); ok {
		return returnFunc(ctx, chainID, txHash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *store.RelayRequest); ok {
		r0 = returnFunc(ctx, chainID, txHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*store.RelayRequest)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, chainID, txHash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_GetRelayRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRelayRequest'
type MockStore_GetRelayRequest_Call struct {
	*mock.Call
}

// GetRelayRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - chainID string
//   - txHash string
func (_e *MockStore_Expecter) GetRelayRequest(ctx any, chainID any, txHash any) *MockStore_GetRelayRequest_Call {
	return &MockStore_GetRelayRequest_Call{Call: _e.mock.On("GetRelayRequest", ctx, chainID, txHash)}
}

func (_c *MockStore_GetRelayRequest_Call) Run(run func(ctx context.Context, chainID string, txHash string)) *MockStore_GetRelayRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStore_GetRelayRequest_Call) Return(relayRequest *store.RelayRequest, err error) *MockStore_GetRelayRequest_Call {
	_c.Call.Return(relayRequest, err)
	return _c
}

func (_c *MockStore_GetRelayRequest_Call) RunAndReturn(run func(ctx context.Context, chainID string, txHash string) (*store.RelayRequest, error)) *MockStore_GetRelayRequest_Call {
	_c.Call.Return(run)
	return _c
}

// ListTransfersBySourceTx provides a mock function for the type MockStore
func (_mock *MockStore) ListTransfersBySourceTx(ctx context.Context, chainID string, txHash string) ([]store.Transfer, error) {
	ret := _mock.Called(ctx, chainID, txHash)

	if len(ret) == 0 {
		panic("no return value specified for ListTransfersBySourceTx")
	}

	var r0 []store.Transfer
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]store.Transfer, error)); ok {
		return returnFunc(ctx, chainID, txHash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []store.Transfer); ok {
		r0 = returnFunc(ctx, chainID, txHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]store.Transfer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, chainID, txHash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_ListTransfersBySourceTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTransfersBySourceTx'
type MockStore_ListTransfersBySourceTx_Call struct {
	*mock.Call
}

// ListTransfersBySourceTx is a helper method to define mock.On call
//   - ctx context.Context
//   - chainID string
//   - txHash string
func (_e *MockStore_Expecter) ListTransfersBySourceTx(ctx any, chainID any, txHash any) *MockStore_ListTransfersBySourceTx_Call {
	return &MockStore_ListTransfersBySourceTx_Call{Call: _e.mock.On("ListTransfersBySourceTx", ctx, chainID, txHash)}
}

func (_c *MockStore_ListTransfersBySourceTx_Call) Run(run func(ctx context.Context, chainID string, txHash string)) *MockStore_ListTransfersBySourceTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStore_ListTransfersBySourceTx_Call) Return(transfers []store.Transfer, err error) *MockStore_ListTransfersBySourceTx_Call {
	_c.Call.Return(transfers, err)
	return _c
}

func (_c *MockStore_ListTransfersBySourceTx_Call) RunAndReturn(run func(ctx context.Context, chainID string, txHash string) ([]store.Transfer, error)) *MockStore_ListTransfersBySourceTx_Call {
	_c.Call.Return(run)
	return _c
}
