// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package relayer

import (
	"context"

	"github.com/cosmos/ibc/link/internal/chains"
	"github.com/cosmos/ibc/link/internal/store"
	mock "github.com/stretchr/testify/mock"
)

// NewMockChainClients creates a new instance of MockChainClients. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChainClients(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChainClients {
	mock := &MockChainClients{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockChainClients is an autogenerated mock type for the ChainClients type
type MockChainClients struct {
	mock.Mock
}

type MockChainClients_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChainClients) EXPECT() *MockChainClients_Expecter {
	return &MockChainClients_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockChainClients
func (_mock *MockChainClients) Get(chainID string) (chains.Client, bool) {
	ret := _mock.Called(chainID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 chains.Client
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(string) (chains.Client, bool)); ok {
		return returnFunc(chainID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) chains.Client); ok {
		r0 = returnFunc(chainID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(chains.Client)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) bool); ok {
		r1 = returnFunc(chainID)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockChainClients_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockChainClients_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - chainID string
func (_e *MockChainClients_Expecter) Get(chainID any) *MockChainClients_Get_Call {
	return &MockChainClients_Get_Call{Call: _e.mock.On("Get", chainID)}
}

func (_c *MockChainClients_Get_Call) Run(run func(chainID string)) *MockChainClients_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockChainClients_Get_Call) Return(client chains.Client, b bool) *MockChainClients_Get_Call {
	_c.Call.Return(client, b)
	return _c
}

func (_c *MockChainClients_Get_Call) RunAndReturn(run func(chainID string) (chains.Client, bool)) *MockChainClients_Get_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStore creates a new instance of MockStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStore {
	mock := &MockStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStore is an autogenerated mock type for the Store type
type MockStore struct {
	mock.Mock
}

type MockStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStore) EXPECT() *MockStore_Expecter {
	return &MockStore_Expecter{mock: &_m.Mock}
}

// GetRelayRequest provides a mock function for the type MockStore
func (_mock *MockStore) GetRelayRequest(ctx context.Context, chainID string, txHash string) (*store.RelayRequest, error) {
	ret := _mock.Called(ctx, chainID, txHash)

	if len(ret) == 0 {
		panic("no return value specified for GetRelayRequest")
	}

	var r0 *store.RelayRequest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*store.RelayRequest, error)); ok {
		return returnFunc(ctx, chainID, txHash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *store.RelayRequest); ok {
		r0 = returnFunc(ctx, chainID, txHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*store.RelayRequest)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, chainID, txHash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_GetRelayRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRelayRequest'
type MockStore_GetRelayRequest_Call struct {
	*mock.Call
}

// GetRelayRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - chainID string
//   - txHash string
func (_e *MockStore_Expecter) GetRelayRequest(ctx any, chainID any, txHash any) *MockStore_GetRelayRequest_Call {
	return &MockStore_GetRelayRequest_Call{Call: _e.mock.On("GetRelayRequest", ctx, chainID, txHash)}
}

func (_c *MockStore_GetRelayRequest_Call) Run(run func(ctx context.Context, chainID string, txHash string)) *MockStore_GetRelayRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStore_GetRelayRequest_Call) Return(relayRequest *store.RelayRequest, err error) *MockStore_GetRelayRequest_Call {
	_c.Call.Return(relayRequest, err)
	return _c
}

func (_c *MockStore_GetRelayRequest_Call) RunAndReturn(run func(ctx context.Context, chainID string, txHash string) (*store.RelayRequest, error)) *MockStore_GetRelayRequest_Call {
	_c.Call.Return(run)
	return _c
}

// ListPacketsBySourceTx provides a mock function for the type MockStore
func (_mock *MockStore) ListPacketsBySourceTx(ctx context.Context, chainID string, txHash string) ([]store.Packet, error) {
	ret := _mock.Called(ctx, chainID, txHash)

	if len(ret) == 0 {
		panic("no return value specified for ListPacketsBySourceTx")
	}

	var r0 []store.Packet
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]store.Packet, error)); ok {
		return returnFunc(ctx, chainID, txHash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []store.Packet); ok {
		r0 = returnFunc(ctx, chainID, txHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]store.Packet)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, chainID, txHash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_ListPacketsBySourceTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPacketsBySourceTx'
type MockStore_ListPacketsBySourceTx_Call struct {
	*mock.Call
}

// ListPacketsBySourceTx is a helper method to define mock.On call
//   - ctx context.Context
//   - chainID string
//   - txHash string
func (_e *MockStore_Expecter) ListPacketsBySourceTx(ctx any, chainID any, txHash any) *MockStore_ListPacketsBySourceTx_Call {
	return &MockStore_ListPacketsBySourceTx_Call{Call: _e.mock.On("ListPacketsBySourceTx", ctx, chainID, txHash)}
}

func (_c *MockStore_ListPacketsBySourceTx_Call) Run(run func(ctx context.Context, chainID string, txHash string)) *MockStore_ListPacketsBySourceTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStore_ListPacketsBySourceTx_Call) Return(packets []store.Packet, err error) *MockStore_ListPacketsBySourceTx_Call {
	_c.Call.Return(packets, err)
	return _c
}

func (_c *MockStore_ListPacketsBySourceTx_Call) RunAndReturn(run func(ctx context.Context, chainID string, txHash string) ([]store.Packet, error)) *MockStore_ListPacketsBySourceTx_Call {
	_c.Call.Return(run)
	return _c
}

// Transact provides a mock function for the type MockStore
func (_mock *MockStore) Transact(ctx context.Context, call func(store.Repository) error) error {
	ret := _mock.Called(ctx, call)

	if len(ret) == 0 {
		panic("no return value specified for Transact")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, func(store.Repository) error) error); ok {
		r0 = returnFunc(ctx, call)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStore_Transact_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Transact'
type MockStore_Transact_Call struct {
	*mock.Call
}

// Transact is a helper method to define mock.On call
//   - ctx context.Context
//   - call func(store.Repository) error
func (_e *MockStore_Expecter) Transact(ctx any, call any) *MockStore_Transact_Call {
	return &MockStore_Transact_Call{Call: _e.mock.On("Transact", ctx, call)}
}

func (_c *MockStore_Transact_Call) Run(run func(ctx context.Context, call func(store.Repository) error)) *MockStore_Transact_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 func(store.Repository) error
		if args[1] != nil {
			arg1 = args[1].(func(store.Repository) error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_Transact_Call) Return(err error) *MockStore_Transact_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStore_Transact_Call) RunAndReturn(run func(ctx context.Context, call func(store.Repository) error) error) *MockStore_Transact_Call {
	_c.Call.Return(run)
	return _c
}
