// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package evm

import (
	"context"
	"github.com/ethereum/go-ethereum"
	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/core/types"
	mock "github.com/stretchr/testify/mock"
	"math/big"
)

// NewMockETHClient creates a new instance of MockETHClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockETHClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockETHClient {
	mock := &MockETHClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockETHClient is an autogenerated mock type for the ETHClient type
type MockETHClient struct {
	mock.Mock
}

type MockETHClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockETHClient) EXPECT() *MockETHClient_Expecter {
	return &MockETHClient_Expecter{mock: &_m.Mock}
}

// FilterLogs provides a mock function for the type MockETHClient
func (_mock *MockETHClient) FilterLogs(ctx context.Context, q ethereum.FilterQuery) ([]types.Log, error) {
	ret := _mock.Called(ctx, q)

	if len(ret) == 0 {
		panic("no return value specified for FilterLogs")
	}

	var r0 []types.Log
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ethereum.FilterQuery) ([]types.Log, error)); ok {
		return returnFunc(ctx, q)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ethereum.FilterQuery) []types.Log); ok {
		r0 = returnFunc(ctx, q)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.Log)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ethereum.FilterQuery) error); ok {
		r1 = returnFunc(ctx, q)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockETHClient_FilterLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FilterLogs'
type MockETHClient_FilterLogs_Call struct {
	*mock.Call
}

// FilterLogs is a helper method to define mock.On call
//   - ctx context.Context
//   - q ethereum.FilterQuery
func (_e *MockETHClient_Expecter) FilterLogs(ctx any, q any) *MockETHClient_FilterLogs_Call {
	return &MockETHClient_FilterLogs_Call{Call: _e.mock.On("FilterLogs", ctx, q)}
}

func (_c *MockETHClient_FilterLogs_Call) Run(run func(ctx context.Context, q ethereum.FilterQuery)) *MockETHClient_FilterLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ethereum.FilterQuery
		if args[1] != nil {
			arg1 = args[1].(ethereum.FilterQuery)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockETHClient_FilterLogs_Call) Return(logs []types.Log, err error) *MockETHClient_FilterLogs_Call {
	_c.Call.Return(logs, err)
	return _c
}

func (_c *MockETHClient_FilterLogs_Call) RunAndReturn(run func(ctx context.Context, q ethereum.FilterQuery) ([]types.Log, error)) *MockETHClient_FilterLogs_Call {
	_c.Call.Return(run)
	return _c
}

// HeaderByNumber provides a mock function for the type MockETHClient
func (_mock *MockETHClient) HeaderByNumber(ctx context.Context, number *big.Int) (*types.Header, error) {
	ret := _mock.Called(ctx, number)

	if len(ret) == 0 {
		panic("no return value specified for HeaderByNumber")
	}

	var r0 *types.Header
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *big.Int) (*types.Header, error)); ok {
		return returnFunc(ctx, number)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *big.Int) *types.Header); ok {
		r0 = returnFunc(ctx, number)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Header)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *big.Int) error); ok {
		r1 = returnFunc(ctx, number)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockETHClient_HeaderByNumber_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HeaderByNumber'
type MockETHClient_HeaderByNumber_Call struct {
	*mock.Call
}

// HeaderByNumber is a helper method to define mock.On call
//   - ctx context.Context
//   - number *big.Int
func (_e *MockETHClient_Expecter) HeaderByNumber(ctx any, number any) *MockETHClient_HeaderByNumber_Call {
	return &MockETHClient_HeaderByNumber_Call{Call: _e.mock.On("HeaderByNumber", ctx, number)}
}

func (_c *MockETHClient_HeaderByNumber_Call) Run(run func(ctx context.Context, number *big.Int)) *MockETHClient_HeaderByNumber_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *big.Int
		if args[1] != nil {
			arg1 = args[1].(*big.Int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockETHClient_HeaderByNumber_Call) Return(header *types.Header, err error) *MockETHClient_HeaderByNumber_Call {
	_c.Call.Return(header, err)
	return _c
}

func (_c *MockETHClient_HeaderByNumber_Call) RunAndReturn(run func(ctx context.Context, number *big.Int) (*types.Header, error)) *MockETHClient_HeaderByNumber_Call {
	_c.Call.Return(run)
	return _c
}

// SubscribeFilterLogs provides a mock function for the type MockETHClient
func (_mock *MockETHClient) SubscribeFilterLogs(ctx context.Context, q ethereum.FilterQuery, ch chan<- types.Log) (ethereum.Subscription, error) {
	ret := _mock.Called(ctx, q, ch)

	if len(ret) == 0 {
		panic("no return value specified for SubscribeFilterLogs")
	}

	var r0 ethereum.Subscription
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ethereum.FilterQuery, chan<- types.Log) (ethereum.Subscription, error)); ok {
		return returnFunc(ctx, q, ch)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ethereum.FilterQuery, chan<- types.Log) ethereum.Subscription); ok {
		r0 = returnFunc(ctx, q, ch)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ethereum.Subscription)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ethereum.FilterQuery, chan<- types.Log) error); ok {
		r1 = returnFunc(ctx, q, ch)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockETHClient_SubscribeFilterLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SubscribeFilterLogs'
type MockETHClient_SubscribeFilterLogs_Call struct {
	*mock.Call
}

// SubscribeFilterLogs is a helper method to define mock.On call
//   - ctx context.Context
//   - q ethereum.FilterQuery
//   - ch chan<- types.Log
func (_e *MockETHClient_Expecter) SubscribeFilterLogs(ctx any, q any, ch any) *MockETHClient_SubscribeFilterLogs_Call {
	return &MockETHClient_SubscribeFilterLogs_Call{Call: _e.mock.On("SubscribeFilterLogs", ctx, q, ch)}
}

func (_c *MockETHClient_SubscribeFilterLogs_Call) Run(run func(ctx context.Context, q ethereum.FilterQuery, ch chan<- types.Log)) *MockETHClient_SubscribeFilterLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ethereum.FilterQuery
		if args[1] != nil {
			arg1 = args[1].(ethereum.FilterQuery)
		}
		var arg2 chan<- types.Log
		if args[2] != nil {
			arg2 = args[2].(chan<- types.Log)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockETHClient_SubscribeFilterLogs_Call) Return(subscription ethereum.Subscription, err error) *MockETHClient_SubscribeFilterLogs_Call {
	_c.Call.Return(subscription, err)
	return _c
}

func (_c *MockETHClient_SubscribeFilterLogs_Call) RunAndReturn(run func(ctx context.Context, q ethereum.FilterQuery, ch chan<- types.Log) (ethereum.Subscription, error)) *MockETHClient_SubscribeFilterLogs_Call {
	_c.Call.Return(run)
	return _c
}

// TransactionReceipt provides a mock function for the type MockETHClient
func (_mock *MockETHClient) TransactionReceipt(ctx context.Context, txHash common.Hash) (*types.Receipt, error) {
	ret := _mock.Called(ctx, txHash)

	if len(ret) == 0 {
		panic("no return value specified for TransactionReceipt")
	}

	var r0 *types.Receipt
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, common.Hash) (*types.Receipt, error)); ok {
		return returnFunc(ctx, txHash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, common.Hash) *types.Receipt); ok {
		r0 = returnFunc(ctx, txHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Receipt)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, common.Hash) error); ok {
		r1 = returnFunc(ctx, txHash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockETHClient_TransactionReceipt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TransactionReceipt'
type MockETHClient_TransactionReceipt_Call struct {
	*mock.Call
}

// TransactionReceipt is a helper method to define mock.On call
//   - ctx context.Context
//   - txHash common.Hash
func (_e *MockETHClient_Expecter) TransactionReceipt(ctx any, txHash any) *MockETHClient_TransactionReceipt_Call {
	return &MockETHClient_TransactionReceipt_Call{Call: _e.mock.On("TransactionReceipt", ctx, txHash)}
}

func (_c *MockETHClient_TransactionReceipt_Call) Run(run func(ctx context.Context, txHash common.Hash)) *MockETHClient_TransactionReceipt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 common.Hash
		if args[1] != nil {
			arg1 = args[1].(common.Hash)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockETHClient_TransactionReceipt_Call) Return(receipt *types.Receipt, err error) *MockETHClient_TransactionReceipt_Call {
	_c.Call.Return(receipt, err)
	return _c
}

func (_c *MockETHClient_TransactionReceipt_Call) RunAndReturn(run func(ctx context.Context, txHash common.Hash) (*types.Receipt, error)) *MockETHClient_TransactionReceipt_Call {
	_c.Call.Return(run)
	return _c
}
