// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package store

import (
	"context"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// CreatePacket provides a mock function for the type MockRepository
func (_mock *MockRepository) CreatePacket(ctx context.Context, packet Packet) error {
	ret := _mock.Called(ctx, packet)

	if len(ret) == 0 {
		panic("no return value specified for CreatePacket")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, Packet) error); ok {
		r0 = returnFunc(ctx, packet)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_CreatePacket_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePacket'
type MockRepository_CreatePacket_Call struct {
	*mock.Call
}

// CreatePacket is a helper method to define mock.On call
//   - ctx context.Context
//   - packet Packet
func (_e *MockRepository_Expecter) CreatePacket(ctx any, packet any) *MockRepository_CreatePacket_Call {
	return &MockRepository_CreatePacket_Call{Call: _e.mock.On("CreatePacket", ctx, packet)}
}

func (_c *MockRepository_CreatePacket_Call) Run(run func(ctx context.Context, packet Packet)) *MockRepository_CreatePacket_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 Packet
		if args[1] != nil {
			arg1 = args[1].(Packet)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_CreatePacket_Call) Return(err error) *MockRepository_CreatePacket_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_CreatePacket_Call) RunAndReturn(run func(ctx context.Context, packet Packet) error) *MockRepository_CreatePacket_Call {
	_c.Call.Return(run)
	return _c
}

// CreateRelayRequest provides a mock function for the type MockRepository
func (_mock *MockRepository) CreateRelayRequest(ctx context.Context, chainID string, txHash string) error {
	ret := _mock.Called(ctx, chainID, txHash)

	if len(ret) == 0 {
		panic("no return value specified for CreateRelayRequest")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, chainID, txHash)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_CreateRelayRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRelayRequest'
type MockRepository_CreateRelayRequest_Call struct {
	*mock.Call
}

// CreateRelayRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - chainID string
//   - txHash string
func (_e *MockRepository_Expecter) CreateRelayRequest(ctx any, chainID any, txHash any) *MockRepository_CreateRelayRequest_Call {
	return &MockRepository_CreateRelayRequest_Call{Call: _e.mock.On("CreateRelayRequest", ctx, chainID, txHash)}
}

func (_c *MockRepository_CreateRelayRequest_Call) Run(run func(ctx context.Context, chainID string, txHash string)) *MockRepository_CreateRelayRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_CreateRelayRequest_Call) Return(err error) *MockRepository_CreateRelayRequest_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_CreateRelayRequest_Call) RunAndReturn(run func(ctx context.Context, chainID string, txHash string) error) *MockRepository_CreateRelayRequest_Call {
	_c.Call.Return(run)
	return _c
}

// GetRelayRequest provides a mock function for the type MockRepository
func (_mock *MockRepository) GetRelayRequest(ctx context.Context, chainID string, txHash string) (*RelayRequest, error) {
	ret := _mock.Called(ctx, chainID, txHash)

	if len(ret) == 0 {
		panic("no return value specified for GetRelayRequest")
	}

	var r0 *RelayRequest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*RelayRequest, error)); ok {
		return returnFunc(ctx, chainID, txHash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *RelayRequest); ok {
		r0 = returnFunc(ctx, chainID, txHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*RelayRequest)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, chainID, txHash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetRelayRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRelayRequest'
type MockRepository_GetRelayRequest_Call struct {
	*mock.Call
}

// GetRelayRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - chainID string
//   - txHash string
func (_e *MockRepository_Expecter) GetRelayRequest(ctx any, chainID any, txHash any) *MockRepository_GetRelayRequest_Call {
	return &MockRepository_GetRelayRequest_Call{Call: _e.mock.On("GetRelayRequest", ctx, chainID, txHash)}
}

func (_c *MockRepository_GetRelayRequest_Call) Run(run func(ctx context.Context, chainID string, txHash string)) *MockRepository_GetRelayRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_GetRelayRequest_Call) Return(relayRequest *RelayRequest, err error) *MockRepository_GetRelayRequest_Call {
	_c.Call.Return(relayRequest, err)
	return _c
}

func (_c *MockRepository_GetRelayRequest_Call) RunAndReturn(run func(ctx context.Context, chainID string, txHash string) (*RelayRequest, error)) *MockRepository_GetRelayRequest_Call {
	_c.Call.Return(run)
	return _c
}

// ListPacketsBySourceTx provides a mock function for the type MockRepository
func (_mock *MockRepository) ListPacketsBySourceTx(ctx context.Context, chainID string, txHash string) ([]Packet, error) {
	ret := _mock.Called(ctx, chainID, txHash)

	if len(ret) == 0 {
		panic("no return value specified for ListPacketsBySourceTx")
	}

	var r0 []Packet
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]Packet, error)); ok {
		return returnFunc(ctx, chainID, txHash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []Packet); ok {
		r0 = returnFunc(ctx, chainID, txHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Packet)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, chainID, txHash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_ListPacketsBySourceTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPacketsBySourceTx'
type MockRepository_ListPacketsBySourceTx_Call struct {
	*mock.Call
}

// ListPacketsBySourceTx is a helper method to define mock.On call
//   - ctx context.Context
//   - chainID string
//   - txHash string
func (_e *MockRepository_Expecter) ListPacketsBySourceTx(ctx any, chainID any, txHash any) *MockRepository_ListPacketsBySourceTx_Call {
	return &MockRepository_ListPacketsBySourceTx_Call{Call: _e.mock.On("ListPacketsBySourceTx", ctx, chainID, txHash)}
}

func (_c *MockRepository_ListPacketsBySourceTx_Call) Run(run func(ctx context.Context, chainID string, txHash string)) *MockRepository_ListPacketsBySourceTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_ListPacketsBySourceTx_Call) Return(packets []Packet, err error) *MockRepository_ListPacketsBySourceTx_Call {
	_c.Call.Return(packets, err)
	return _c
}

func (_c *MockRepository_ListPacketsBySourceTx_Call) RunAndReturn(run func(ctx context.Context, chainID string, txHash string) ([]Packet, error)) *MockRepository_ListPacketsBySourceTx_Call {
	_c.Call.Return(run)
	return _c
}
