// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: relayer.sql

package sqlite

import (
	"context"
	"time"
)

const clearPacketAckTx = `-- name: ClearPacketAckTx :exec
UPDATE packets SET
    ack_tx_hash = NULL,
    ack_tx_time = NULL,
    ack_tx_relayer_address = NULL,
    updated_at = CURRENT_TIMESTAMP
WHERE source_chain_id = ?1
AND packet_source_client_id = ?2
AND packet_sequence_number = ?3
`

type ClearPacketAckTxParams struct {
	SourceChainID        string
	PacketSourceClientID string
	PacketSequenceNumber int64
}

func (q *Queries) ClearPacketAckTx(ctx context.Context, arg ClearPacketAckTxParams) error {
	_, err := q.db.ExecContext(ctx, clearPacketAckTx, arg.SourceChainID, arg.PacketSourceClientID, arg.PacketSequenceNumber)
	return err
}

const clearPacketRecvTx = `-- name: ClearPacketRecvTx :exec
UPDATE packets SET
    recv_tx_hash = NULL,
    recv_tx_time = NULL,
    recv_tx_relayer_address = NULL,
    updated_at = CURRENT_TIMESTAMP
WHERE source_chain_id = ?1
AND packet_source_client_id = ?2
AND packet_sequence_number = ?3
`

type ClearPacketRecvTxParams struct {
	SourceChainID        string
	PacketSourceClientID string
	PacketSequenceNumber int64
}

func (q *Queries) ClearPacketRecvTx(ctx context.Context, arg ClearPacketRecvTxParams) error {
	_, err := q.db.ExecContext(ctx, clearPacketRecvTx, arg.SourceChainID, arg.PacketSourceClientID, arg.PacketSequenceNumber)
	return err
}

const clearPacketTimeoutTx = `-- name: ClearPacketTimeoutTx :exec
UPDATE packets SET
    timeout_tx_hash = NULL,
    timeout_tx_time = NULL,
    timeout_tx_relayer_address = NULL,
    updated_at = CURRENT_TIMESTAMP
WHERE source_chain_id = ?1
AND packet_source_client_id = ?2
AND packet_sequence_number = ?3
`

type ClearPacketTimeoutTxParams struct {
	SourceChainID        string
	PacketSourceClientID string
	PacketSequenceNumber int64
}

func (q *Queries) ClearPacketTimeoutTx(ctx context.Context, arg ClearPacketTimeoutTxParams) error {
	_, err := q.db.ExecContext(ctx, clearPacketTimeoutTx, arg.SourceChainID, arg.PacketSourceClientID, arg.PacketSequenceNumber)
	return err
}

const createUnresolvedSequence = `-- name: CreateUnresolvedSequence :exec
INSERT INTO packet_clearing_unresolved (
    source_chain_id,
    packet_source_client_id,
    packet_sequence_number
) VALUES (
    ?1,
    ?2,
    ?3
)
ON CONFLICT (source_chain_id, packet_source_client_id, packet_sequence_number) DO NOTHING
`

type CreateUnresolvedSequenceParams struct {
	ChainID  string
	ClientID string
	Sequence int64
}

// a sequence that is still unresolved keeps the first_seen_at it was first recorded with,
// since how long it has been stuck is the only signal an operator gets about it
func (q *Queries) CreateUnresolvedSequence(ctx context.Context, arg CreateUnresolvedSequenceParams) error {
	_, err := q.db.ExecContext(ctx, createUnresolvedSequence, arg.ChainID, arg.ClientID, arg.Sequence)
	return err
}

const deleteUnresolvedSequence = `-- name: DeleteUnresolvedSequence :exec
DELETE FROM packet_clearing_unresolved
WHERE source_chain_id = ?1
  AND packet_source_client_id = ?2
  AND packet_sequence_number = ?3
`

type DeleteUnresolvedSequenceParams struct {
	ChainID  string
	ClientID string
	Sequence int64
}

func (q *Queries) DeleteUnresolvedSequence(ctx context.Context, arg DeleteUnresolvedSequenceParams) error {
	_, err := q.db.ExecContext(ctx, deleteUnresolvedSequence, arg.ChainID, arg.ClientID, arg.Sequence)
	return err
}

const getClearingState = `-- name: GetClearingState :one
SELECT last_probed_sequence FROM packet_clearing_state
WHERE source_chain_id = ?1 AND packet_source_client_id = ?2
`

func (q *Queries) GetClearingState(ctx context.Context, chainID string, clientID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getClearingState, chainID, clientID)
	var last_probed_sequence int64
	err := row.Scan(&last_probed_sequence)
	return last_probed_sequence, err
}

const listDispatchablePackets = `-- name: ListDispatchablePackets :many
SELECT id, created_at, updated_at, status, source_chain_id, destination_chain_id, source_tx_hash, source_tx_time, packet_sequence_number, packet_source_client_id, packet_destination_client_id, packet_timeout_timestamp, recv_tx_hash, recv_tx_time, recv_tx_relayer_address, write_ack_tx_hash, write_ack_tx_time, write_ack_status, ack_tx_hash, ack_tx_time, ack_tx_relayer_address, timeout_tx_hash, timeout_tx_time, timeout_tx_relayer_address FROM packets
WHERE status NOT IN (
    'NOT_SELECTED',
    'COMPLETE_WITH_ACK',
    'COMPLETE_WITH_TIMEOUT',
    'COMPLETE_WITH_WRITE_ACK_ERROR',
    'FAILED'
)
ORDER BY id
`

func (q *Queries) ListDispatchablePackets(ctx context.Context) ([]Packet, error) {
	rows, err := q.db.QueryContext(ctx, listDispatchablePackets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Packet
	for rows.Next() {
		var i Packet
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Status,
			&i.SourceChainID,
			&i.DestinationChainID,
			&i.SourceTxHash,
			&i.SourceTxTime,
			&i.PacketSequenceNumber,
			&i.PacketSourceClientID,
			&i.PacketDestinationClientID,
			&i.PacketTimeoutTimestamp,
			&i.RecvTxHash,
			&i.RecvTxTime,
			&i.RecvTxRelayerAddress,
			&i.WriteAckTxHash,
			&i.WriteAckTxTime,
			&i.WriteAckStatus,
			&i.AckTxHash,
			&i.AckTxTime,
			&i.AckTxRelayerAddress,
			&i.TimeoutTxHash,
			&i.TimeoutTxTime,
			&i.TimeoutTxRelayerAddress,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPacketSequencesFrom = `-- name: ListPacketSequencesFrom :many
SELECT packet_sequence_number FROM packets
WHERE source_chain_id = ?1
  AND packet_source_client_id = ?2
  AND packet_sequence_number >= ?3
ORDER BY packet_sequence_number
`

type ListPacketSequencesFromParams struct {
	ChainID      string
	ClientID     string
	FromSequence int64
}

// clearing skips a sequence we hold a row for in ANY state, including NOT_SELECTED,
// so this filters on no status
func (q *Queries) ListPacketSequencesFrom(ctx context.Context, arg ListPacketSequencesFromParams) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listPacketSequencesFrom, arg.ChainID, arg.ClientID, arg.FromSequence)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var packet_sequence_number int64
		if err := rows.Scan(&packet_sequence_number); err != nil {
			return nil, err
		}
		items = append(items, packet_sequence_number)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPackets = `-- name: ListPackets :many
SELECT id, created_at, updated_at, status, source_chain_id, destination_chain_id, source_tx_hash, source_tx_time, packet_sequence_number, packet_source_client_id, packet_destination_client_id, packet_timeout_timestamp, recv_tx_hash, recv_tx_time, recv_tx_relayer_address, write_ack_tx_hash, write_ack_tx_time, write_ack_status, ack_tx_hash, ack_tx_time, ack_tx_relayer_address, timeout_tx_hash, timeout_tx_time, timeout_tx_relayer_address FROM packets
WHERE ',' || ?1 || ',' LIKE '%,' || status || ',%'
AND (source_chain_id = ?2 OR ?2 = '')
AND (destination_chain_id = ?3 OR ?3 = '')
AND (packet_source_client_id = ?4 OR ?4 = '')
AND (packet_destination_client_id = ?5 OR ?5 = '')
AND (source_tx_hash = ?6 OR ?6 = '')
AND (packet_sequence_number = ?7 OR ?7 = 0)
AND id < ?8
ORDER BY id DESC
LIMIT ?9
`

type ListPacketsParams struct {
	Statuses            *string
	SourceChainID       string
	DestinationChainID  string
	SourceClientID      string
	DestinationClientID string
	SourceTxHash        string
	SequenceNumber      int64
	Before              int64
	RowLimit            int64
}

func (q *Queries) ListPackets(ctx context.Context, arg ListPacketsParams) ([]Packet, error) {
	rows, err := q.db.QueryContext(ctx, listPackets,
		arg.Statuses,
		arg.SourceChainID,
		arg.DestinationChainID,
		arg.SourceClientID,
		arg.DestinationClientID,
		arg.SourceTxHash,
		arg.SequenceNumber,
		arg.Before,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Packet
	for rows.Next() {
		var i Packet
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Status,
			&i.SourceChainID,
			&i.DestinationChainID,
			&i.SourceTxHash,
			&i.SourceTxTime,
			&i.PacketSequenceNumber,
			&i.PacketSourceClientID,
			&i.PacketDestinationClientID,
			&i.PacketTimeoutTimestamp,
			&i.RecvTxHash,
			&i.RecvTxTime,
			&i.RecvTxRelayerAddress,
			&i.WriteAckTxHash,
			&i.WriteAckTxTime,
			&i.WriteAckStatus,
			&i.AckTxHash,
			&i.AckTxTime,
			&i.AckTxRelayerAddress,
			&i.TimeoutTxHash,
			&i.TimeoutTxTime,
			&i.TimeoutTxRelayerAddress,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPacketsBySourceTx = `-- name: ListPacketsBySourceTx :many
SELECT id, created_at, updated_at, status, source_chain_id, destination_chain_id, source_tx_hash, source_tx_time, packet_sequence_number, packet_source_client_id, packet_destination_client_id, packet_timeout_timestamp, recv_tx_hash, recv_tx_time, recv_tx_relayer_address, write_ack_tx_hash, write_ack_tx_time, write_ack_status, ack_tx_hash, ack_tx_time, ack_tx_relayer_address, timeout_tx_hash, timeout_tx_time, timeout_tx_relayer_address FROM packets
WHERE source_chain_id = ?1
AND source_tx_hash = ?2
ORDER BY packet_sequence_number
`

func (q *Queries) ListPacketsBySourceTx(ctx context.Context, chainID string, txHash string) ([]Packet, error) {
	rows, err := q.db.QueryContext(ctx, listPacketsBySourceTx, chainID, txHash)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Packet
	for rows.Next() {
		var i Packet
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Status,
			&i.SourceChainID,
			&i.DestinationChainID,
			&i.SourceTxHash,
			&i.SourceTxTime,
			&i.PacketSequenceNumber,
			&i.PacketSourceClientID,
			&i.PacketDestinationClientID,
			&i.PacketTimeoutTimestamp,
			&i.RecvTxHash,
			&i.RecvTxTime,
			&i.RecvTxRelayerAddress,
			&i.WriteAckTxHash,
			&i.WriteAckTxTime,
			&i.WriteAckStatus,
			&i.AckTxHash,
			&i.AckTxTime,
			&i.AckTxRelayerAddress,
			&i.TimeoutTxHash,
			&i.TimeoutTxTime,
			&i.TimeoutTxRelayerAddress,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnresolvedSequences = `-- name: ListUnresolvedSequences :many
SELECT packet_sequence_number FROM packet_clearing_unresolved
WHERE source_chain_id = ?1 AND packet_source_client_id = ?2
ORDER BY packet_sequence_number
`

func (q *Queries) ListUnresolvedSequences(ctx context.Context, chainID string, clientID string) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listUnresolvedSequences, chainID, clientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var packet_sequence_number int64
		if err := rows.Scan(&packet_sequence_number); err != nil {
			return nil, err
		}
		items = append(items, packet_sequence_number)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxPacketSequence = `-- name: MaxPacketSequence :one
SELECT CAST(COALESCE(MAX(packet_sequence_number), 0) AS bigint) FROM packets
WHERE source_chain_id = ?1 AND packet_source_client_id = ?2
`

// the CAST is load-bearing: without it sqlc types the COALESCE as interface{} on sqlite
func (q *Queries) MaxPacketSequence(ctx context.Context, chainID string, clientID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, maxPacketSequence, chainID, clientID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const setClearingState = `-- name: SetClearingState :exec
INSERT INTO packet_clearing_state (
    source_chain_id,
    packet_source_client_id,
    last_probed_sequence
) VALUES (
    ?1,
    ?2,
    ?3
)
ON CONFLICT (source_chain_id, packet_source_client_id) DO UPDATE SET
    last_probed_sequence = excluded.last_probed_sequence,
    updated_at           = CURRENT_TIMESTAMP
WHERE excluded.last_probed_sequence > packet_clearing_state.last_probed_sequence
`

type SetClearingStateParams struct {
	ChainID            string
	ClientID           string
	LastProbedSequence int64
}

// the watermark only moves forward, so a slow pass cannot drag it back over sequences
// another instance already probed, and a storage read gone bad cannot force a full rescan
func (q *Queries) SetClearingState(ctx context.Context, arg SetClearingStateParams) error {
	_, err := q.db.ExecContext(ctx, setClearingState, arg.ChainID, arg.ClientID, arg.LastProbedSequence)
	return err
}

const updatePacketAckTx = `-- name: UpdatePacketAckTx :exec
UPDATE packets SET
    ack_tx_hash = ?1,
    ack_tx_time = ?2,
    ack_tx_relayer_address = ?3,
    updated_at = CURRENT_TIMESTAMP
WHERE source_chain_id = ?4
AND packet_source_client_id = ?5
AND packet_sequence_number = ?6
`

type UpdatePacketAckTxParams struct {
	AckTxHash            *string
	AckTxTime            *time.Time
	AckTxRelayerAddress  *string
	SourceChainID        string
	PacketSourceClientID string
	PacketSequenceNumber int64
}

func (q *Queries) UpdatePacketAckTx(ctx context.Context, arg UpdatePacketAckTxParams) error {
	_, err := q.db.ExecContext(ctx, updatePacketAckTx,
		arg.AckTxHash,
		arg.AckTxTime,
		arg.AckTxRelayerAddress,
		arg.SourceChainID,
		arg.PacketSourceClientID,
		arg.PacketSequenceNumber,
	)
	return err
}

const updatePacketRecvTx = `-- name: UpdatePacketRecvTx :exec
UPDATE packets SET
    recv_tx_hash = ?1,
    recv_tx_time = ?2,
    recv_tx_relayer_address = ?3,
    updated_at = CURRENT_TIMESTAMP
WHERE source_chain_id = ?4
AND packet_source_client_id = ?5
AND packet_sequence_number = ?6
`

type UpdatePacketRecvTxParams struct {
	RecvTxHash           *string
	RecvTxTime           *time.Time
	RecvTxRelayerAddress *string
	SourceChainID        string
	PacketSourceClientID string
	PacketSequenceNumber int64
}

func (q *Queries) UpdatePacketRecvTx(ctx context.Context, arg UpdatePacketRecvTxParams) error {
	_, err := q.db.ExecContext(ctx, updatePacketRecvTx,
		arg.RecvTxHash,
		arg.RecvTxTime,
		arg.RecvTxRelayerAddress,
		arg.SourceChainID,
		arg.PacketSourceClientID,
		arg.PacketSequenceNumber,
	)
	return err
}

const updatePacketStatus = `-- name: UpdatePacketStatus :exec
UPDATE packets SET
    status = ?1,
    updated_at = CURRENT_TIMESTAMP
WHERE source_chain_id = ?2
AND packet_source_client_id = ?3
AND packet_sequence_number = ?4
`

type UpdatePacketStatusParams struct {
	Status               string
	SourceChainID        string
	PacketSourceClientID string
	PacketSequenceNumber int64
}

func (q *Queries) UpdatePacketStatus(ctx context.Context, arg UpdatePacketStatusParams) error {
	_, err := q.db.ExecContext(ctx, updatePacketStatus,
		arg.Status,
		arg.SourceChainID,
		arg.PacketSourceClientID,
		arg.PacketSequenceNumber,
	)
	return err
}

const updatePacketTimeoutTx = `-- name: UpdatePacketTimeoutTx :exec
UPDATE packets SET
    timeout_tx_hash = ?1,
    timeout_tx_time = ?2,
    timeout_tx_relayer_address = ?3,
    updated_at = CURRENT_TIMESTAMP
WHERE source_chain_id = ?4
AND packet_source_client_id = ?5
AND packet_sequence_number = ?6
`

type UpdatePacketTimeoutTxParams struct {
	TimeoutTxHash           *string
	TimeoutTxTime           *time.Time
	TimeoutTxRelayerAddress *string
	SourceChainID           string
	PacketSourceClientID    string
	PacketSequenceNumber    int64
}

func (q *Queries) UpdatePacketTimeoutTx(ctx context.Context, arg UpdatePacketTimeoutTxParams) error {
	_, err := q.db.ExecContext(ctx, updatePacketTimeoutTx,
		arg.TimeoutTxHash,
		arg.TimeoutTxTime,
		arg.TimeoutTxRelayerAddress,
		arg.SourceChainID,
		arg.PacketSourceClientID,
		arg.PacketSequenceNumber,
	)
	return err
}

const updatePacketWriteAck = `-- name: UpdatePacketWriteAck :exec
UPDATE packets SET
    write_ack_tx_hash = ?1,
    write_ack_tx_time = ?2,
    write_ack_status = ?3,
    updated_at = CURRENT_TIMESTAMP
WHERE source_chain_id = ?4
AND packet_source_client_id = ?5
AND packet_sequence_number = ?6
`

type UpdatePacketWriteAckParams struct {
	WriteAckTxHash       *string
	WriteAckTxTime       *time.Time
	WriteAckStatus       *string
	SourceChainID        string
	PacketSourceClientID string
	PacketSequenceNumber int64
}

func (q *Queries) UpdatePacketWriteAck(ctx context.Context, arg UpdatePacketWriteAckParams) error {
	_, err := q.db.ExecContext(ctx, updatePacketWriteAck,
		arg.WriteAckTxHash,
		arg.WriteAckTxTime,
		arg.WriteAckStatus,
		arg.SourceChainID,
		arg.PacketSourceClientID,
		arg.PacketSequenceNumber,
	)
	return err
}

const upsertPacket = `-- name: UpsertPacket :exec
/*
 * SPDX-License-Identifier: Apache-2.0
 */

INSERT INTO packets (
    status,
    source_chain_id,
    destination_chain_id,
    source_tx_hash,
    source_tx_time,
    packet_sequence_number,
    packet_source_client_id,
    packet_destination_client_id,
    packet_timeout_timestamp
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7,
    ?8,
    ?9
)
ON CONFLICT (source_chain_id, packet_sequence_number, packet_source_client_id) DO UPDATE SET
    status = EXCLUDED.status,
    destination_chain_id = EXCLUDED.destination_chain_id,
    source_tx_hash = EXCLUDED.source_tx_hash,
    source_tx_time = EXCLUDED.source_tx_time,
    packet_destination_client_id = EXCLUDED.packet_destination_client_id,
    packet_timeout_timestamp = EXCLUDED.packet_timeout_timestamp,
    updated_at = CURRENT_TIMESTAMP
WHERE packets.status = 'NOT_SELECTED'
AND EXCLUDED.status IN ('NOT_SELECTED', 'PENDING')
`

type UpsertPacketParams struct {
	Status                    string
	SourceChainID             string
	DestinationChainID        string
	SourceTxHash              string
	SourceTxTime              time.Time
	PacketSequenceNumber      int64
	PacketSourceClientID      string
	PacketDestinationClientID string
	PacketTimeoutTimestamp    time.Time
}

func (q *Queries) UpsertPacket(ctx context.Context, arg UpsertPacketParams) error {
	_, err := q.db.ExecContext(ctx, upsertPacket,
		arg.Status,
		arg.SourceChainID,
		arg.DestinationChainID,
		arg.SourceTxHash,
		arg.SourceTxTime,
		arg.PacketSequenceNumber,
		arg.PacketSourceClientID,
		arg.PacketDestinationClientID,
		arg.PacketTimeoutTimestamp,
	)
	return err
}
