// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package txbuilder

import (
	"github.com/cosmos/ibc/link/internal/types/v2"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTxBuilder creates a new instance of MockTxBuilder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTxBuilder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTxBuilder {
	mock := &MockTxBuilder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTxBuilder is an autogenerated mock type for the TxBuilder type
type MockTxBuilder struct {
	mock.Mock
}

type MockTxBuilder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTxBuilder) EXPECT() *MockTxBuilder_Expecter {
	return &MockTxBuilder_Expecter{mock: &_m.Mock}
}

// BuildRelayTxs provides a mock function for the type MockTxBuilder
func (_mock *MockTxBuilder) BuildRelayTxs(clientUpdate v2.ClientUpdate, packetRelayItems []v2.PacketRelayItem) ([]v2.RelayTx, error) {
	ret := _mock.Called(clientUpdate, packetRelayItems)

	if len(ret) == 0 {
		panic("no return value specified for BuildRelayTxs")
	}

	var r0 []v2.RelayTx
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(v2.ClientUpdate, []v2.PacketRelayItem) ([]v2.RelayTx, error)); ok {
		return returnFunc(clientUpdate, packetRelayItems)
	}
	if returnFunc, ok := ret.Get(0).(func(v2.ClientUpdate, []v2.PacketRelayItem) []v2.RelayTx); ok {
		r0 = returnFunc(clientUpdate, packetRelayItems)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]v2.RelayTx)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(v2.ClientUpdate, []v2.PacketRelayItem) error); ok {
		r1 = returnFunc(clientUpdate, packetRelayItems)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTxBuilder_BuildRelayTxs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BuildRelayTxs'
type MockTxBuilder_BuildRelayTxs_Call struct {
	*mock.Call
}

// BuildRelayTxs is a helper method to define mock.On call
//   - clientUpdate v2.ClientUpdate
//   - packetRelayItems []v2.PacketRelayItem
func (_e *MockTxBuilder_Expecter) BuildRelayTxs(clientUpdate any, packetRelayItems any) *MockTxBuilder_BuildRelayTxs_Call {
	return &MockTxBuilder_BuildRelayTxs_Call{Call: _e.mock.On("BuildRelayTxs", clientUpdate, packetRelayItems)}
}

func (_c *MockTxBuilder_BuildRelayTxs_Call) Run(run func(clientUpdate v2.ClientUpdate, packetRelayItems []v2.PacketRelayItem)) *MockTxBuilder_BuildRelayTxs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 v2.ClientUpdate
		if args[0] != nil {
			arg0 = args[0].(v2.ClientUpdate)
		}
		var arg1 []v2.PacketRelayItem
		if args[1] != nil {
			arg1 = args[1].([]v2.PacketRelayItem)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTxBuilder_BuildRelayTxs_Call) Return(relayTxs []v2.RelayTx, err error) *MockTxBuilder_BuildRelayTxs_Call {
	_c.Call.Return(relayTxs, err)
	return _c
}

func (_c *MockTxBuilder_BuildRelayTxs_Call) RunAndReturn(run func(clientUpdate v2.ClientUpdate, packetRelayItems []v2.PacketRelayItem) ([]v2.RelayTx, error)) *MockTxBuilder_BuildRelayTxs_Call {
	_c.Call.Return(run)
	return _c
}
