// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: relayer.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPacket = `-- name: CreatePacket :execrows
INSERT INTO packets (
    status,
    source_chain_id,
    destination_chain_id,
    source_tx_hash,
    source_tx_time,
    packet_sequence_number,
    packet_source_client_id,
    packet_destination_client_id,
    packet_timeout_timestamp
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
)
ON CONFLICT (source_chain_id, packet_sequence_number, packet_source_client_id) DO NOTHING
`

type CreatePacketParams struct {
	Status                    string
	SourceChainID             string
	DestinationChainID        string
	SourceTxHash              string
	SourceTxTime              pgtype.Timestamptz
	PacketSequenceNumber      int64
	PacketSourceClientID      string
	PacketDestinationClientID string
	PacketTimeoutTimestamp    pgtype.Timestamptz
}

func (q *Queries) CreatePacket(ctx context.Context, arg CreatePacketParams) (int64, error) {
	result, err := q.db.Exec(ctx, createPacket,
		arg.Status,
		arg.SourceChainID,
		arg.DestinationChainID,
		arg.SourceTxHash,
		arg.SourceTxTime,
		arg.PacketSequenceNumber,
		arg.PacketSourceClientID,
		arg.PacketDestinationClientID,
		arg.PacketTimeoutTimestamp,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createRelayRequest = `-- name: CreateRelayRequest :exec
INSERT INTO relay_requests (source_chain_id, source_tx_hash)
VALUES ($1, $2)
ON CONFLICT (source_chain_id, source_tx_hash) DO NOTHING
`

func (q *Queries) CreateRelayRequest(ctx context.Context, chainID string, txHash string) error {
	_, err := q.db.Exec(ctx, createRelayRequest, chainID, txHash)
	return err
}

const getRelayRequest = `-- name: GetRelayRequest :one
SELECT id, source_chain_id, source_tx_hash, created_at FROM relay_requests
WHERE source_chain_id = $1
AND source_tx_hash = $2
`

func (q *Queries) GetRelayRequest(ctx context.Context, chainID string, txHash string) (RelayRequest, error) {
	row := q.db.QueryRow(ctx, getRelayRequest, chainID, txHash)
	var i RelayRequest
	err := row.Scan(
		&i.ID,
		&i.SourceChainID,
		&i.SourceTxHash,
		&i.CreatedAt,
	)
	return i, err
}

const listPacketsBySourceTx = `-- name: ListPacketsBySourceTx :many
SELECT id, created_at, updated_at, status, source_chain_id, destination_chain_id, source_tx_hash, source_tx_time, packet_sequence_number, packet_source_client_id, packet_destination_client_id, packet_timeout_timestamp, recv_tx_hash, recv_tx_time, recv_tx_relayer_address, write_ack_tx_hash, write_ack_tx_time, write_ack_status, ack_tx_hash, ack_tx_time, ack_tx_relayer_address, timeout_tx_hash, timeout_tx_time, timeout_tx_relayer_address FROM packets
WHERE source_chain_id = $1
AND source_tx_hash = $2
ORDER BY packet_sequence_number
`

func (q *Queries) ListPacketsBySourceTx(ctx context.Context, chainID string, txHash string) ([]Packet, error) {
	rows, err := q.db.Query(ctx, listPacketsBySourceTx, chainID, txHash)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Packet
	for rows.Next() {
		var i Packet
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Status,
			&i.SourceChainID,
			&i.DestinationChainID,
			&i.SourceTxHash,
			&i.SourceTxTime,
			&i.PacketSequenceNumber,
			&i.PacketSourceClientID,
			&i.PacketDestinationClientID,
			&i.PacketTimeoutTimestamp,
			&i.RecvTxHash,
			&i.RecvTxTime,
			&i.RecvTxRelayerAddress,
			&i.WriteAckTxHash,
			&i.WriteAckTxTime,
			&i.WriteAckStatus,
			&i.AckTxHash,
			&i.AckTxTime,
			&i.AckTxRelayerAddress,
			&i.TimeoutTxHash,
			&i.TimeoutTxTime,
			&i.TimeoutTxRelayerAddress,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
