#!/usr/bin/env bash

# SPDX-License-Identifier: Apache-2.0

# The IBC half of the example: kms keys, `ibc deploy core`, and the two
# standalone attestors.
#
# DEMO KEYS ONLY — every key here comes from a public BIP-39 test vector and is
# written to disk unencrypted. See the banner in setup.sh.
#
# The topology this sets up:
#
#     besu-a ◀─ watches ─ attestor-41001 ─┐
#     besu-b ◀─ watches ─ attestor-41002 ─┴─ Sign (gRPC) ─▶ kms
#
# Each attestor is a standalone external process with its own container and its
# own config, and neither holds a signing key: both are configured with a
# `type: remote` signer pointing at kms, which holds both keys and serves them
# over its SignerService.

KMS_KEYS_DIR="$LOCAL_DIR/kms/keys"
IBC_ENV_FILE="$LOCAL_DIR/ibc.env"
DEPLOY_DIR="$LOCAL_DIR/deploy"

IBC_SERVICES=(kms attestor-41001 attestor-41002)

# `ibc deploy` writes into host-owned bind mounts, and the compose default of
# 65532 cannot on Linux.
export DEPLOY_UID="${DEPLOY_UID:-$(id -u)}"
export DEPLOY_GID="${DEPLOY_GID:-$(id -g)}"

# _attestor_id <name> — the attestor naming convention, attestor-<chain id>.
# Used for the kms key id, the key file, the compose service, and the
# attestors[].name inside the container's config. They all have to agree: a
# relayer sends that name in every query and the process serves its attestors
# by name.
_attestor_id() { printf 'attestor-%s' "$(_chain_attr "$1" CHAIN_ID)"; }

_lc() { printf '%s' "$1" | tr 'A-Z' 'a-z'; }

# --progress quiet: this runs several times and would otherwise reprint the
# "Container besu-a Waiting / Healthy" block each time. Images are pulled by
# check_prerequisites, so nothing slow is being hidden.
_ibc() {
  docker compose --progress quiet run --rm -T deployer "$@" --home /home/ibc
}

# _steps <ibc-deploy-stdout> — one indented line per step in place of the raw
# JSON `ibc deploy` prints. "executed" on a first run, "skipped" on a re-run,
# which is the idempotency of the deploy path made visible.
_steps() {
  printf '%s' "$1" | perl -0777 -ne \
    'print "    $1: $2\n" while /"name"\s*:\s*"([^"]+)"\s*,\s*"action"\s*:\s*"([^"]+)"/gs'
}

# _key <chain> <role> — "<privkey-without-0x> <address>" for that chain's key.
_key() {
  local index account
  index=$(_chain_attr "$1" "${2}_INDEX")
  [[ "$index" =~ ^[0-9]+$ ]] \
    || die "${1}_${2}_INDEX must be a non-negative integer, got '$index'"
  account=$(derive_account "$(_chain_mnemonic "$1")" "$index") \
    || die "could not derive chain $1's $(_lc "$2") key at index $index — check ${1}_MNEMONIC"
  printf '%s' "$account"
}

_addr() {
  local pk addr
  read -r pk addr <<<"$(_key "$1" "$2")"
  printf '%s' "$addr"
}

# Derive the attestor keys into the files kms serves.
#
# Mode 0644, unlike the 0600 Besu validator keys, because the kms image runs
# unprivileged (uid 10001) and could not otherwise read them through the bind
# mount on Linux. The directories need 755 for the same reason.
init_kms_keys() {
  mkdir -p "$KMS_KEYS_DIR"
  chmod 755 "$LOCAL_DIR/kms" "$KMS_KEYS_DIR"

  local name pk addr file
  for name in "${CHAINS[@]}"; do
    read -r pk addr <<<"$(_key "$name" ATTESTOR)"
    file="$KMS_KEYS_DIR/$(_attestor_id "$name").hex"
    printf '%s\n' "$pk" > "$file"
    chmod 644 "$file"
  done

  print_attestor_keys
}

# The attestor addresses, printed because nothing else surfaces them: a kms-held
# key has no address the CLI can derive offline, and `ibc deploy client
# --attestors <alias>` fails on a remote signer with "cannot derive an address
# for remote signer". These are the values to pass to `--attestors` when
# registering a light client against these attestors.
print_attestor_keys() {
  local name index
  log "kms keys (served on kms:9090, referenced by remoteKeyId in config/attestor-*.yml):"
  for name in "${CHAINS[@]}"; do
    index=$(_chain_attr "$name" ATTESTOR_INDEX)
    log "  $(_attestor_id "$name")  $(_addr "$name" ATTESTOR)  (${name}_MNEMONIC index $index)"
  done
  log "Pass those addresses to 'ibc deploy client --attestors' — a client on one"
  log "chain authorizes the *counterparty's* attestor, since it verifies that chain."
}

_write_ibc_env() {
  cat > "$IBC_ENV_FILE" <<EOF
# Generated by ./setup.sh — do not edit, do not commit.
A_ICS26_ROUTER=$1
B_ICS26_ROUTER=$2
EOF
  chmod 644 "$IBC_ENV_FILE"
}

# _router <chain-id> — the router address out of that chain's deploy manifest.
_router() {
  local file router
  file="$DEPLOY_DIR/deployments/$1.json"
  router=$(perl -0777 -ne 'print $1 if /"router"\s*:\s*"([^"]+)"/' "$file" 2>/dev/null)
  [[ -n "$router" ]] || die "no router address in $file — did 'ibc deploy core' run?"
  printf '%s' "$router"
}

# `ibc deploy core` on both chains, then record the router addresses.
#
# The attestors need those addresses: config validation treats ics26Router as
# optional, but the process will not start without one. `ibc deploy core` does
# not write it back into any config, so it is read out of the manifest here and
# passed to the containers through ibc.env.
deploy_core() {
  mkdir -p "$DEPLOY_DIR/keys" "$DEPLOY_DIR/deployments"

  local name pk addr out
  for name in "${CHAINS[@]}"; do
    if [[ ! -f "$DEPLOY_DIR/keys/deployer-$(_lc "$name").json" ]]; then
      read -r pk addr <<<"$(_key "$name" DEPLOYER)"
      _ibc keys import ecdsa "deployer-$(_lc "$name")" --private-key "0x$pk" >/dev/null \
        || die "[$name] importing the deployer key failed"
      log "[$name] imported deployer-$(_lc "$name") ($addr)"
    fi
  done

  for name in "${CHAINS[@]}"; do
    log "[$name] deploying the core IBC routing stack..."
    out=$(_ibc deploy core --chain "$(_chain_attr "$name" CHAIN_ID)" --yes) \
      || die "[$name] 'ibc deploy core' failed"
    _steps "$out"
  done

  # Via locals, not inline `$(...)`: `die` inside a command substitution only
  # exits the subshell, and errexit ignores a failed substitution in argument
  # position — inline, a missing router would print the error and then write an
  # empty address into ibc.env.
  local a_router b_router
  a_router=$(_router "$A_CHAIN_ID") || exit 1
  b_router=$(_router "$B_CHAIN_ID") || exit 1
  _write_ibc_env "$a_router" "$b_router"
  log "Wrote the router addresses into $IBC_ENV_FILE:"
  grep -v '^#' "$IBC_ENV_FILE" | while read -r line; do log "  $line"; done
}

# Pull the ibc and kms images up front, with docker's progress bars. Every
# later compose call is --progress quiet, where a first-run pull of these two
# would look like a hang. COMPOSE_PROFILES reaches `deployer`, which is
# otherwise skipped as an inactive profile.
pull_ibc_images() {
  local img missing=()
  while read -r img; do
    docker image inspect "$img" >/dev/null 2>&1 || missing+=("$img")
  done < <(COMPOSE_PROFILES=tools docker compose config --images \
             "${IBC_SERVICES[@]}" deployer | sort -u)

  (( ${#missing[@]} )) || return 0
  log "Pulling ${#missing[@]} image(s), first run only:"
  printf '             %s\n' "${missing[@]}"
  COMPOSE_PROFILES=tools docker compose pull --policy missing \
    "${IBC_SERVICES[@]}" deployer \
    || die "could not pull the ibc and kms images — check network access"
}

start_attestors() {
  local key
  for key in A_ICS26_ROUTER B_ICS26_ROUTER; do
    grep -qE "^$key=.+" "$IBC_ENV_FILE" 2>/dev/null \
      || die "$IBC_ENV_FILE has no $key — the deploy phase did not complete"
  done

  log "Bringing up ${IBC_SERVICES[*]}..."
  docker compose --progress quiet up -d --wait "${IBC_SERVICES[@]}" \
    || die "the IBC services did not come up healthy" \
           "— check 'docker compose logs ${IBC_SERVICES[*]}'"
}

# Ask each attestor what it is. This is the end-to-end check for everything
# above: `attestor info` only answers if the process resolved its config,
# reached its chain, and fetched its key from kms over gRPC.
print_attestor_status() {
  local name id out
  log "Attestors:"
  for name in "${CHAINS[@]}"; do
    id=$(_attestor_id "$name")
    out=$(docker compose --progress quiet exec -T "$id" \
            /opt/ibc attestor info "$id" --home /home/ibc 2>/dev/null) \
      || die "'attestor info' failed against $id — check 'docker compose logs $id'"
    log "  $id  $(printf '%s' "$out" | perl -0777 -ne 'print $1 if /"address"\s*:\s*"([^"]+)"/')" \
        "(chain $(_chain_attr "$name" CHAIN_ID), signing through kms)"
  done
}
