#!/usr/bin/env bash

# SPDX-License-Identifier: Apache-2.0

# IBC Link: kms keys, deployment, and service bring-up.
#
KMS_KEYS_DIR="$LOCAL_DIR/kms/keys"
LINK_ENV_FILE="$LOCAL_DIR/link.env"
DEPLOY_DIR="$LOCAL_DIR/deploy"

LINK_SERVICES=(kms attestor-a attestor-b relayer)
LINK_CLIENT_ID="link-$A_CHAIN_ID-$B_CHAIN_ID"

export DEPLOY_UID="${DEPLOY_UID:-$(id -u)}"
export DEPLOY_GID="${DEPLOY_GID:-$(id -g)}"

_lc()    { printf '%s' "$1" | tr 'A-Z' 'a-z'; }
_other() { [[ "$1" == "A" ]] && printf 'B' || printf 'A'; }

_key() {
  local index account
  index=$(_chain_attr "$1" "${2}_INDEX")
  [[ "$index" =~ ^[0-9]+$ ]] \
    || die "${1}_${2}_INDEX must be a non-negative integer, got '$index'"
  account=$(derive_account "$(_chain_mnemonic "$1")" "$index") \
    || die "could not derive chain $1's $(_lc "$2") key at index $index — check ${1}_MNEMONIC"
  printf '%s' "$account"
}

_addr() {
  local pk addr
  read -r pk addr <<<"$(_key "$1" "$2")"
  printf '%s' "$addr"
}

# --progress quiet: this runs a dozen times, and each run would otherwise
# reprint the "Container besu-a Waiting / Healthy" block. Images are pulled by
# check_prerequisites so nothing slow is being hidden.
_ibc() {
  docker compose --progress quiet run --rm -T deployer "$@" --home /home/ibc
}

# _steps <ibc-deploy-stdout> — one indented line per step, in place of the raw
# JSON array `ibc deploy` prints. "executed" on a first run, "skipped" on a
# re-run, which is the idempotency of the deploy path made visible.
_steps() {
  printf '%s' "$1" | perl -0777 -ne \
    'print "    $1: $2\n" while /"name"\s*:\s*"([^"]+)"\s*,\s*"action"\s*:\s*"([^"]+)"/gs'
}

init_link() {
  mkdir -p "$KMS_KEYS_DIR"
  # Traversable by the unprivileged kms container (uid 10001) whatever the
  # host umask is — the 0644 on the keys below is not enough on its own.
  chmod 755 "$LOCAL_DIR/kms" "$KMS_KEYS_DIR"

  local name role pk addr file
  for name in "${CHAINS[@]}"; do
    for role in RELAYER ATTESTOR; do
      read -r pk addr <<<"$(_key "$name" "$role")"
      file="$KMS_KEYS_DIR/$(_lc "$role")-$(_lc "$name").hex"
      printf '%s\n' "$pk" > "$file"
      chmod 644 "$file"
    done
  done

  print_signers
}

print_signers() {
  local name role index addr
  log "kms keys (served on kms:9090, referenced by remoteKeyId in link/*.yml):"
  for name in "${CHAINS[@]}"; do
    for role in RELAYER ATTESTOR; do
      index=$(_chain_attr "$name" "${role}_INDEX")
      addr=$(_addr "$name" "$role")
      log "  $(_lc "$role")-$(_lc "$name")  $addr  (${name}_MNEMONIC index $index)"
      [[ "$role" == "RELAYER" && "$index" -ge "$FUNDED_ACCOUNTS" ]] \
        && warn "$addr is outside the funded range (FUNDED_ACCOUNTS=$FUNDED_ACCOUNTS)" \
                "and has no gas on chain $name"
    done
  done
  return 0
}

_write_link_env() {
  cat > "$LINK_ENV_FILE" <<EOF
# Generated by ./setup.sh — do not edit, do not commit.
A_ICS26_ROUTER=$1
B_ICS26_ROUTER=$2
A_CLIENT_ID=$3
B_CLIENT_ID=$3
EOF
  chmod 644 "$LINK_ENV_FILE"
}

_router() {
  local file router
  file="$DEPLOY_DIR/deployments/$1.json"
  router=$(perl -0777 -ne 'print $1 if /"router"\s*:\s*"([^"]+)"/' "$file" 2>/dev/null)
  [[ -n "$router" ]] || die "no router address in $file — did 'ibc deploy core' run?"
  printf '%s' "$router"
}

deploy_contracts() {
  [[ -d "$KMS_KEYS_DIR" ]] || die "$KMS_KEYS_DIR is missing — the init phase did not complete"
  mkdir -p "$DEPLOY_DIR/keys" "$DEPLOY_DIR/deployments"

  local name other pk addr out
  for name in "${CHAINS[@]}"; do
    if [[ ! -f "$DEPLOY_DIR/keys/deployer-$(_lc "$name").json" ]]; then
      read -r pk addr <<<"$(_key "$name" DEPLOYER)"
      _ibc keys import ecdsa "deployer-$(_lc "$name")" --private-key "0x$pk" >/dev/null \
        || die "[$name] importing the deployer key failed"
      log "[$name] imported deployer-$(_lc "$name") ($addr)"
    fi
  done

  for name in "${CHAINS[@]}"; do
    log "[$name] deploying the core IBC routing stack..."
    out=$(_ibc deploy core --chain "$(_chain_attr "$name" CHAIN_ID)" --yes) \
      || die "[$name] 'ibc deploy core' failed"
    _steps "$out"
  done

  for name in "${CHAINS[@]}"; do
    other=$(_other "$name")
    log "[$name] registering $LINK_CLIENT_ID tracking chain $other," \
        "authorizing attestor-$(_lc "$other") $(_addr "$other" ATTESTOR)..."
    out=$(_ibc deploy client \
      --chain "$(_chain_attr "$name" CHAIN_ID)" \
      --counterparty-chain "$(_chain_attr "$other" CHAIN_ID)" \
      --client-id "$LINK_CLIENT_ID" --counterparty-client-id "$LINK_CLIENT_ID" \
      --attestors "$(_addr "$other" ATTESTOR)" --threshold 1 --yes) \
      || die "[$name] 'ibc deploy client' failed"
    _steps "$out"
  done

  # Via locals, not inline `$(...)`: `die` in a command substitution only exits
  # the subshell, and errexit ignores a failed substitution in argument
  # position — inline, a missing router would print the error and then write an
  # empty address into link.env.
  local a_router b_router
  a_router=$(_router "$A_CHAIN_ID") || exit 1
  b_router=$(_router "$B_CHAIN_ID") || exit 1
  _write_link_env "$a_router" "$b_router" "$LINK_CLIENT_ID"
  log "Wrote the deployment into $LINK_ENV_FILE:"
  grep -v '^#' "$LINK_ENV_FILE" | while read -r line; do log "  $line"; done
}

# ── IFT transfer ────────────────────────────────────────────────────────────

# _token <chain-id> — the address of the $IFT_SYMBOL token in that chain's
# manifest. Anchored on the symbol rather than on the first "address" in the
# file: clients[] carries an "address" too and comes first, and a manifest can
# hold more than one token. "address" follows "symbol" inside the same object.
_token() {
  IFT_SYMBOL="$IFT_SYMBOL" perl -0777 -ne \
    'print $1 if /"symbol"\s*:\s*"\Q$ENV{IFT_SYMBOL}\E".*?"address"\s*:\s*"([^"]+)"/s' \
    "$DEPLOY_DIR/deployments/$1.json" 2>/dev/null
}

# _balance <chain-id> <ift> <address> — IFT balance in base units, empty when
# the query fails. Callers check for empty: an unguarded assignment would take
# the pipeline's non-zero status through pipefail into an errexit abort with no
# message, pre-empting their own diagnostics.
_balance() {
  _ibc query ift balance --chain "$1" --ift "$2" --address "$3" 2>/dev/null \
    | perl -0777 -ne 'print $1 if /"balance"\s*:\s*"([^"]+)"/' \
    || true
}

# Deploys one IFT token per chain and bridges them over the client registered by
# deploy_contracts.
#
# No short-circuit here: every step below is idempotent on the link side. `deploy
# ift` skips when a token with this symbol, name, and owner is already on chain,
# and `deploy ift-bridge` re-reads the on-chain bridge, so a re-run after a
# failed bridge retries the bridge instead of reporting the tokens as done and
# leaving the pair unbridged. Changing IFT_NAME or IFT_SYMBOL against a live
# stack mints a second token rather than replacing the first — './setup.sh
# clean' first.
deploy_ift() {
  local name out
  for name in "${CHAINS[@]}"; do
    # IFT rides on ICS27-GMP, and `deploy ift` refuses without it
    # ("no gmp deployment recorded for chain <id>").
    log "[$name] deploying the ICS27-GMP app..."
    out=$(_ibc deploy gmp --chain "$(_chain_attr "$name" CHAIN_ID)" --yes) \
      || die "[$name] 'ibc deploy gmp' failed"
    _steps "$out"

    log "[$name] deploying IFT $IFT_SYMBOL..."
    out=$(_ibc deploy ift --chain "$(_chain_attr "$name" CHAIN_ID)" \
      --name "$IFT_NAME" --symbol "$IFT_SYMBOL" --yes) \
      || die "[$name] 'ibc deploy ift' failed"
    _steps "$out"
  done

  log "bridging $(_token "$A_CHAIN_ID") <-> $(_token "$B_CHAIN_ID") over $LINK_CLIENT_ID..."
  out=$(_ibc deploy ift-bridge \
    --chain-a "$A_CHAIN_ID" --ift-a "$(_token "$A_CHAIN_ID")" \
    --chain-b "$B_CHAIN_ID" --ift-b "$(_token "$B_CHAIN_ID")" \
    --client-id "$LINK_CLIENT_ID" --yes) \
    || die "'ibc deploy ift-bridge' failed"
  _steps "$out"
}

# _leg <src> <dst> — move IFT_SEND_AMOUNT from src's deployer to dst's deployer
# and block until it lands. This is the end-to-end assertion for everything the
# earlier phases set up: the balance on dst only moves if *src's* attestor
# signed through kms and the relayer assembled that attestation into a proof
# dst's light client accepted.
#
# Direction is a parameter because the two legs exercise different halves of
# the stack. A -> B proves attestor-a and dst chain B's client; B -> A proves
# attestor-b and chain A's client. A demo that only ever went one way would
# leave attestor-b unverified.
_leg() {
  local src="$1" dst="$2"
  local src_id dst_id ift_src ift_dst sender receiver
  local before expected balance hash waited=0

  src_id=$(_chain_attr "$src" CHAIN_ID); dst_id=$(_chain_attr "$dst" CHAIN_ID)
  ift_src=$(_token "$src_id"); ift_dst=$(_token "$dst_id")
  [[ -n "$ift_src" && -n "$ift_dst" ]] \
    || die "no IFT address in the manifests — did 'ibc deploy ift' run?"
  sender=$(_addr "$src" DEPLOYER); receiver=$(_addr "$dst" DEPLOYER)

  # Wait on a delta, not an absolute balance: a second run starts with the first
  # run's tokens already in place, and an absolute check would pass before the
  # new packet ever landed. bigint because 1e18 is past what bash arithmetic can
  # be trusted with once the amounts are overridden.
  before=$(_balance "$dst_id" "$ift_dst" "$receiver")
  [[ "$before" =~ ^[0-9]+$ ]] \
    || die "could not read the chain $dst balance of $receiver, got '${before:-nothing}'"
  expected=$(perl -Mbigint -e 'print $ARGV[0] + $ARGV[1]' "$before" "$IFT_SEND_AMOUNT")

  log "[$src] sending $IFT_SEND_AMOUNT $IFT_SYMBOL to $receiver on chain $dst over $LINK_CLIENT_ID..."
  hash=$(_ibc tx ift send --chain "$src_id" --ift "$ift_src" --from "deployer-$(_lc "$src")" \
           --client-id "$LINK_CLIENT_ID" --to "$receiver" --amount "$IFT_SEND_AMOUNT" 2>/dev/null \
         | perl -0777 -ne 'print $1 if /"txHash"\s*:\s*"([^"]+)"/')
  [[ -n "$hash" ]] || die "'ibc tx ift send' on chain $src returned no transaction hash"
  log "      sent in $hash"

  # The relay is explicit. `relayer.connections[].autoRelay` exists in the config
  # schema but nothing in link reads it yet, so a packet sits unrelayed until it
  # is handed to the relayer by transaction hash. Run inside the relayer
  # container: the command dials the relayer's own gRPC, which only its config
  # describes.
  log "      handing the packet to the relayer..."
  docker compose --progress quiet exec -T relayer /opt/ibc relayer relay \
    --tx-hash "$hash" --chain-id "$src_id" --home /home/ibc >/dev/null \
    || die "'ibc relayer relay' failed for the $src -> $dst leg"

  log "      waiting for chain $dst's balance to go $before -> $expected..."
  while (( waited < IFT_RELAY_TIMEOUT )); do
    # A failed query is a retry, not a fatal: the poll outlives one transient
    # RPC hiccup and only the timeout below ends the wait.
    balance=$(_balance "$dst_id" "$ift_dst" "$receiver")
    if [[ "$balance" == "$expected" ]]; then
      log "      relayed $src -> $dst: $receiver holds $balance $IFT_SYMBOL on chain $dst"
      return 0
    fi
    sleep "$IFT_POLL_INTERVAL"
    (( waited += IFT_POLL_INTERVAL ))
  done

  die "chain $dst balance is '${balance:-unset}' after ${IFT_RELAY_TIMEOUT}s, expected $expected" \
      "— check 'docker compose logs relayer attestor-a attestor-b'"
}

# Top up chain A's deployer so there is something to send.
_mint_on_a() {
  local ift_a sender
  ift_a=$(_token "$A_CHAIN_ID"); sender=$(_addr A DEPLOYER)
  log "[A] minting $IFT_MINT_AMOUNT $IFT_SYMBOL to $sender..."
  _ibc tx ift mint --chain "$A_CHAIN_ID" --ift "$ift_a" --from deployer-a \
    --to "$sender" --amount "$IFT_MINT_AMOUNT" >/dev/null \
    || die "'ibc tx ift mint' failed"
}

_print_balances() {
  local a b
  a=$(_balance "$A_CHAIN_ID" "$(_token "$A_CHAIN_ID")" "$(_addr A DEPLOYER)")
  b=$(_balance "$B_CHAIN_ID" "$(_token "$B_CHAIN_ID")" "$(_addr B DEPLOYER)")
  log "$IFT_SYMBOL held by the deployer: chain A ${a:-?}, chain B ${b:-?}"
}

relay_ift_transfer() {
  _mint_on_a
  _leg A B
  _print_balances
}

# Send the same tokens straight back. The return leg needs no mint — it spends
# what the A -> B leg just delivered — so chain B ends where it started and
# chain A ends holding everything it minted.
relay_ift_roundtrip() {
  _mint_on_a
  _leg A B
  _leg B A
  _print_balances
}

stack_ready() {
  local key svc health

  for key in A_ICS26_ROUTER B_ICS26_ROUTER A_CLIENT_ID B_CLIENT_ID; do
    grep -qE "^$key=.+" "$LINK_ENV_FILE" 2>/dev/null || return 1
  done
  [[ -n "$(_token "$A_CHAIN_ID")" && -n "$(_token "$B_CHAIN_ID")" ]] || return 1

  health=$(docker compose ps --format '{{.Service}}|{{.Health}}' 2>/dev/null) || return 1
  for svc in besu-a besu-b "${LINK_SERVICES[@]}"; do
    grep -Fqx "$svc|healthy" <<<"$health" || return 1
  done
}

start_link() {
  local key
  for key in A_ICS26_ROUTER B_ICS26_ROUTER A_CLIENT_ID B_CLIENT_ID; do
    grep -qE "^$key=.+" "$LINK_ENV_FILE" 2>/dev/null \
      || die "$LINK_ENV_FILE has no $key — the deploy phase did not complete"
  done

  log "Bringing up ${LINK_SERVICES[*]}..."
  docker compose --progress quiet up -d --wait "${LINK_SERVICES[@]}" \
    || die "the link services did not come up healthy" \
           "— check 'docker compose logs ${LINK_SERVICES[*]}'"
}
