#!/usr/bin/env bash

# SPDX-License-Identifier: Apache-2.0

# IBC Link: kms keys, deployment, and service bring-up.
#
KMS_KEYS_DIR="$LOCAL_DIR/kms/keys"
LINK_ENV_FILE="$LOCAL_DIR/link.env"
DEPLOY_DIR="$LOCAL_DIR/deploy"

LINK_SERVICES=(kms attestor-a attestor-b ibc-link)
LINK_CLIENT_ID="link-$A_CHAIN_ID-$B_CHAIN_ID"

export DEPLOY_UID="${DEPLOY_UID:-$(id -u)}"
export DEPLOY_GID="${DEPLOY_GID:-$(id -g)}"

_lc()    { printf '%s' "$1" | tr 'A-Z' 'a-z'; }
_other() { [[ "$1" == "A" ]] && printf 'B' || printf 'A'; }

_key() {
  local index account
  index=$(_chain_attr "$1" "${2}_INDEX")
  [[ "$index" =~ ^[0-9]+$ ]] \
    || die "${1}_${2}_INDEX must be a non-negative integer, got '$index'"
  account=$(derive_account "$(_chain_mnemonic "$1")" "$index") \
    || die "could not derive chain $1's $(_lc "$2") key at index $index — check ${1}_MNEMONIC"
  printf '%s' "$account"
}

_addr() {
  local pk addr
  read -r pk addr <<<"$(_key "$1" "$2")"
  printf '%s' "$addr"
}

_ibc() {
  docker compose run --rm -T deployer "$@" --home /home/ibc
}

init_link() {
  mkdir -p "$KMS_KEYS_DIR"

  local name role pk addr file
  for name in "${CHAINS[@]}"; do
    for role in RELAYER ATTESTOR; do
      read -r pk addr <<<"$(_key "$name" "$role")"
      file="$KMS_KEYS_DIR/$(_lc "$role")-$(_lc "$name").hex"
      printf '%s\n' "$pk" > "$file"
      chmod 644 "$file"
    done
  done

  print_signers
}

print_signers() {
  local name role index addr
  log "kms keys (served on kms:9090, referenced by remoteKeyId in link/*.yml):"
  for name in "${CHAINS[@]}"; do
    for role in RELAYER ATTESTOR; do
      index=$(_chain_attr "$name" "${role}_INDEX")
      addr=$(_addr "$name" "$role")
      log "  $(_lc "$role")-$(_lc "$name")  $addr  (${name}_MNEMONIC index $index)"
      [[ "$role" == "RELAYER" && "$index" -ge "$FUNDED_ACCOUNTS" ]] \
        && warn "$addr is outside the funded range (FUNDED_ACCOUNTS=$FUNDED_ACCOUNTS)" \
                "and has no gas on chain $name"
    done
  done
  return 0
}

_write_link_env() {
  cat > "$LINK_ENV_FILE" <<EOF
# Generated by ./setup.sh — do not edit, do not commit.
A_ICS26_ROUTER=$1
B_ICS26_ROUTER=$2
A_CLIENT_ID=$3
B_CLIENT_ID=$3
EOF
  chmod 644 "$LINK_ENV_FILE"
}

_router() {
  local file router
  file="$DEPLOY_DIR/deployments/$1.json"
  router=$(perl -0777 -ne 'print $1 if /"router"\s*:\s*"([^"]+)"/' "$file" 2>/dev/null)
  [[ -n "$router" ]] || die "no router address in $file — did 'ibc deploy core' run?"
  printf '%s' "$router"
}

deploy_contracts() {
  [[ -d "$KMS_KEYS_DIR" ]] || die "$KMS_KEYS_DIR is missing — the init phase did not complete"
  mkdir -p "$DEPLOY_DIR/keys" "$DEPLOY_DIR/deployments"

  local name other pk addr
  for name in "${CHAINS[@]}"; do
    if [[ ! -f "$DEPLOY_DIR/keys/deployer-$(_lc "$name").json" ]]; then
      read -r pk addr <<<"$(_key "$name" DEPLOYER)"
      _ibc keys import ecdsa "deployer-$(_lc "$name")" --private-key "0x$pk" >/dev/null \
        || die "[$name] importing the deployer key failed"
      log "[$name] imported deployer-$(_lc "$name") ($addr)"
    fi
  done

  for name in "${CHAINS[@]}"; do
    log "[$name] deploying the core IBC routing stack..."
    _ibc deploy core --chain "$(_chain_attr "$name" CHAIN_ID)" --yes \
      || die "[$name] 'ibc deploy core' failed"
  done

  for name in "${CHAINS[@]}"; do
    other=$(_other "$name")
    log "[$name] registering $LINK_CLIENT_ID tracking chain $other," \
        "authorizing attestor-$(_lc "$other") $(_addr "$other" ATTESTOR)..."
    _ibc deploy client \
      --chain "$(_chain_attr "$name" CHAIN_ID)" \
      --counterparty-chain "$(_chain_attr "$other" CHAIN_ID)" \
      --client-id "$LINK_CLIENT_ID" --counterparty-client-id "$LINK_CLIENT_ID" \
      --attestors "$(_addr "$other" ATTESTOR)" --threshold 1 --yes \
      || die "[$name] 'ibc deploy client' failed"
  done

  _write_link_env "$(_router "$A_CHAIN_ID")" "$(_router "$B_CHAIN_ID")" "$LINK_CLIENT_ID"
  log "Wrote the deployment into $LINK_ENV_FILE:"
  grep -v '^#' "$LINK_ENV_FILE" | while read -r line; do log "  $line"; done
}

# ── IFT transfer ────────────────────────────────────────────────────────────

# _token <chain-id> — the IFT address from that chain's manifest. Scoped to the
# "tokens" array: clients[] carries an "address" too, and it comes first.
_token() {
  perl -0777 -ne 'print $1 if /"tokens"\s*:\s*\[.*?"address"\s*:\s*"([^"]+)"/s' \
    "$DEPLOY_DIR/deployments/$1.json" 2>/dev/null
}

# _balance <chain-id> <ift> <address> — IFT balance in base units.
_balance() {
  _ibc query ift balance --chain "$1" --ift "$2" --address "$3" 2>/dev/null \
    | perl -0777 -ne 'print $1 if /"balance"\s*:\s*"([^"]+)"/'
}

# Deploys one IFT token per chain and bridges them over the client registered by
# deploy_contracts. Skipped when both manifests already carry a token, so a
# re-run does not mint a second one.
deploy_ift() {
  local name other
  if [[ -n "$(_token "$A_CHAIN_ID")" && -n "$(_token "$B_CHAIN_ID")" ]]; then
    log "IFT already deployed on both chains"
    return 0
  fi

  for name in "${CHAINS[@]}"; do
    # IFT rides on ICS27-GMP, and `deploy ift` refuses without it
    # ("no gmp deployment recorded for chain <id>").
    log "[$name] deploying the ICS27-GMP app..."
    _ibc deploy gmp --chain "$(_chain_attr "$name" CHAIN_ID)" --yes \
      || die "[$name] 'ibc deploy gmp' failed"

    log "[$name] deploying IFT $IFT_SYMBOL..."
    _ibc deploy ift --chain "$(_chain_attr "$name" CHAIN_ID)" \
      --name "$IFT_NAME" --symbol "$IFT_SYMBOL" --yes \
      || die "[$name] 'ibc deploy ift' failed"
  done

  log "bridging $(_token "$A_CHAIN_ID") <-> $(_token "$B_CHAIN_ID") over $LINK_CLIENT_ID..."
  _ibc deploy ift-bridge \
    --chain-a "$A_CHAIN_ID" --ift-a "$(_token "$A_CHAIN_ID")" \
    --chain-b "$B_CHAIN_ID" --ift-b "$(_token "$B_CHAIN_ID")" \
    --client-id "$LINK_CLIENT_ID" --yes \
    || die "'ibc deploy ift-bridge' failed"
}

# Mint on chain A, send across, and wait for the relayer to deliver it. This is
# the end-to-end assertion for the whole example: the balance on chain B only
# moves if both attestors signed through kms and the relayer assembled their
# attestations into a proof the light client accepted.
relay_ift_transfer() {
  local ift_a ift_b sender receiver balance before expected waited=0
  ift_a=$(_token "$A_CHAIN_ID"); ift_b=$(_token "$B_CHAIN_ID")
  [[ -n "$ift_a" && -n "$ift_b" ]] || die "no IFT address in the manifests — did 'ibc deploy ift' run?"
  sender=$(_addr A DEPLOYER); receiver=$(_addr B DEPLOYER)

  # Wait on a delta, not an absolute balance: a second run starts with the first
  # run's tokens already on chain B, and an absolute check would pass before the
  # new packet ever landed. bigint because 1e18 is past what bash arithmetic can
  # be trusted with once the amounts are overridden.
  before=$(_balance "$B_CHAIN_ID" "$ift_b" "$receiver")
  [[ -n "$before" ]] || die "could not read the chain B balance of $receiver"
  expected=$(perl -Mbigint -e 'print $ARGV[0] + $ARGV[1]' "$before" "$IFT_SEND_AMOUNT")

  log "[A] minting $IFT_MINT_AMOUNT $IFT_SYMBOL to $sender..."
  _ibc tx ift mint --chain "$A_CHAIN_ID" --ift "$ift_a" --from deployer-a \
    --to "$sender" --amount "$IFT_MINT_AMOUNT" \
    || die "'ibc tx ift mint' failed"

  log "[A] sending $IFT_SEND_AMOUNT $IFT_SYMBOL to $receiver on chain B over $LINK_CLIENT_ID..."
  local hash
  hash=$(_ibc tx ift send --chain "$A_CHAIN_ID" --ift "$ift_a" --from deployer-a \
           --client-id "$LINK_CLIENT_ID" --to "$receiver" --amount "$IFT_SEND_AMOUNT" 2>/dev/null \
         | perl -0777 -ne 'print $1 if /"txHash"\s*:\s*"([^"]+)"/')
  [[ -n "$hash" ]] || die "'ibc tx ift send' returned no transaction hash"
  log "     sent in $hash"

  # The relay is explicit. `relayer.connections[].autoRelay` exists in the config
  # schema but nothing in link reads it yet, so a packet sits unrelayed until it
  # is handed to the relayer by transaction hash. Run inside ibc-link: the
  # command dials the relayer's own gRPC, which only its config describes.
  log "handing the packet to the relayer..."
  docker compose exec -T ibc-link /opt/ibc relayer relay \
    --tx-hash "$hash" --chain-id "$A_CHAIN_ID" --home /home/ibc >/dev/null \
    || die "'ibc relayer relay' failed"

  log "waiting for chain B's balance to go $before -> $expected..."
  while (( waited < IFT_RELAY_TIMEOUT )); do
    balance=$(_balance "$B_CHAIN_ID" "$ift_b" "$receiver")
    if [[ "$balance" == "$expected" ]]; then
      log "relayed: $receiver holds $balance $IFT_SYMBOL on chain B"
      log "         $sender holds $(_balance "$A_CHAIN_ID" "$ift_a" "$sender") $IFT_SYMBOL on chain A"
      return 0
    fi
    sleep "$IFT_POLL_INTERVAL"
    (( waited += IFT_POLL_INTERVAL ))
  done

  die "chain B balance is '${balance:-unset}' after ${IFT_RELAY_TIMEOUT}s, expected $expected" \
      "— check 'docker compose logs ibc-link attestor-a attestor-b'"
}

start_link() {
  # Written by deploy_contracts. Without it the attestors exit on
  # `invalid ics26 router address` and ibc-link on `.clientId required`.
  grep -qE '^A_ICS26_ROUTER=.+' "$LINK_ENV_FILE" 2>/dev/null \
    || die "$LINK_ENV_FILE holds no deployment — the deploy phase did not complete"

  log "Bringing up ${LINK_SERVICES[*]}..."
  docker compose up -d "${LINK_SERVICES[@]}"
}
