// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package relayer

import (
	"connectrpc.com/connect"
	"context"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRelayerApiServiceClient creates a new instance of MockRelayerApiServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRelayerApiServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRelayerApiServiceClient {
	mock := &MockRelayerApiServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRelayerApiServiceClient is an autogenerated mock type for the RelayerApiServiceClient type
type MockRelayerApiServiceClient struct {
	mock.Mock
}

type MockRelayerApiServiceClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRelayerApiServiceClient) EXPECT() *MockRelayerApiServiceClient_Expecter {
	return &MockRelayerApiServiceClient_Expecter{mock: &_m.Mock}
}

// Relay provides a mock function for the type MockRelayerApiServiceClient
func (_mock *MockRelayerApiServiceClient) Relay(context1 context.Context, request *connect.Request[RelayRequest]) (*connect.Response[RelayResponse], error) {
	ret := _mock.Called(context1, request)

	if len(ret) == 0 {
		panic("no return value specified for Relay")
	}

	var r0 *connect.Response[RelayResponse]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *connect.Request[RelayRequest]) (*connect.Response[RelayResponse], error)); ok {
		return returnFunc(context1, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *connect.Request[RelayRequest]) *connect.Response[RelayResponse]); ok {
		r0 = returnFunc(context1, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*connect.Response[RelayResponse])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *connect.Request[RelayRequest]) error); ok {
		r1 = returnFunc(context1, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRelayerApiServiceClient_Relay_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Relay'
type MockRelayerApiServiceClient_Relay_Call struct {
	*mock.Call
}

// Relay is a helper method to define mock.On call
//   - context1 context.Context
//   - request *connect.Request[RelayRequest]
func (_e *MockRelayerApiServiceClient_Expecter) Relay(context1 any, request any) *MockRelayerApiServiceClient_Relay_Call {
	return &MockRelayerApiServiceClient_Relay_Call{Call: _e.mock.On("Relay", context1, request)}
}

func (_c *MockRelayerApiServiceClient_Relay_Call) Run(run func(context1 context.Context, request *connect.Request[RelayRequest])) *MockRelayerApiServiceClient_Relay_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *connect.Request[RelayRequest]
		if args[1] != nil {
			arg1 = args[1].(*connect.Request[RelayRequest])
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRelayerApiServiceClient_Relay_Call) Return(response *connect.Response[RelayResponse], err error) *MockRelayerApiServiceClient_Relay_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockRelayerApiServiceClient_Relay_Call) RunAndReturn(run func(context1 context.Context, request *connect.Request[RelayRequest]) (*connect.Response[RelayResponse], error)) *MockRelayerApiServiceClient_Relay_Call {
	_c.Call.Return(run)
	return _c
}
