// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: relayer.proto

package relayer

import (
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"

	connect "connectrpc.com/connect"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// RelayerApiServiceName is the fully-qualified name of the RelayerApiService service.
	RelayerApiServiceName = "ibc.v2.relayer.RelayerApiService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// RelayerApiServiceRelayProcedure is the fully-qualified name of the RelayerApiService's Relay RPC.
	RelayerApiServiceRelayProcedure = "/ibc.v2.relayer.RelayerApiService/Relay"
	// RelayerApiServiceStatusProcedure is the fully-qualified name of the RelayerApiService's Status
	// RPC.
	RelayerApiServiceStatusProcedure = "/ibc.v2.relayer.RelayerApiService/Status"
)

// RelayerApiServiceClient is a client for the ibc.v2.relayer.RelayerApiService service.
type RelayerApiServiceClient interface {
	// Relay will track the status of a transfer, and submit the transactions
	// required to complete the transfer via the bridging protocol.
	Relay(context.Context, *connect.Request[RelayRequest]) (*connect.Response[RelayResponse], error)
	// Status returns per-packet transfer status for a transaction previously
	// submitted via Relay.
	Status(context.Context, *connect.Request[StatusRequest]) (*connect.Response[StatusResponse], error)
}

// NewRelayerApiServiceClient constructs a client for the ibc.v2.relayer.RelayerApiService service.
// By default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped
// responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewRelayerApiServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) RelayerApiServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	relayerApiServiceMethods := File_relayer_proto.Services().ByName("RelayerApiService").Methods()
	return &relayerApiServiceClient{
		relay: connect.NewClient[RelayRequest, RelayResponse](
			httpClient,
			baseURL+RelayerApiServiceRelayProcedure,
			connect.WithSchema(relayerApiServiceMethods.ByName("Relay")),
			connect.WithClientOptions(opts...),
		),
		status: connect.NewClient[StatusRequest, StatusResponse](
			httpClient,
			baseURL+RelayerApiServiceStatusProcedure,
			connect.WithSchema(relayerApiServiceMethods.ByName("Status")),
			connect.WithClientOptions(opts...),
		),
	}
}

// relayerApiServiceClient implements RelayerApiServiceClient.
type relayerApiServiceClient struct {
	relay  *connect.Client[RelayRequest, RelayResponse]
	status *connect.Client[StatusRequest, StatusResponse]
}

// Relay calls ibc.v2.relayer.RelayerApiService.Relay.
func (c *relayerApiServiceClient) Relay(ctx context.Context, req *connect.Request[RelayRequest]) (*connect.Response[RelayResponse], error) {
	return c.relay.CallUnary(ctx, req)
}

// Status calls ibc.v2.relayer.RelayerApiService.Status.
func (c *relayerApiServiceClient) Status(ctx context.Context, req *connect.Request[StatusRequest]) (*connect.Response[StatusResponse], error) {
	return c.status.CallUnary(ctx, req)
}

// RelayerApiServiceHandler is an implementation of the ibc.v2.relayer.RelayerApiService service.
type RelayerApiServiceHandler interface {
	// Relay will track the status of a transfer, and submit the transactions
	// required to complete the transfer via the bridging protocol.
	Relay(context.Context, *connect.Request[RelayRequest]) (*connect.Response[RelayResponse], error)
	// Status returns per-packet transfer status for a transaction previously
	// submitted via Relay.
	Status(context.Context, *connect.Request[StatusRequest]) (*connect.Response[StatusResponse], error)
}

// NewRelayerApiServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewRelayerApiServiceHandler(svc RelayerApiServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	relayerApiServiceMethods := File_relayer_proto.Services().ByName("RelayerApiService").Methods()
	relayerApiServiceRelayHandler := connect.NewUnaryHandler(
		RelayerApiServiceRelayProcedure,
		svc.Relay,
		connect.WithSchema(relayerApiServiceMethods.ByName("Relay")),
		connect.WithHandlerOptions(opts...),
	)
	relayerApiServiceStatusHandler := connect.NewUnaryHandler(
		RelayerApiServiceStatusProcedure,
		svc.Status,
		connect.WithSchema(relayerApiServiceMethods.ByName("Status")),
		connect.WithHandlerOptions(opts...),
	)
	return "/ibc.v2.relayer.RelayerApiService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case RelayerApiServiceRelayProcedure:
			relayerApiServiceRelayHandler.ServeHTTP(w, r)
		case RelayerApiServiceStatusProcedure:
			relayerApiServiceStatusHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedRelayerApiServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedRelayerApiServiceHandler struct{}

func (UnimplementedRelayerApiServiceHandler) Relay(context.Context, *connect.Request[RelayRequest]) (*connect.Response[RelayResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ibc.v2.relayer.RelayerApiService.Relay is not implemented"))
}

func (UnimplementedRelayerApiServiceHandler) Status(context.Context, *connect.Request[StatusRequest]) (*connect.Response[StatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ibc.v2.relayer.RelayerApiService.Status is not implemented"))
}
