syntax = "proto3";

package ibc.v2.attestor;

option go_package = "github.com/cosmos/ibc/link/api/v2/attestor";

// Service definition for retrieving attestations.
service AttestationService {
  // Returns the latest height the attestor will generate attestations for.
  rpc LatestAttestableHeight(LatestAttestableHeightRequest)
      returns (LatestAttestableHeightResponse);
}

message LatestAttestableHeightRequest { string attestor = 1; }

message LatestAttestableHeightResponse { uint64 height = 1; }
