// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlite

type RelaySubmission struct {
	ID            int64
	SourceChainID string
	SourceTxHash  string
	CreatedAt     string
}
