// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: relayer_submissions.sql

package sqlite

import (
	"context"
)

const getRelaySubmission = `-- name: GetRelaySubmission :one
SELECT id, source_chain_id, source_tx_hash, created_at
FROM relay_submissions
WHERE source_chain_id = ?1
AND source_tx_hash = ?2
`

func (q *Queries) GetRelaySubmission(ctx context.Context, chainID string, txHash string) (RelaySubmission, error) {
	row := q.db.QueryRowContext(ctx, getRelaySubmission, chainID, txHash)
	var i RelaySubmission
	err := row.Scan(
		&i.ID,
		&i.SourceChainID,
		&i.SourceTxHash,
		&i.CreatedAt,
	)
	return i, err
}

const upsertRelaySubmission = `-- name: UpsertRelaySubmission :exec
INSERT INTO relay_submissions (source_chain_id, source_tx_hash)
VALUES (?1, ?2)
ON CONFLICT (source_chain_id, source_tx_hash) DO NOTHING
`

func (q *Queries) UpsertRelaySubmission(ctx context.Context, chainID string, txHash string) error {
	_, err := q.db.ExecContext(ctx, upsertRelaySubmission, chainID, txHash)
	return err
}
