// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: relayer.proto

package relayer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PacketState int32

const (
	PacketState_PACKET_STATE_UNSPECIFIED PacketState = 0
	// The packet was discovered but has not been selected by this relayer
	// instance. Another relayer may still deliver it.
	PacketState_PACKET_STATE_NOT_SELECTED PacketState = 1
	// The relayer is still processing the packet.
	PacketState_PACKET_STATE_PENDING PacketState = 2
	// The packet completed with a successful acknowledgement on the source
	// chain.
	PacketState_PACKET_STATE_SUCCEEDED PacketState = 3
	// The packet completed with a timeout refund on the source chain.
	PacketState_PACKET_STATE_TIMED_OUT PacketState = 4
	// The packet completed with an error acknowledgement on the source chain.
	PacketState_PACKET_STATE_REJECTED PacketState = 5
	// A permanent error prevents the relayer from processing the packet.
	PacketState_PACKET_STATE_RELAY_FAILED PacketState = 6
)

// Enum value maps for PacketState.
var (
	PacketState_name = map[int32]string{
		0: "PACKET_STATE_UNSPECIFIED",
		1: "PACKET_STATE_NOT_SELECTED",
		2: "PACKET_STATE_PENDING",
		3: "PACKET_STATE_SUCCEEDED",
		4: "PACKET_STATE_TIMED_OUT",
		5: "PACKET_STATE_REJECTED",
		6: "PACKET_STATE_RELAY_FAILED",
	}
	PacketState_value = map[string]int32{
		"PACKET_STATE_UNSPECIFIED":  0,
		"PACKET_STATE_NOT_SELECTED": 1,
		"PACKET_STATE_PENDING":      2,
		"PACKET_STATE_SUCCEEDED":    3,
		"PACKET_STATE_TIMED_OUT":    4,
		"PACKET_STATE_REJECTED":     5,
		"PACKET_STATE_RELAY_FAILED": 6,
	}
)

func (x PacketState) Enum() *PacketState {
	p := new(PacketState)
	*p = x
	return p
}

func (x PacketState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PacketState) Descriptor() protoreflect.EnumDescriptor {
	return file_relayer_proto_enumTypes[0].Descriptor()
}

func (PacketState) Type() protoreflect.EnumType {
	return &file_relayer_proto_enumTypes[0]
}

func (x PacketState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PacketState.Descriptor instead.
func (PacketState) EnumDescriptor() ([]byte, []int) {
	return file_relayer_proto_rawDescGZIP(), []int{0}
}

type RelayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxHash        string                 `protobuf:"bytes,1,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	SourceChainId string                 `protobuf:"bytes,2,opt,name=source_chain_id,json=sourceChainId,proto3" json:"source_chain_id,omitempty"`
	// Selection is required and controls only this relayer instance; IBC
	// relaying remains permissionless.
	//
	// Types that are valid to be assigned to Selection:
	//
	//	*RelayRequest_AllPackets
	//	*RelayRequest_SelectedPackets
	Selection     isRelayRequest_Selection `protobuf_oneof:"selection"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayRequest) Reset() {
	*x = RelayRequest{}
	mi := &file_relayer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayRequest) ProtoMessage() {}

func (x *RelayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_relayer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayRequest.ProtoReflect.Descriptor instead.
func (*RelayRequest) Descriptor() ([]byte, []int) {
	return file_relayer_proto_rawDescGZIP(), []int{0}
}

func (x *RelayRequest) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *RelayRequest) GetSourceChainId() string {
	if x != nil {
		return x.SourceChainId
	}
	return ""
}

func (x *RelayRequest) GetSelection() isRelayRequest_Selection {
	if x != nil {
		return x.Selection
	}
	return nil
}

func (x *RelayRequest) GetAllPackets() *AllPackets {
	if x != nil {
		if x, ok := x.Selection.(*RelayRequest_AllPackets); ok {
			return x.AllPackets
		}
	}
	return nil
}

func (x *RelayRequest) GetSelectedPackets() *SelectedPackets {
	if x != nil {
		if x, ok := x.Selection.(*RelayRequest_SelectedPackets); ok {
			return x.SelectedPackets
		}
	}
	return nil
}

type isRelayRequest_Selection interface {
	isRelayRequest_Selection()
}

type RelayRequest_AllPackets struct {
	AllPackets *AllPackets `protobuf:"bytes,3,opt,name=all_packets,json=allPackets,proto3,oneof"`
}

type RelayRequest_SelectedPackets struct {
	SelectedPackets *SelectedPackets `protobuf:"bytes,4,opt,name=selected_packets,json=selectedPackets,proto3,oneof"`
}

func (*RelayRequest_AllPackets) isRelayRequest_Selection() {}

func (*RelayRequest_SelectedPackets) isRelayRequest_Selection() {}

// AllPackets selects every packet in the transaction for which this relayer
// has a configured client and route; packets without one are skipped, and the
// request succeeds even if that leaves nothing to relay.
type AllPackets struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllPackets) Reset() {
	*x = AllPackets{}
	mi := &file_relayer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllPackets) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllPackets) ProtoMessage() {}

func (x *AllPackets) ProtoReflect() protoreflect.Message {
	mi := &file_relayer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllPackets.ProtoReflect.Descriptor instead.
func (*AllPackets) Descriptor() ([]byte, []int) {
	return file_relayer_proto_rawDescGZIP(), []int{1}
}

// SelectedPackets selects exactly the listed packets. The request fails if any
// packet is absent or not configured and routed. Packets already selected,
// in flight, or terminal are successful no-ops.
type SelectedPackets struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Packets       []*PacketSelector      `protobuf:"bytes,1,rep,name=packets,proto3" json:"packets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SelectedPackets) Reset() {
	*x = SelectedPackets{}
	mi := &file_relayer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelectedPackets) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectedPackets) ProtoMessage() {}

func (x *SelectedPackets) ProtoReflect() protoreflect.Message {
	mi := &file_relayer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectedPackets.ProtoReflect.Descriptor instead.
func (*SelectedPackets) Descriptor() ([]byte, []int) {
	return file_relayer_proto_rawDescGZIP(), []int{2}
}

func (x *SelectedPackets) GetPackets() []*PacketSelector {
	if x != nil {
		return x.Packets
	}
	return nil
}

type PacketSelector struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SourceClientId string                 `protobuf:"bytes,1,opt,name=source_client_id,json=sourceClientId,proto3" json:"source_client_id,omitempty"`
	SequenceNumber uint64                 `protobuf:"varint,2,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PacketSelector) Reset() {
	*x = PacketSelector{}
	mi := &file_relayer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PacketSelector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PacketSelector) ProtoMessage() {}

func (x *PacketSelector) ProtoReflect() protoreflect.Message {
	mi := &file_relayer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PacketSelector.ProtoReflect.Descriptor instead.
func (*PacketSelector) Descriptor() ([]byte, []int) {
	return file_relayer_proto_rawDescGZIP(), []int{3}
}

func (x *PacketSelector) GetSourceClientId() string {
	if x != nil {
		return x.SourceClientId
	}
	return ""
}

func (x *PacketSelector) GetSequenceNumber() uint64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

type RelayResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayResponse) Reset() {
	*x = RelayResponse{}
	mi := &file_relayer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayResponse) ProtoMessage() {}

func (x *RelayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_relayer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayResponse.ProtoReflect.Descriptor instead.
func (*RelayResponse) Descriptor() ([]byte, []int) {
	return file_relayer_proto_rawDescGZIP(), []int{4}
}

type PacketsRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Filter *PacketFilter          `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	// Zero applies the default of 100; values above 1000 are capped.
	Limit uint32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	// Packets inserted between requests shift later pages; paging is not a
	// consistent snapshot.
	Offset        uint32 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PacketsRequest) Reset() {
	*x = PacketsRequest{}
	mi := &file_relayer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PacketsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PacketsRequest) ProtoMessage() {}

func (x *PacketsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_relayer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PacketsRequest.ProtoReflect.Descriptor instead.
func (*PacketsRequest) Descriptor() ([]byte, []int) {
	return file_relayer_proto_rawDescGZIP(), []int{5}
}

func (x *PacketsRequest) GetFilter() *PacketFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *PacketsRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *PacketsRequest) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

// Every field is optional; all present fields must match.
type PacketFilter struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	SourceChainId       *string                `protobuf:"bytes,1,opt,name=source_chain_id,json=sourceChainId,proto3,oneof" json:"source_chain_id,omitempty"`
	DestinationChainId  *string                `protobuf:"bytes,2,opt,name=destination_chain_id,json=destinationChainId,proto3,oneof" json:"destination_chain_id,omitempty"`
	SourceClientId      *string                `protobuf:"bytes,3,opt,name=source_client_id,json=sourceClientId,proto3,oneof" json:"source_client_id,omitempty"`
	DestinationClientId *string                `protobuf:"bytes,4,opt,name=destination_client_id,json=destinationClientId,proto3,oneof" json:"destination_client_id,omitempty"`
	// PACKET_STATE_PENDING covers every in-flight internal status.
	State *PacketState `protobuf:"varint,5,opt,name=state,proto3,enum=ibc.v2.relayer.PacketState,oneof" json:"state,omitempty"`
	// Matches the SendPacket transaction only, never recv, ack, or timeout.
	SourceTxHash   *string `protobuf:"bytes,6,opt,name=source_tx_hash,json=sourceTxHash,proto3,oneof" json:"source_tx_hash,omitempty"`
	SequenceNumber *uint64 `protobuf:"varint,7,opt,name=sequence_number,json=sequenceNumber,proto3,oneof" json:"sequence_number,omitempty"`
	// Unix seconds, inclusive, against the packet's discovery time.
	CreatedFrom   *int64 `protobuf:"varint,8,opt,name=created_from,json=createdFrom,proto3,oneof" json:"created_from,omitempty"`
	CreatedTo     *int64 `protobuf:"varint,9,opt,name=created_to,json=createdTo,proto3,oneof" json:"created_to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PacketFilter) Reset() {
	*x = PacketFilter{}
	mi := &file_relayer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PacketFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PacketFilter) ProtoMessage() {}

func (x *PacketFilter) ProtoReflect() protoreflect.Message {
	mi := &file_relayer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PacketFilter.ProtoReflect.Descriptor instead.
func (*PacketFilter) Descriptor() ([]byte, []int) {
	return file_relayer_proto_rawDescGZIP(), []int{6}
}

func (x *PacketFilter) GetSourceChainId() string {
	if x != nil && x.SourceChainId != nil {
		return *x.SourceChainId
	}
	return ""
}

func (x *PacketFilter) GetDestinationChainId() string {
	if x != nil && x.DestinationChainId != nil {
		return *x.DestinationChainId
	}
	return ""
}

func (x *PacketFilter) GetSourceClientId() string {
	if x != nil && x.SourceClientId != nil {
		return *x.SourceClientId
	}
	return ""
}

func (x *PacketFilter) GetDestinationClientId() string {
	if x != nil && x.DestinationClientId != nil {
		return *x.DestinationClientId
	}
	return ""
}

func (x *PacketFilter) GetState() PacketState {
	if x != nil && x.State != nil {
		return *x.State
	}
	return PacketState_PACKET_STATE_UNSPECIFIED
}

func (x *PacketFilter) GetSourceTxHash() string {
	if x != nil && x.SourceTxHash != nil {
		return *x.SourceTxHash
	}
	return ""
}

func (x *PacketFilter) GetSequenceNumber() uint64 {
	if x != nil && x.SequenceNumber != nil {
		return *x.SequenceNumber
	}
	return 0
}

func (x *PacketFilter) GetCreatedFrom() int64 {
	if x != nil && x.CreatedFrom != nil {
		return *x.CreatedFrom
	}
	return 0
}

func (x *PacketFilter) GetCreatedTo() int64 {
	if x != nil && x.CreatedTo != nil {
		return *x.CreatedTo
	}
	return 0
}

type PacketsResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Packets []*PacketStatus        `protobuf:"bytes,1,rep,name=packets,proto3" json:"packets,omitempty"`
	// More packets match beyond this page. No exact count is reported: producing
	// one would visit every matching packet on every request.
	HasMore       bool `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PacketsResponse) Reset() {
	*x = PacketsResponse{}
	mi := &file_relayer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PacketsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PacketsResponse) ProtoMessage() {}

func (x *PacketsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_relayer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PacketsResponse.ProtoReflect.Descriptor instead.
func (*PacketsResponse) Descriptor() ([]byte, []int) {
	return file_relayer_proto_rawDescGZIP(), []int{7}
}

func (x *PacketsResponse) GetPackets() []*PacketStatus {
	if x != nil {
		return x.Packets
	}
	return nil
}

func (x *PacketsResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type TransactionInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxHash        string                 `protobuf:"bytes,1,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	ChainId       string                 `protobuf:"bytes,2,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionInfo) Reset() {
	*x = TransactionInfo{}
	mi := &file_relayer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionInfo) ProtoMessage() {}

func (x *TransactionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_relayer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionInfo.ProtoReflect.Descriptor instead.
func (*TransactionInfo) Descriptor() ([]byte, []int) {
	return file_relayer_proto_rawDescGZIP(), []int{8}
}

func (x *TransactionInfo) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *TransactionInfo) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

type PacketStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	State PacketState            `protobuf:"varint,1,opt,name=state,proto3,enum=ibc.v2.relayer.PacketState" json:"state,omitempty"`
	// Together with source_client_id, identifies the packet.
	SequenceNumber uint64 `protobuf:"varint,2,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	// Together with sequence_number, identifies the packet.
	SourceClientId string `protobuf:"bytes,3,opt,name=source_client_id,json=sourceClientId,proto3" json:"source_client_id,omitempty"`
	// The source-chain SendPacket transaction. Always present.
	SendTx *TransactionInfo `protobuf:"bytes,4,opt,name=send_tx,json=sendTx,proto3" json:"send_tx,omitempty"`
	// The destination-chain receive transaction, once submitted or discovered.
	RecvTx *TransactionInfo `protobuf:"bytes,5,opt,name=recv_tx,json=recvTx,proto3" json:"recv_tx,omitempty"`
	// The source-chain acknowledgement transaction. Present for succeeded and
	// rejected packets, and may be present while pending.
	AckTx *TransactionInfo `protobuf:"bytes,6,opt,name=ack_tx,json=ackTx,proto3" json:"ack_tx,omitempty"`
	// The source-chain timeout transaction. Present for timed-out packets, and
	// may be present while pending.
	TimeoutTx *TransactionInfo `protobuf:"bytes,7,opt,name=timeout_tx,json=timeoutTx,proto3" json:"timeout_tx,omitempty"`
	// Unix seconds.
	CreatedAt     int64 `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64 `protobuf:"varint,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PacketStatus) Reset() {
	*x = PacketStatus{}
	mi := &file_relayer_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PacketStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PacketStatus) ProtoMessage() {}

func (x *PacketStatus) ProtoReflect() protoreflect.Message {
	mi := &file_relayer_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PacketStatus.ProtoReflect.Descriptor instead.
func (*PacketStatus) Descriptor() ([]byte, []int) {
	return file_relayer_proto_rawDescGZIP(), []int{9}
}

func (x *PacketStatus) GetState() PacketState {
	if x != nil {
		return x.State
	}
	return PacketState_PACKET_STATE_UNSPECIFIED
}

func (x *PacketStatus) GetSequenceNumber() uint64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *PacketStatus) GetSourceClientId() string {
	if x != nil {
		return x.SourceClientId
	}
	return ""
}

func (x *PacketStatus) GetSendTx() *TransactionInfo {
	if x != nil {
		return x.SendTx
	}
	return nil
}

func (x *PacketStatus) GetRecvTx() *TransactionInfo {
	if x != nil {
		return x.RecvTx
	}
	return nil
}

func (x *PacketStatus) GetAckTx() *TransactionInfo {
	if x != nil {
		return x.AckTx
	}
	return nil
}

func (x *PacketStatus) GetTimeoutTx() *TransactionInfo {
	if x != nil {
		return x.TimeoutTx
	}
	return nil
}

func (x *PacketStatus) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *PacketStatus) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

var File_relayer_proto protoreflect.FileDescriptor

const file_relayer_proto_rawDesc = "" +
	"\n" +
	"\rrelayer.proto\x12\x0eibc.v2.relayer\"\xe9\x01\n" +
	"\fRelayRequest\x12\x17\n" +
	"\atx_hash\x18\x01 \x01(\tR\x06txHash\x12&\n" +
	"\x0fsource_chain_id\x18\x02 \x01(\tR\rsourceChainId\x12=\n" +
	"\vall_packets\x18\x03 \x01(\v2\x1a.ibc.v2.relayer.AllPacketsH\x00R\n" +
	"allPackets\x12L\n" +
	"\x10selected_packets\x18\x04 \x01(\v2\x1f.ibc.v2.relayer.SelectedPacketsH\x00R\x0fselectedPacketsB\v\n" +
	"\tselection\"\f\n" +
	"\n" +
	"AllPackets\"K\n" +
	"\x0fSelectedPackets\x128\n" +
	"\apackets\x18\x01 \x03(\v2\x1e.ibc.v2.relayer.PacketSelectorR\apackets\"c\n" +
	"\x0ePacketSelector\x12(\n" +
	"\x10source_client_id\x18\x01 \x01(\tR\x0esourceClientId\x12'\n" +
	"\x0fsequence_number\x18\x02 \x01(\x04R\x0esequenceNumber\"\x0f\n" +
	"\rRelayResponse\"t\n" +
	"\x0ePacketsRequest\x124\n" +
	"\x06filter\x18\x01 \x01(\v2\x1c.ibc.v2.relayer.PacketFilterR\x06filter\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\rR\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\rR\x06offset\"\xe4\x04\n" +
	"\fPacketFilter\x12+\n" +
	"\x0fsource_chain_id\x18\x01 \x01(\tH\x00R\rsourceChainId\x88\x01\x01\x125\n" +
	"\x14destination_chain_id\x18\x02 \x01(\tH\x01R\x12destinationChainId\x88\x01\x01\x12-\n" +
	"\x10source_client_id\x18\x03 \x01(\tH\x02R\x0esourceClientId\x88\x01\x01\x127\n" +
	"\x15destination_client_id\x18\x04 \x01(\tH\x03R\x13destinationClientId\x88\x01\x01\x126\n" +
	"\x05state\x18\x05 \x01(\x0e2\x1b.ibc.v2.relayer.PacketStateH\x04R\x05state\x88\x01\x01\x12)\n" +
	"\x0esource_tx_hash\x18\x06 \x01(\tH\x05R\fsourceTxHash\x88\x01\x01\x12,\n" +
	"\x0fsequence_number\x18\a \x01(\x04H\x06R\x0esequenceNumber\x88\x01\x01\x12&\n" +
	"\fcreated_from\x18\b \x01(\x03H\aR\vcreatedFrom\x88\x01\x01\x12\"\n" +
	"\n" +
	"created_to\x18\t \x01(\x03H\bR\tcreatedTo\x88\x01\x01B\x12\n" +
	"\x10_source_chain_idB\x17\n" +
	"\x15_destination_chain_idB\x13\n" +
	"\x11_source_client_idB\x18\n" +
	"\x16_destination_client_idB\b\n" +
	"\x06_stateB\x11\n" +
	"\x0f_source_tx_hashB\x12\n" +
	"\x10_sequence_numberB\x0f\n" +
	"\r_created_fromB\r\n" +
	"\v_created_to\"d\n" +
	"\x0fPacketsResponse\x126\n" +
	"\apackets\x18\x01 \x03(\v2\x1c.ibc.v2.relayer.PacketStatusR\apackets\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMore\"E\n" +
	"\x0fTransactionInfo\x12\x17\n" +
	"\atx_hash\x18\x01 \x01(\tR\x06txHash\x12\x19\n" +
	"\bchain_id\x18\x02 \x01(\tR\achainId\"\xbe\x03\n" +
	"\fPacketStatus\x121\n" +
	"\x05state\x18\x01 \x01(\x0e2\x1b.ibc.v2.relayer.PacketStateR\x05state\x12'\n" +
	"\x0fsequence_number\x18\x02 \x01(\x04R\x0esequenceNumber\x12(\n" +
	"\x10source_client_id\x18\x03 \x01(\tR\x0esourceClientId\x128\n" +
	"\asend_tx\x18\x04 \x01(\v2\x1f.ibc.v2.relayer.TransactionInfoR\x06sendTx\x128\n" +
	"\arecv_tx\x18\x05 \x01(\v2\x1f.ibc.v2.relayer.TransactionInfoR\x06recvTx\x126\n" +
	"\x06ack_tx\x18\x06 \x01(\v2\x1f.ibc.v2.relayer.TransactionInfoR\x05ackTx\x12>\n" +
	"\n" +
	"timeout_tx\x18\a \x01(\v2\x1f.ibc.v2.relayer.TransactionInfoR\ttimeoutTx\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\x03R\tupdatedAt*\xd6\x01\n" +
	"\vPacketState\x12\x1c\n" +
	"\x18PACKET_STATE_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19PACKET_STATE_NOT_SELECTED\x10\x01\x12\x18\n" +
	"\x14PACKET_STATE_PENDING\x10\x02\x12\x1a\n" +
	"\x16PACKET_STATE_SUCCEEDED\x10\x03\x12\x1a\n" +
	"\x16PACKET_STATE_TIMED_OUT\x10\x04\x12\x19\n" +
	"\x15PACKET_STATE_REJECTED\x10\x05\x12\x1d\n" +
	"\x19PACKET_STATE_RELAY_FAILED\x10\x062\xa9\x01\n" +
	"\x11RelayerApiService\x12F\n" +
	"\x05Relay\x12\x1c.ibc.v2.relayer.RelayRequest\x1a\x1d.ibc.v2.relayer.RelayResponse\"\x00\x12L\n" +
	"\aPackets\x12\x1e.ibc.v2.relayer.PacketsRequest\x1a\x1f.ibc.v2.relayer.PacketsResponse\"\x00B+Z)github.com/cosmos/ibc/link/api/v2/relayerb\x06proto3"

var (
	file_relayer_proto_rawDescOnce sync.Once
	file_relayer_proto_rawDescData []byte
)

func file_relayer_proto_rawDescGZIP() []byte {
	file_relayer_proto_rawDescOnce.Do(func() {
		file_relayer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_relayer_proto_rawDesc), len(file_relayer_proto_rawDesc)))
	})
	return file_relayer_proto_rawDescData
}

var file_relayer_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_relayer_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_relayer_proto_goTypes = []any{
	(PacketState)(0),        // 0: ibc.v2.relayer.PacketState
	(*RelayRequest)(nil),    // 1: ibc.v2.relayer.RelayRequest
	(*AllPackets)(nil),      // 2: ibc.v2.relayer.AllPackets
	(*SelectedPackets)(nil), // 3: ibc.v2.relayer.SelectedPackets
	(*PacketSelector)(nil),  // 4: ibc.v2.relayer.PacketSelector
	(*RelayResponse)(nil),   // 5: ibc.v2.relayer.RelayResponse
	(*PacketsRequest)(nil),  // 6: ibc.v2.relayer.PacketsRequest
	(*PacketFilter)(nil),    // 7: ibc.v2.relayer.PacketFilter
	(*PacketsResponse)(nil), // 8: ibc.v2.relayer.PacketsResponse
	(*TransactionInfo)(nil), // 9: ibc.v2.relayer.TransactionInfo
	(*PacketStatus)(nil),    // 10: ibc.v2.relayer.PacketStatus
}
var file_relayer_proto_depIdxs = []int32{
	2,  // 0: ibc.v2.relayer.RelayRequest.all_packets:type_name -> ibc.v2.relayer.AllPackets
	3,  // 1: ibc.v2.relayer.RelayRequest.selected_packets:type_name -> ibc.v2.relayer.SelectedPackets
	4,  // 2: ibc.v2.relayer.SelectedPackets.packets:type_name -> ibc.v2.relayer.PacketSelector
	7,  // 3: ibc.v2.relayer.PacketsRequest.filter:type_name -> ibc.v2.relayer.PacketFilter
	0,  // 4: ibc.v2.relayer.PacketFilter.state:type_name -> ibc.v2.relayer.PacketState
	10, // 5: ibc.v2.relayer.PacketsResponse.packets:type_name -> ibc.v2.relayer.PacketStatus
	0,  // 6: ibc.v2.relayer.PacketStatus.state:type_name -> ibc.v2.relayer.PacketState
	9,  // 7: ibc.v2.relayer.PacketStatus.send_tx:type_name -> ibc.v2.relayer.TransactionInfo
	9,  // 8: ibc.v2.relayer.PacketStatus.recv_tx:type_name -> ibc.v2.relayer.TransactionInfo
	9,  // 9: ibc.v2.relayer.PacketStatus.ack_tx:type_name -> ibc.v2.relayer.TransactionInfo
	9,  // 10: ibc.v2.relayer.PacketStatus.timeout_tx:type_name -> ibc.v2.relayer.TransactionInfo
	1,  // 11: ibc.v2.relayer.RelayerApiService.Relay:input_type -> ibc.v2.relayer.RelayRequest
	6,  // 12: ibc.v2.relayer.RelayerApiService.Packets:input_type -> ibc.v2.relayer.PacketsRequest
	5,  // 13: ibc.v2.relayer.RelayerApiService.Relay:output_type -> ibc.v2.relayer.RelayResponse
	8,  // 14: ibc.v2.relayer.RelayerApiService.Packets:output_type -> ibc.v2.relayer.PacketsResponse
	13, // [13:15] is the sub-list for method output_type
	11, // [11:13] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_relayer_proto_init() }
func file_relayer_proto_init() {
	if File_relayer_proto != nil {
		return
	}
	file_relayer_proto_msgTypes[0].OneofWrappers = []any{
		(*RelayRequest_AllPackets)(nil),
		(*RelayRequest_SelectedPackets)(nil),
	}
	file_relayer_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_relayer_proto_rawDesc), len(file_relayer_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_relayer_proto_goTypes,
		DependencyIndexes: file_relayer_proto_depIdxs,
		EnumInfos:         file_relayer_proto_enumTypes,
		MessageInfos:      file_relayer_proto_msgTypes,
	}.Build()
	File_relayer_proto = out.File
	file_relayer_proto_goTypes = nil
	file_relayer_proto_depIdxs = nil
}
