# SPDX-License-Identifier: Apache-2.0

name: License Headers

on:
  push:
    branches: [main]
  pull_request:
  merge_group:
  workflow_dispatch:

permissions: read-all

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Check DCO commit hook
        run: .githooks/test-commit-msg
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7
        with:
          go-version-file: link/go.mod
          cache-dependency-path: link/go.sum
      - run: make check-license-headers
