# SPDX-License-Identifier: Apache-2.0

name: PR Lint

on:
  pull_request_target:
    types: [opened, edited, synchronize, reopened]

permissions: read-all

jobs:
  validate-title:
    name: Validate PR title
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    timeout-minutes: 5
    steps:
      - uses: amannn/action-semantic-pull-request@48f256284bd46cdaab1048c3721360e808335d50 # v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
