# SPDX-License-Identifier: Apache-2.0

name: Spec

on:
  push:
    paths:
      - "README.md"
      - "spec/**"
      - ".github/workflows/spec.yml"
      - ".github/workflows/link-check-config.json"
  pull_request:
    branches: [main, development]
    paths:
      - "README.md"
      - "spec/**"
      - ".github/workflows/spec.yml"
      - ".github/workflows/link-check-config.json"

permissions: read-all

jobs:
  markdown-lint:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 0
      - uses: tj-actions/changed-files@716b1e13042866565e00e85fd4ec490e186c4a2f # v41
        id: changed-files
        with:
          files: "README.md,spec/**/*.md"
          separator: ","
      - uses: DavidAnson/markdownlint-cli2-action@ed4dec634fd2ef689c7061d5647371d8248064f1 # v13
        if: steps.changed-files.outputs.any_changed == 'true'
        with:
          config: "spec/.markdownlint.jsonc"
          globs: ${{ steps.changed-files.outputs.all_changed_files }}
          separator: ","
